{
 "title": "AWS Serverless Observability Monitoring",
 "description": "This dashboard offers deep insights into the AWS Serverless World, based on the principles of Cloud Native Observability theory (Logs, Metrics (RED/USE patterns), Traces, Service maps, etc.)",
 "tags": [
  "AWS",
  "CloudWatch",
  "Observability"
 ],
 "time": { "from": "2024-10-11T09:35:00.000Z", "to": "2024-10-11T09:45:00.000Z" },
 "templating": {
  "list": [
   { "name": "cloudwatch", "label": "🔴CW Data source", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "🌐Region",
    "query": {}
   },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" },
   { "name": "refresh_interval", "label": "🔄Refresh interval", "query": "off,1m,3m,5m,15m,30m,1h" },
   {
    "name": "api_gtwy_log_group",
    "label": "🔴Log Group(CW)",
    "query": {}
   },
   { "name": "api_gtwy_request_id", "label": "🔴🟠Target Request Id", "query": ".*" },
   {
    "name": "lambda_log_group",
    "label": "🟠Log Group",
    "query": {}
   },
   {
    "name": "cloud_trail_log_groups",
    "label": "🔴Log Group(CT)",
    "query": {}
   },
   {
    "name": "limit",
    "label": "🔴🟠🔴limit",
    "query": "100, 25, 50, 75, 150, 200, 250, 300 "
   }
  ]
 },
 "panels": [
  {
   "title": "📑Logs: 🔴API-Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "volkovlabs-image-panel",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "API-Gateway",
          "type": "string",
          "values": [
           "iVBORw0KGgoAAAANSUhEUgAAAFAAAABSCAYAAADD2VOmAAABYWlDQ1BrQ0dDb2xvclNwYWNlRGlzcGxheVAzAAAokWNgYFJJLCjIYWFgYMjNKykKcndSiIiMUmB/yMAOhLwMYgwKicnFBY4BAT5AJQwwGhV8u8bACKIv64LMOiU1tUm1XsDXYqbw1YuvRJsw1aMArpTU4mQg/QeIU5MLikoYGBhTgGzl8pICELsDyBYpAjoKyJ4DYqdD2BtA7CQI+whYTUiQM5B9A8hWSM5IBJrB+API1klCEk9HYkPtBQFul8zigpzESoUAYwKuJQOUpFaUgGjn/ILKosz0jBIFR2AopSp45iXr6SgYGRiaMzCAwhyi+nMgOCwZxc4gxJrvMzDY7v////9uhJjXfgaGjUCdXDsRYhoWDAyC3AwMJ3YWJBYlgoWYgZgpLY2B4dNyBgbeSAYG4QtAPdHFacZGYHlGHicGBtZ7//9/VmNgYJ/MwPB3wv//vxf9//93MVDzHQaGA3kAFSFl7jXH0fsAAAB4ZVhJZk1NACoAAAAIAAUBEgADAAAAAQABAAABGgAFAAAAAQAAAEoBGwAFAAAAAQAAAFIBKAADAAAAAQACAACHaQAEAAAAAQAAAFoAAAAAAAAASAAAAAEAAABIAAAAAQACoAIABAAAAAEAAABQoAMABAAAAAEAAABSAAAAAPfS+p4AAAAJcEhZcwAACxMAAAsTAQCanBgAAAIEaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj40MDI8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+NDExPC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+Cvh0/TIAACwDSURBVHgBpX0JmF5Xed53/2V2zSpZu2RJXiV5k2y8yDaGUIMBG+xUFExpiMPSJA15TCkECEVJTUnzNA2hpAUa9iUBsXnBJmBjgzGWsWVjY3mTLNmWLMkazWhmNNu/3r7v+51z7z+S/NA+OfP/95zznW8/6z333H8SQ9j5ux9bV0qLf50kNtVs2jTiWYBn0jSdtiSZSpvNqcRsspkUPE5tstBk3qaLxdpUY6Y53Sg3ZidfHJs9f/vna+T5LwmpWWJbtiS2Y22yffedhc7VSyD++LAWoCeOBwvycmVrBxan9syBdOuCHenmrVthgkHcbw/7rv2vQ5VmfUmhkK4G9hmJpevTxE6VYnuu3fJnJ88b+uRoZcpKhaIVBAVK4J1CBNONtGl1eJhxrdlgaQXwChKzdHSSplOATUHABOIJsJlAeryJb8FsrJkiX0jGk2ZjIimUJhqomCIqo16uTDUqqIBFa2bP//x7/8UV8NvdMRfjoau3dA0m1XlJuW0gTQoLLG0uTlJbAqyVqMoVsG857Flmabqgq9RWKsNHPeV22z89fkiu2n3dllt6Su1XHxgbOVpvNNoLSQF8En4oCXGBF4aCR0lSLBSsCHhBceJp4BOXdMCFbA8QrtBETdD5WUVYSmdVoVgFuNPAm0Z+Bukp1O4kFGeFTDMPuMpSS2bAeBawKvjVUNl1sG0iRj2ZoZIoHvWVFJEpA68NzawDgHbw7Ea+B3y7gdwHWF/T0l5o2gtSfrthU3sbHFSCXbAaqOQJvcGegpBPwX8maVpXtVG/p7Rj85aeQjM5u4EWNT1b6UwbzRKs5ycLcAb5KMCHTMPB5EWHoYz4/AMN87QAmeh4wJjzS7iyJohb5heY3VB2kHTxS3waILog+0RRphiMywJlZRlPtJSivugIeN0dogqNaTgU3aqZ1pppE2zgLDSOIm0uUlG1oGazWS41WIP1iVJb1VYkZVs+WUVPbKIiYRgdA7qW2B3gqnhhKHZQUIh0DTQB8GaSiF6OCLUdHM2yBI2BkZDgNCioJB0IPFISwSJcyM4t4LE00iid5SXIcQOMEStDIaOHdKaDofCM2JWQ1x/rT4qQSkRQjE432AgPkmNih9lSV6P7Fl6anoHtKbsoCICFTx4cxqsso8MoiGhsgBQQA5LKK3Z8lrq6jhSUDhToeym5uUiwVoo4qA6kEbMwi8ULOYIClSNAHzYZwskECX0I8CwBGS+HZle2SspkTHqo5DIyDFF7jvYjhegw/NVcxUERY18DxJAmC7JrzJGv0kwwBCYEkh2hEs6Yfyx3oGLPO63wROd8cCXRcSGCApXzC6iEiWeISRzlkleU5ziuy3GwyCPYxHLxUURuHvLYC9AK6WLqM4xZubCcvoYDM+KcFKDAVOqBniyiIJY5S5IqlZcR5EJa4pw2ynD6yCdCj8EDkquBchJQrotD7IkYS2pWCFQBGEc8Alr4eTaUEt6KF+VEuSTkp5lwzESDPcyOvAjjJft1YOVIRHNWOVPBcqDjg5FAYuyFmRLCOEYJss+UDPjEy/gcLzdCnCzLkUThWH7OLiv87fo5wXH2ZvLEyuXyCnclXM6h+45gvZLOR981jItYxslFMjAjdh3nwoSHAkdqMd7pWw1wMyA0KhFo5hjdws/RXNm5fCInl5vzIxZVcCaRr2DRJSgTR6EEPsJv0cuZRArnJ77OyQuIT/o0qafosWkyyjm3j62vyemFWM5faeECkIGylAsW3JFAF/DEwimiMcwxLWgR659Ak8WBr8ojXowDLSJgAcM/nnMCivZQ9AkDqxDPC7c1LTLnw2RepAJlTyQ38CE+vxzy0OhqtbQ5Dgcm8+q8q9AEIv2oY2DujiKUMIZotDDJ0IEqI5Hncwripw2MF51YXnaUuFQyrFIzPpFfFgd+ka/iFrmSAKDDozzkuP4h7/aiGeU0kJbFuS4vp19mHBLiG+1olesCOUNrokd21pql8RIS3erCWDcSR/2YhJzvAeA6WVO65h2f2t1YlANGSEYnGuAjJjPiYalsSU/Z6rvGLH1ixoqnd1nSh1VUfzsM5kDsS4c5MfWQMeQT+AVjhIeyuGTBaG4pK+RoxewoGsKBWSss77Diyj7caKKb1eFIOjfo6u4M+kX96WhI9A/4IXEiubECqAOQpotJ/Si7cDsnEdyp0BLA5bf8SkfwL8Yo8UBMlHmB6AKSF8OopKtszfGKVW55ztrOX2qrfnmjnX7HR63tvKXWHJ7BTVbR6SOfObEyGV+XFuSxiCWUjW6bjlWsdMZCW/7t99ui77zHSmctstrW/dachFPR8onDEHUN1IycT8ZPoJhDxv0RaakDecAyOvvoyWWbLmE6ZhsRIyIwxY9SsdZUQDgJyRQ1FJjFFqE7UdRMoQsKo7Dx0rQ1H56wjrestmWfeLuddNlGK7a3kbF1bVxjM597wgor5qmViD1o1GJbWyRws5ZAY1A2Ry7qPenALe/OSet4xyrrOnmJvr3nrbWxtz5iR776U6v/ZJ8VzuixwlCn06JVwgTemrgdMiu26BjThGBni1zqzqasmw1sgiRbt1Rx5yKNVSaPq4d7loJi0wefl+/O7CVobRzj6rvHrbljwjrffrqddNPbbOEVF1ips0PdtT4zG9K846TH9HFlIRea/L87ESrGaqdjNf4B1pjGMNHVaYOvusD6Ljrbxu592Ma/c5/Vf/yCFVZ3WWExKq2Krs0vnchKiXZCh9g81FZiTk4Ec+Ax6C49sXGmeb9H19B3sZxwZMiKMT9KZTjEFZQJDAIczxqHp61y67PWds4iW3n7H9n6z37Qll51mRw2/vQe2/GBT9nk7r0ktLQO5RmLL64ZP4GRj/JCLOSozzFx4BN5Tu/eZ3s+9nmbfPo5K3a229CVF9vKv/1jG/r826x4ypDVvrnPmhPY7uxBb+AABllBfNAn6AVglB7LpR2UExm26Jgvwft1dosMPSjP5pB3H5QCUR2I5WwqWI4kGMOaY7NW/dle67zmNFt+0/W2EF21PK9bHMee2m0Hb/mZjX/pAas+9Ywte/c1gru0qF5oSWqBdOb/T0uk8c4nYwzrpm661yo/ftq6r7/ABl53kfWcfrIc2XfxOTb+u4/a+Nfvsfqt+6y4aQBrkHY0W3DhSgGsZCdbIu1VHPRz61W5HPLQ8tyBwKmFQRG+BRGdIwvB9FgnQllsBGpgbhyescbDR6zj9Stt2c1/YotfdWHmuPGdz9v+795l45/5paUvVq38xoVWHl2V2RhNVl3h4mMbYjkvxjAm6JPF4NDSyVCOPI3mTJw5EttPmxZaclKXTX5hm0199Vdw5EYbfNPl1n3Kcht67cXWtwmOfBu69td/Zo1fHbLCab1W6IMja5xMI9MTOJGyaAX8Akx3ILKzRQBYEL/EYchboKtH56W1htXuPWDtV660pVuvs6WvvdTaQoubQBd98fs/tdEP3KnlS+ly1PB6rMvAuHmI+6F5cI6BL8CULef8NicCkXUs5wW6OYqjoHmoYoUFXVY8o1+T1NRXHrSpLz1kPe+9yAavvhQTzVIbev2l1nfZBhv76a/s6LcwRm4ftuKZfWog5M2a8RYYY+rHwEKNfWOMS0Ce5a4yWh5K+HEEaslU5kR0DQ7U3Ddb8a1329IrN1l7PwZkhPFnX7ADt99rh2/8MbpCxdpes5j8LMVAnVZrVugukxO+gTeJEGLuuBb2W53oPYXud6d7RThXXNFJtJDWYhrZU7EmRJj8H/fa1BcesHn/fpP1X3mhda1eZvPfdIX1XXG+jd/9kE18+R61Zu2JQrm8G+dOlE/ACw01jIHYKmcLZHDPIw4ZOQFpOtHaMMPefcgW/PerbPVbXkcMm9izz/bdfLeNfuoeazw/YW2vXmyF9rKlE9ilB0tXhJoQO8aelskEgbfkxBjFcjXK8kX8CfCIL3qyRiIEpmJOMctm6yotvmKBZt+Jm+62yX980Hreer4NvGGTda5YbPPffIXV9h+2yU//wkob8VhkuuZ6gVvWEskF7KhzEc92mGVdTfE5hlogCrwuXQUiMsQr95oLnb6WG92x0x5e/QEbvvGHlmDl3/Z6PHvBQNwYn7UUXOkFkpM2fsmrNcR24/yJ56k8JnbMIRX1CQSxJIBz1gCoLAhmZcJALKxRsWg6xUtPsqS/bEc/e5/tveKvbAozNkOhG+PgEawQ2KBAK76MlfE8sgkfp2Hv4KhogAQHan4lWhZy5ZwTmaEurFnz2mxUoIzVrfx6PLzCXQdnY902adWfUZMIgRclxF+KcRjm4C/GiDl4azYEXNgxzxjrxkDOSlKe+PygIJ1geUAgbUhSC/7xowvsJH0KR+JpmBXPGrLmSE3DjDCwvEo52ogBiUQtUnECnHXhe4GJHMiF9ARbIJ9LSJkg3CuBBBxl2KCcoWqHec7GhmUMmrphYsm7u+QhT5EUhxikUgA5hqRUtGRlpxWwFmtU6lgX4vaou00TD/2azqD70I+4h5YcOgtyyK8QYXTqFPAwNidndIAWk1UWXCale2AeOU4MtIQFXIvy2V4f6OBMBRoNXWQpLhwieHEqR0EOt9/YvcLdNyG8lYMDwRaKiNIvEnisE8kvBncKrXRoFMNK8DENsqVBpMjj2uiEzT7/oKXPn2XFjb2W4DarevtBcMJzfCtb+bKF2lWp37ofsApg7VZ+NcYv8K7e/CIYYWKyTiu9br6cXX3sKauPnJcJoG7UyyNcaQhy2VgGkC+dAK622EACJwqJ4BM6Ma8AbaYiq2UFblxN0zFnYop04W58tqiVcGCKuyRkaeEDJBUhSDUMYGyRTkXOxPBwEtZi884+1YodbTb8g3tt5mtP26KvbbbOZSdZfWrGhr/+U0xK47b4O++wtqE+q40dteHP/bMVOsq28OZ3Wqmvx6oHR2z4v9xqHa882Zbd8lHrAK0CncWhAZlYf0ojLy1guXwR8txHyQMwwtBABhoWwI6OV0tEjEaBzdQUe1cN7IZwGWM2yoQcSEkSTWIheyyoK0WMGISujFSTwvGORS2RTos10uLA+RvXRxY2+dQem5j4iS256nJrh7MYjty13eqPDNuya16ddc3DX7kTi91OW3LNq4RTn5y2g2/9qpXfcYEtvvoKwXShSI6TCFG/bCkWoXQI3UmE4GwVEQqHEswvsTyBnGgwP6K7gqSKqcgdiOnkCM0HnA01s1e56ESwEjOWk2lLEARApwaeZOUtkah0ZnhaLMqRR5+y2eER7c7M7HzRSrbUDtz5SywnFlpjcsbqL2GFgFnyxR/93Nrm96sFNrm3NzFjB36EZUY/WuCBw1Y4vd+q+w7bwR/fZx2L51v/WadTmCz3CpRw766C+0gevCKbWlugbGMLpJXEZxItOpAiwz0/bAxjKm1Ly6EFJs0jdXDB03f2Yadxue4UOhFQ8jrWfdF5KAp6AwKBrU5UgWjzvnLwjl/YoQ//b2uzdVbc0G3F3xm0A2/9J/DnqY0ylhlDlnQXbd81XwZlFbA2K716yBpYz+276h+AV7dCb4eVLhqw2q5D9vxr/9KGPvlv5MBoNwiDTkqBhk0TVlA/BxHDWyuNC0EtMPhBIND4mK6Y7ZDk1aliDZuNnESa6SifMOFMCBohsNF3yS+fCCgGeRaRoiUQImgUgrKsu1AJcXL6FjKMYd3W1r3e2q5cbM0jM7pjKV4Jp2Fml/MxM7Nrla7Cei1OblwMI116AyYYzrxcjszUsRnQZuU1q6wInlmgbOoEgHTGJe8h0hiAUJjXq5OH7u+URAq82BLxxwkXE3WlWOHyAw7E04Ox2UbNSkUu4LR4EJUUIBEUoTApIhYkOz5kCrOG6WzFAY/5wIEQ3mY1p6rWrGBpgrQqi10US1S3zOlSOE1V7sJlcxMwsAY3b0mUmz7nfJzKDWZaqusSuyG1CC1QyMiryzolS/WwjTFl6gJ8eiS4gboiVNonuuTAQqXanADedLmonWSgBW1FH9JzIs/wKoFIMGbQFcxaYxmo0lbOTOejdVSWxghfADJ0voZ76QQPi1hGmM+UlMM8PmyNQYYAZB0AjESXsXPcQJ1RKUFktsBA64XAFMgp0EdYXjl5wVp3YDPtwFm+dLJcxOKWfViScw4kY8jgeZHzZ7k+Ac+RI1XAIUpOGNOMPY0y3M04aeDDloGumqJlVm/ba7UHsVjg8w/qx4dIgTPjyC+AMl3FPXjS9acdkiKdlZrjfIDRCcQTiJEmIhOk3oIxMNn6FnYXK2DnZxoUY21ogRoEQZ0JibIc4IwJC0EKIp3p1IJHJsxSiVyRSEkaFoY8N2Zx98GHTAKDhs86GnuOWscFK+20Bz5i/R+8DLddOMeJh0Qpxkg+7XPyyCTGrpByARTl57GLVr5lDBQ6K46KOxvXn2nagZgdGF/cCyokhVfdswVa2REeMMKADbxArMjTRA1QJzvu6syFF+mPwckxUABm5CdZ6JqNFyehQsHq2KDFHrmXo/U190xZ/+Xn2PxXnGULr9pkjUcmrLEfZy2xh944OOXdmt1evFyg0sEJc+BBLwh1xGgRcUOaBTEn3TJUT7D9cwTFMKgZmJLVbzCmjOrEabEoBwaVgqzAEoIjv6AB8vjL4Hm5hFMZloEop/NUvBZ6261y1x4b+P1Nds73t1j/f9xk9Z24xUTr4w1/4ex+G7rAF92HfrINo+aU9V7/Clv33T+3vrdfZJUfvYBnzm3gj2bEphFDlEnhlO4CM13n6NXSAh0x0IiX689ktENdGAtpwv5iy19gF4GFOGUkB4bbOcF4geSog7LMe2LuNdMxL49OlFJg4iXRSnTRgU6b/d4+G/zY6+z0911vnQuHrG/DmdbYd9Sf7j1x1HquOcu6ly2y2ZExO3rn4/BRh/Wec6pw1/wHrPv+86us+uP92DDtcAuDVpIddHLDMwXlxEx56iUDHULbsi9JmKHmIWYuWCAHfhz5OHIPs2kWC0X2YeKJk6fcdGcdCoQg1nKMMEAXBeUUniKfPIUMJqzKkcds4GObbN1H34V74nZ7aduj9vyfflkbCdzJbo5O29Brzpekke07rHrHASu/bontvfFrNvzAY6I57SM3WO+NaIk7d6Lr57sx1EPypFCUjDiYxgTtjNlgjqIcyhT+hOQxadQC8Rwp0ngLtGSYgCLWgtzrIhGJwwclyikmHoMLd5w5eF7g5UxLgwxbtI3pWev//Wtt7Ydu0O3c8MNP2DNX/S22r+AEbEtxU7Z8xRIbwgNyhtGfPYIyqEon4TT1s1f/nY2Ahg/qT/vg71nve6/E82C+mRHDXHnUIULctoiXW5ZDqHLEJxRpEWsFyWUpW6EcuHXHDu/CzWbjMPa3sKqO6wRnoCuIA31QIogKcJZleAExCvQyp3eOTsv73dU3vtVKaHmT+w7aExs/gRcKcF5mfhccWLDatmEb2HyhtfX26LHB5D89ilu+Ph3VKAxiH/GUTtu58b/ZFGjZepf90bXWnM0ahQyWKtStJeFJXPmhk/iV/q6Xp3nNg+eI63awBEnfVUZaLRDLv8N87wPjIF7b4H0EsTJSUcwVJQQizcXLyFygyiMq4xAK2Mbaf9vPlevBGHfyre+2xqNjLU5IbcHlG1U++tDjVts9ols2imtW61a/f8SW3XaDxkciHfrn+7NdGxFlszC1jrqgJHOY2yZcMp0TSEFU0nlZhoG8ZmEst0myGX9yYCNNRvDOA3oI1xAMkUlrzqEZMy/SVXJQkAkUkvMg1bGUxd4u2/eRm+zpL31f9CvfeIWt/O57rP7zUau/MGHdf3CO9Z+22hp4ojdy+6+suLpfu9aGtz5qdx+0Zd9/ly17wytFu/srN9uhD37Wij2drgulURfmdAnSQ5owJvUFYgQTnYTKy6AcR0UtmHDi3BaIyeMIDgvW2nBnjDVO9AM5ShnSSiA5zQlRfK5ITEkH0gXaVjLe/3bYJbbvhm/Aid9T0arr/pWt/N4NNvPkNpv/xoutgKeAPNkw+WV039PgQGx41O48bMu3/oGtePPviObZL/3ADr7z29a2dJ3uqTMZQbjr7DpSL/dLVMrhbplT5piyHMAAcULl/FY43wRTC8T21jhwprWYlgNJmLnCU0GpoIUkRoHijHJRANhKmSkhJFeUsCbWoh3XrrIXbvis7frGrXJAZeQINrNOtaEN64R46J4HEbuK2LdEGi1wHC8w4czfnm/+0Pbf8EVru24FTj9gXRuMJGHckpJsV5Jg6UU0glq/KgyXDD0gZLa08ndyUXBLH7eYZaxe06O4H+7jg3PdrMPV8CX+GJ9YIEudL6UBC1H2MDpQSmEhZaoRDV/syExXrX3TGtv359+1I/f+xsY/d7cNffhqm4fntBVs44/+4zYrXbxAOzdcPhQ39dlLH73VJu5/0ir3v2BtV6zC81s+Hcx5K6m7C8gAWLor4XYEJd2iY/QCUHCNf57x7TUwcR8EOS0CVb0je3l/ZOP+omHow8AV/0w9EgcGgXmMHBrKEEWsFjmCRXhEYFemjMLKbpv65bN4xjdki994mdgOP/Qbq27b73cavOGnU6BtYV2vzf7yORxT6/RdGIDJl98saEPAodl45MYEPNfsWLo5eeBnjgzpjH9LQg7UK6rYUKADsS8IXaM6ZAJsMmDUQsgkoSpBgZcFDOE7MFMiYEQWgVLdES+m6SxLsrLDJna9YFMHhu0wjloUMNnwLI43blCQPfKFJd2Ao0urW7smka/isCUVtHEdURCdGeFOIwsCeaZVrm2wXQhzCQXiQyWOi3TaEd7OJVhMq7axZqXCKgSqby7nwpxXvHLxww5PfF3lUa462fS9AhxXWV5aAlsin/sWlnba3t/7iu3v/K4Vz8Wp0vW92q2mEtqpdgmAYTfGOcs5OWdnyi0pBRRQ4+xxJmjkRBnFwuiwgB/JyFC1FWwSHtNBUhQOtIJt/raP0tiR4XY1X57zVuPIIgqCMgZRkOS04EW5URDpUEwMxwqEyh9LB1x007bXLLMCnpNEWcKS/EgLiAMjoIUbQSwPX6Vz9MjTndNC7gx1jTgUIT+QlVDzKyrTfQZ4gW+EsxxAPd4s4nZJXZiEwXonFRdcWnM5U5ZmwgWOeC1xTGYqOSCCSd88ymMX3nQlP0oMTqRKDK4aKTKpDmcZGrTQMsYBB/kc21MxnxGTntSRNiSU5cWL0D89tL5O7w7ki7zACrghBYgI54hTGfFYmBvrlG6oSlXmKRfqGJhA0OKcLsScLMiLpwU4abCc3ZtxlBNgGmacEUqix5y/rIzauSKuo3gwKW7IxTjSEQKYPkgFPMXUSxSKtXox22qltskRDVMYNnRCAYvqIIEjGDl53/fRIBeUpQJjMqGgsOWtEYoCczrmPPi7uTjP0omjcDzzAscVkE64rU80PkxCzNck/KkcMnrAhG1X4rGO6UjSsv+04cSYzuo4f7IQPRJM6+Y0jHvxSAfLZZ4wIh2BTuMQ8sltElMUYJRTC9yKdPAkB0Mb4ws3fDoXeIuHFEDKYS5ABYJ5rbAUYtxpmcAweIPEnZjT1o5O4TWfbWY/vASnQnFyfrDDqj8fBg+8JAOVShvny5m1uw9ACp4BY3lduni+ZuDqfdw4wqyN8zKlSweNT+6q1WesPnFZVEuaMUOJmnzg7+OdyNJcJ+IzyCLY4K0ONrEZBTQMbfIN0HTGb/O6dWnmwGZan+BvGYQ3rkVFQj1PZYxvdJcktVyEp9IoMNYa3RpDnhrcsNYKf/OXOlM9etcjVrlzry34xGusfeGgNWYqduS2B3GSvmKL/u5NeGWhwxo4LzO6dZsVF3Tb/M+8Umdqakcm7Mg/3GftGxfbor/5Q+tbv8YF0WCmgtWqWvYiwOc4MWjG8uigqKnolWEZbYoQ5vFtugOJkjkQVe4OVP+IPAMDICIVWCpSjrBWOFuaC6T+uRNdQc1VIl712svN+EV4FO91vPCtW+yMd3/GOhcMCLbt8T02+8xBW/++dyhPYT+/+UFrWznf1v7x9YKxFd/7n7Za/7+90Na9/52Ohyt+1SDXCnTeAkNvaHUiKVDuVmXkolURC0gPBrRJQfgEovkzbPl4Wqr2DBHVis3GVL1Z5K40EeQAwuUUXMlCzhI2S4LwwJQYLDrOicInJXccPYzt2WvVo5NWKJVtZu8h1OLJdujhx613zXKrTkxafXQSPbdpL+FupA0nsSo4Dmd4IZzw4UeeQMvtwl7gS+jGfVYdHrPDgLUN9FrvycuC3lGS6+y6HeNEqUK8VlzHl50B3toCMeyGvT7shYSQtcA0Lc6gjze4J8gyMpnjlEiRCXThEo+L7oFFF9RV048KMebq1pXd/e07bO+ffco65p+L1xFwNOOiZfb01X+Puwueg+EY2KtJ4TcXYKMVdIQVL+y1KvYFf7PhJsAw1Ay0WfGSQZt5bK/9esMf2qK/eoet/9C7ICKaT/09tPYGX1SrjajQNQqILVGEZw1IADQDdqfQAmFpWprhL/kg4LDHbFfSid9hSfzMOaFBAyWlmCsX5YgQTpGz4TDhscmDMAoWEAStlAW8QVSyVVY6d0BHg3m7Vtgwz2dX4mJWpujiJX3QgWoiwyUONsy5ocCZnny5K5OUcRjJFmZnt10n4CPENHkd70TIEELEEon01JCjS7AJKMTiJMKzqch0fHvz5uJbtm5tFGz7dlG2JwX++E2ddyP0HA3WgElGYka0Y4XhTHEARQd5PuRCIfm8bIhFiIXGPNOSz7TzElrGL3ATrkrmaOa0uAaGjhH4iz0g+rAEDgkh1zPIjPLEnbjeAuGhjguG1/E0tRU2zlvCEownaRX4DdUuMAItiwK5MxWAFzi6YHj3F88w1FyIFxUWx4ivDHh4TFLi8YiaFslBkHZm0KLYqoQLdIchBxi1IAeluYvDL/+Ix+EhZ08RWdbZOy2h0UmaF3gajPMB20wI4hkziDN8wtBo+bs4ENU1UprRRFK4hwUItZkU29RpI7RA0LlQXVuUiwy53T5td1htB16khgJa9PKFGh72Ji0EUaJfKaGFSZbz8qwsyCRqlBs5tDoi6kCuuYycf07LYuSoCxlgoc43SvngnqFxcBLbuk9kbx6QlwJxSec5JJlW69MBc1jbOdhV1ESSrS3qHfgtDziYo1fggshZODkbe01vQLJ8/ulrbMPW223e5vU4jjtuM/fvstr9WAyjZfDdXJ464EimFtOijPPmFVzJPisL6sY8spQbPiJzjHANeK0wIYWLnMxWysrlGwDUh48FnhzDw/gD1nhuyjouXmWrv/dJm3fKSlFxPOWkxd4lvpLhEgRAnmtlFLc3CoUeEqE6PHRVwb4DGMF/SGXKE0THFK3fxnfssZnRMesc7Le1//oqfUc+9JwdfPAxe+nu7Tbxf7bjfmIY9w6LrLwJdxR8iQ8MfBZ2WXKMJ6UXB3MZ6jlkgAEtHc7BHgYhE2dQclNFS0nmqGBgiASXTGptuO0zHESq7ThizRfHrTTQZ13Xn2kDOG8zuHGt9a1ZEYnwoH/Cpp/EO8WrsIXGA54IZJnrptESXbiJTlZqw0w714GiOObiOlEheACnQUvn9duRv3/I7nrqQ7bousts8SvOtpPWnWZDp+B1UnzP3PwGG3n/HqzfHreXfrTNxr/xAGinreOsUzFedqtmowhy5R+DJLgHlXOPA/oyTvQKCbShpj0HctIsbNfJ1+pPcXYGbaTnhrNt8DV4YxN3QHRaIZxiqOOuZ+zJXXZk+5M2/qOHrf4Uzm2vnqd7bO0IZRXpuqhicUC/DeehcSwaS4SWFjjdlhS6OC9IE178S/20GqfWs3h2fN48qzzyku2663/aHvySXM+bcXLqta+wJZs22ElnnGILwvfMza+3kQ8/bwfuf8QO3b7NJn7zDWvWQ82CJ7kzyHngzTg0Q0rykBnAotgCHQ9+yoJoA8cmlkSzL+3Am5hX2qI/fQNOdq2H01ZasY3dE60IL9iMPr7TRnA8ZPzuR232G3sAxdB0br8V+ZhAb7Kz9UMOhUQdXENksWLG3Q7WM4PkV7qCV4Syfi8kKXKh6BOAw2UiWoecSIY48Fg8pddK5QG95DJ953O26wcP27Pwfe91G2zxmy61pRefZ4OrV6J1nqpv499da/sfvN46BvqdqYyHHOgov+HiuzjuJPUbYbYYIL/l5X575a5zVDG1jsE+O/f+L9gCHAuJv9HA4Wds1/N2GE4bvf1Bm/3mTgkurp+Hw+uDOCaHkYyzPxoIa4+cqNocJxIKhfkLbSXeLiZNvPnT0gLhozaU480lLBWRcOeTjQcaG1siX9pj4PZT8bQeOBOtGQhTOKr25PfutWfQXQduuAzvflxsC89bZwOrV9jyTX5QiHR8FZ8TknSi8/DHQT86kS3RW5jMEG9XiELpeK9QWQkQx1eedmCYt2KJvuQ3vvsFG/n1Uzbyk4ds8rOPohS/2XDmfDgNtmNLTAfVOdHAHo51lCHnZbpQnAwna4mjf7TUM9ObPaXtp+1P7B404mq9s72jja9+oQViOYgTVHlwQ5wXa90NZM3qDgGtkgoUV3dbuedsbTuNf3G7jXzxh/YU3gEZfB8c+coNtuTCc3E6v8uOPvEcJqQ+zNC+foM/pDgrwT3nTiKQBjFkDhZKdCLgeD5SGJxnU5gAqnhmXJ2ctEMPPm6jv3jUjv6vX2N3Z8RK8wbxqhhO/HOJhbHcD6qTuXNXY5HzWvhCF69QoNF8ug8w/sIT1cS7hYsILXUe8R94LZVKGOUxPWOWIVK2rwqge5xc2FKYbxEkKHhzkxPjR2MY77uhZZYvWYh9Tvw+DF5jGPn0vTb86dts19o1Vl6BDYBHh620AbdxbMlUHEw5YTBQWXdoTFAuQ0srlQ4ySUNK4fR5dvSOJ+2B3R/Hz61MWfVXe1FB6J6X9Fu5d0hP8LT5OoWHUXoZwWUdVymQodE49ICs3JuMtMBvjKGH6oZuMQElP0BGOxp9JdxW1HBGhgitAeaJtat8rBNDqZwAPjheQ0gTP4YD63SmuW0T3mA3vBNyeNYqjx/ywRr3tgyqfcaZE6PjACOnYEwuO7QM4DstjMb4lQy1W3UXDiFhodz+6lUoAzV6RmMUL+8QkV0Wq15KdVnkT1siP+TZMByayVU5YDHwR9r4YhLYuQN3hS19/IzbfB7tgANB48YphnBvFc46NyQIlIHRiSgFshTTHZ4bwde0tM3YjYPseF3VF9ekbzEgM0zUZJS1RE0YsAEQYp3YaAwn3Nlm4Cu4fKENAiQ3dxptga7H2CQnSReSnMCJkgvGYMTXDPVbi2mycOdVf9JeOCXsB2IFs7iMzf5qvY4GSCHCJwU/ThwZhdj9HMoBIxovIZXH5EU+eBiu31EQYgteEOD0Tq2reGVMmUBw4rySA5S4WMLogTtlhUaT4YnUecumwCpApF9AQZRB3XZCgi5N9Bz9BHSSLmj29M4vbB/Y7xol6UrWfaXGPYVQ2a2MjhGYG+IF8kHElzBnK1WUD3iKoiEtqjq6u8eZObdAS4oAJgeFzDkqiOUxbuUddQEZcJXL4hPgOYLjSS4BzgOHURMeBcQr6r1t1cKywm1LlmAqZNNN1nDsq1Qq/A1pyImKtAgMfAIkYyr9JYicIn6WcghoXYVYHuNj8AJXyY/cXIDnxMQ5ASA9PdY1OBm8A0qQkuMFZGdzAh0CYWYT8RGyPBL4udlmF3bT8TvJqwtbtmxp3n3FFp6sPLUCz07OzGAGxkobADqS4xTTaJNk44wgPdY+YSpxjXJBju7Oc0qhBmynCsoyI1MCj0BKIcKL4Iw2AoiIEHXJjRQ06CKxc/G8ONMhsgvuPI6fiHmRI7BKq+PHtvXoIzlDmwkrB2tLk6R9+URlBo8Iq9aoN9JG+HEJPKRJ6FC+kM2tLs1o4hUc657NZOQJqgWvh4hwKhg3BDghcLqRleQLPE5AHLw4kIcaU7kvcY6hPQaPTvRJiaQ5n7jodo4tE5B0oTjIQzqTh1RrYKXIsVyZYL+KOzr1Bt5vRR6Ua3w3Ji2/cmFnT9/hZMouOHNdebZWs9lapTlTraSVSjWtVKv4/Zya1Wu1pFGv8yQ/64KWwr2IYkslCGmN4I4BSB4y5xMkxZVwHGeYI3sREXMeGTMh57iCh0IVhXSOIT4xG92lmK0clSEnCYFQr1pYl6LxNNl4cHo3LZWx0MOrDOVyGS+laZlxpRyIH/U9un9m4j6oOtiO1W9Xe0dvZ3GooHs+MOPimgPnbB2OrVdtBq20Wq81arVas1KvpUjipgKHv+Fc4BYwU+GEF6rL2xRdiQDuwTgHMO/OcceG8oh9bCx6GhdcGnjRWHqYMmS2MJCP9CJgqeNICaS1JKSD8HobfkSHTkp5tA8bLXzdo1DGKwv4FjrwrwfaMd6Fdwk1A0/Vq9Uj1end4LoNjT2uiqAAxsJdg7YIr+2uSArNVaiY1cW0sAq6LIfgJYhPQhfsB8NSO15OpIOpP5szf4e1ikePVbx7zLGUDq/V61jyIWDQxbABn/LnluuqEL8lgqPRAtiiEbN/8ePWSi85JbjCXcCM3I4YrV8eZUthKZ3BNHH4My7sDdg5gZMw/NAxPgzhLrWId7sTnKMq4QfoSnIOY66DicPWWIOu02gs2EDFlru9CNizELEDpv4a/+bgsZPPsmcSzB9SNt2ypcCXRviUiYqcKOCfFrThVbXBQrmxoJgmiyAL94Ap/m1EcQnSi2AvbjZtPowbhAH4Ua2kuwMK8rhcCRL9UQE400mI6PTw2626deROL7+8F49xcK7UcSomQ6tlCoLIF87KYj5SpBO45eRlXi4muFA2f8KYazn2KNQXjzcfARhnRtIDWAPvA+fnkX8OrzQ+jwawb83CFQeTE/ybjoc2vof/LSIPdOT2W/cX+Q9QeOiID93X2tpGfDc2xzxxigyL87q68Ur/vM562ocHLP2lUtKPH80cwE/cDkAY9rOK/bgdnQdDepDHs8wEb9fg6RT+RQXiTtjP24kOtMcy2hM28fBbQvAB/IrmHgNKsEcOHthgTLCtk/KgNO8dZ1DA33PBK7wpjy1PQsZRVBScZGOgGQXeKO4T8G2MFIrlUYxDR9JCbeKMW/6aOC8bUIGJvefzpV17Hy+csnx905YcaLAF/l/6jCmtrZDEiQAAAABJRU5ErkJggg=="
          ]
         }
        ],
        "meta": {},
        "name": "icon"
       }
      }
     ]
    },
    {
     "title": "🔴API-Gateway💜: Last ${limit} Requests🆕🔽 (Filter by 🔴🟠Target Request Id: ${api_gtwy_request_id})",
     "type": "logs",
     "description": "Include sensitive data💥\nNewest first",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expression": "filter status<=399\n| fields @timestamp, @message, @xrayTraceId, requestId, ip, apiKey, requestTime, httpMethod, routeKey, path, status, protocol, integrationStatus, integrationLatency, responseLatency, responseLength\n| parse @message \"(*) *\" as @requestId, restOfMessage\n| parse restOfMessage \"Method completed with status: *\" as @status\n| parse restOfMessage \"Received response. Status: *, Integration latency: * ms\" as responseStatus, jsonIntegrationLatency\n| parse restOfMessage \"X-ray Tracing ID : Root=*\" as @xrayTraceId\n| filter requestId like /${api_gtwy_request_id}/\n| sort @timestamp desc\n| limit ${limit}",
       "logGroups": [
        { "arn": "$api_gtwy_log_group", "name": "$api_gtwy_log_group" }
       ],
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "🔴API-Gateway🐉: Last ${limit} 4-500 Errors🚨",
     "type": "logs",
     "description": "Returns the last ${limit} 4-500 errors in your API Gateway access log group.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expression": "filter status>=400 and status<=599\n| fields @timestamp, @message, @xrayTraceId, requestId, ip, apiKey, requestTime, httpMethod, routeKey, path, status, protocol, integrationStatus, integrationLatency, responseLatency, responseLength\n| parse @message \"(*) *\" as @requestId, restOfMessage\n| parse restOfMessage \"Method completed with status: *\" as @status\n| parse restOfMessage \"Received response. Status: *, Integration latency: * ms\" as responseStatus, jsonIntegrationLatency\n| parse restOfMessage \"X-ray Tracing ID : Root=*\" as @xrayTraceId\n| sort @timestamp desc\n| limit 25",
       "logGroups": [
        { "arn": "$api_gtwy_log_group", "name": "$api_gtwy_log_group" }
       ],
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "📑Logs: 🟠Lambda",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "volkovlabs-image-panel",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "Lambda",
          "type": "string",
          "values": [
           "iVBORw0KGgoAAAANSUhEUgAAAEsAAABLCAYAAAA4TnrqAAABYWlDQ1BrQ0dDb2xvclNwYWNlRGlzcGxheVAzAAAokWNgYFJJLCjIYWFgYMjNKykKcndSiIiMUmB/yMAOhLwMYgwKicnFBY4BAT5AJQwwGhV8u8bACKIv64LMOiU1tUm1XsDXYqbw1YuvRJsw1aMArpTU4mQg/QeIU5MLikoYGBhTgGzl8pICELsDyBYpAjoKyJ4DYqdD2BtA7CQI+whYTUiQM5B9A8hWSM5IBJrB+API1klCEk9HYkPtBQFul8zigpzESoUAYwKuJQOUpFaUgGjn/ILKosz0jBIFR2AopSp45iXr6SgYGRiaMzCAwhyi+nMgOCwZxc4gxJrvMzDY7v////9uhJjXfgaGjUCdXDsRYhoWDAyC3AwMJ3YWJBYlgoWYgZgpLY2B4dNyBgbeSAYG4QtAPdHFacZGYHlGHicGBtZ7//9/VmNgYJ/MwPB3wv//vxf9//93MVDzHQaGA3kAFSFl7jXH0fsAAABsZVhJZk1NACoAAAAIAAQBEgADAAAAAQABAAABGgAFAAAAAQAAAD4BGwAFAAAAAQAAAEaHaQAEAAAAAQAAAE4AAAAAAAAASAAAAAEAAABIAAAAAQACoAIABAAAAAEAAABLoAMABAAAAAEAAABLAAAAAAIHqMMAAAAJcEhZcwAACxMAAAsTAQCanBgAAAJmaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyI+CiAgICAgICAgIDx0aWZmOlhSZXNvbHV0aW9uPjcyPC90aWZmOlhSZXNvbHV0aW9uPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICAgICA8dGlmZjpZUmVzb2x1dGlvbj43MjwvdGlmZjpZUmVzb2x1dGlvbj4KICAgICAgICAgPGV4aWY6UGl4ZWxZRGltZW5zaW9uPjMyNTwvZXhpZjpQaXhlbFlEaW1lbnNpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj4zMjg8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KI5mc/AAAJpRJREFUeAG9nAm0Xld13/e93/cmPb1Z0rMkWx6wsZHxKHmWbckDJkALYWhaoE1pSiirwCoFVpIm1AIWIQZSykrbFFaZQ9owhZRFm0DwIM/zKNmysS3bssan9/Tm4Rtuf/99zrnve5IcGy9Wj3TvmfZ89jln33Pv+7KtWy3nalpM923dsGxNV3FiM89O4TqpUti6wrLhLC8GM8v6i6LZa1nWDXhnZtZWmOVWFGRZPcuyBYpzwE0XVkxnmU0WTZvMcjsMzFizsEOVLDtYNxspiuxgs8hGiurC2Mkffehw4v8P5cX33lWxsWfyHXthQVq/urOwvT2FrV9ZfGrH94vrt1pBB7K8uoQWmX3/XXnicebW7QuJkvqc6Z4vnr+hyLJ/SsdZKH0Gyg63Va2zrZpbRdwj+yaFRsNMOYp7u7pExC9uec4F2UoOFTWqj1w0dAm31vBLAzTLNU7/GJWDWdP2oe0eSLzQtOJFyyu726zYP1HJR077yN0TovVKUoEDfH/7u7J3vcvs5h0Hs80R6eYWZLWpvhlDG4bOWhyG5jLt/uKG30a+49Z+7P4bXJ3df7rx/rWDHecfmlhwhRZqKFOXYfAP/kvBTEUpnGyQDCEzhf/BYrDBTrKhG5Cb/rkBVZLhZEw3KoAVLIO3UadMn2CV6vBeQIZ6s5ijOs41wrUPwnuzotgNkRcza77YzKr7ijwbySrF6GxzdOq0j/xyHrhXlZ644bKerraFdW3NxrlFlm+ByOXDvW2v3T9Re2Ltx+57Xbb7houOz9saO/GYZZMT9ToTsiKruIbSjP/osdRIobnFc2hQiu2ylFDdZOTJeIsI0SbqE2nBKpG7NT136ExGxMHdU6uUJYuMLR5u0EZTRmVm2xSkmM7ZGCCHGVtNbYyc0W4z1GXEGnWcuMjzIm/He7sh1UffKpxhNbzXoPrqnq6KD+B0rQHvzGYXGrtGmrXXV7O8eUZ3R2XZocO1er1WVKsMbyaJSBkUuCedQ5vuobnM3bjSmHYtGgFb+I4i73QbuNvSGMl6Lk+Vxzqs8BNtUNWGVxd1pj6yqEfklQd4tUrxPKviof2VLO9n+p8kb5VBhS8REm3hleTVQdJyoqvBDS+2GtdsUTSwprUtqxSNuWYVpBUDzUpfFT86o6OaWb1esJ7H+QOyaAXCqtAeslIZKeyGCUC0R4u0tLcaLuGLgFzpaPyoVOQadZEQAJMtknflxVbt6oRPoRWjIagGWwcFdUsU5Sm50bziiEJnWQwNOEiWYe22DGdmqQ6tWC0wXg7gYBWhX6OOJqNHexh16skQIVfHosFcCvGTNDEX51+bwVwQETySvovhcoqfnC3aMkMOBIz9yC9XjhPEjSsdHQc8Ly5arjQ+6K6TNjF1s4tDNWt0tGHGejGUM4FP0NxvNqS2y6csCLokFymaQ3aMfu92gwXAUHeFY1EZ486dyxVVg/+PN28WmNNxVi/RX+JRSHDepopwoN9kSoU8TjeUbcZL0y6VlbtekZckVN0lzYqmz7yiWKG1c1hrAgjB1gnBMUAiX/QgUXglHtZwRkB7KvFjPXhDYORTknbBCs7tqIxhDY0IINAoR7RzELZsxyjIJZFLWJWVWhBTvwC9DHBYTAXHpcZIk1I0WMZmC+2iWFmF1soaOwqWdPxAJAK2IJcKu8lf2mAilFd72L46IAjnpIS4Qy/R92qqpPYyp9BgE2vOQ4G5AI2kRGnQQLql/QiDiZ2joZgMBoElBg3iqLU0WFRNojldzxkz0eE2xNJu/Szu6lQTWVSIWomsbuovbzAA83ZrzD5rxcKLmvOBkfMSdZLohNKSchAodKg/X3aeZRj812UwKaDBW2KwpNORBoO/7BBuQQdUGazS2BPmL2RYESWoAJNCr9xgMhTx9sJ+qw6cZ5XetxHZTGCwsLGItxvEC4v0YzU2aJSBB6cx9pA1a+DjpRnhUZADqWCTBk5CtsoXhD/CICVf2n8FgzltCUcSD5b1/irlLi1wJLePM6fiBosWaxUoCRpyoLCA74J5FeUmrbL8FDv+X/536xhc431O+VXcJrbfaqM/ugrDrMdgPIoSUwY5Xtpg6pcWvksiV1CoVRcAJDjavRIPcyNAjr1AtHo1DT3cc0GiVZyn6AbeDhm7vPEog4l9RuxW22eV7g3WMbTGCh4Gpl/YyVTSeIjSYnIlFquxFJVo1Kzr+NOt98zLberR37P5xz5rRd8VkFhwz9TAqLC4JIAO6tHyYRA63JuTLoKTLCKhUqtB6XOatGuNdGmAi5CC75EmZVKfW05dCTnmwj5aINpEVQzUaRisyRMF9bmDz9tznz3LKoNUg+e6ALq5AsrpCreQZW24+wEW0Xd81Va94f3Wu+E37cB2jFVnOlY64S+DgQUvVxSWSU7ROUo+GQQA5yfYxC7Bqh/Esp/2ZDBJRFU01aTqMjeWRssZJYLeLdtH5EhE2EcJ5JRELQhTxlGsOzJU3nMlHTOgAijuJBdDZdENDUhE7NLWD8J2m3noa1a76G22/LQNdvjkD9rCc3+Ox17qCIv8X6XBEk+oBVpHGFT9UXE3JHCahqRlLPIxhQaviIhTUqYWbin3qlda2lVUGwq3Jq/q5g8iPIN49KeHEj0uhOCO8zGkIXQRem3U8u6zrbbvbpt4+EYn1Xvxe/zxN3hsENd5qZdCkivlsdlxS7kpeL93Olro5x4G94j+Es7bWbPALqwrGsvHNygcyQTlA4skSMqdVugSkRKPmDhiJyLq5l9gRqPKjh3aIrKLRId7ODtfvrzXJu/7mtWnx613/aXWtu69Vsw9DjTiRr6Bjkg6trdH0s58sT+iJLjAPsqRZEH/I/udSur3SlswlmBjZ8mEupdjQxIk5U4mIXlFCIt0UlNY1MKUTkwSDzdiBAykOHRdGGPqXmK13T+3ice20ZtZ7yXvs+asTlp0ALDIJNEpFU1dgdiiQcr2aNjEM8JJavcwCLY0Jf19N0QMN1Zao0vipRAQ9XJscEIlY3GM/cq91lJQg2agTzeOm5p1yiFnxaYcvPAog0lgIvesu8sm7/mWNeZnrff1m6y69q3Epy9CVAZb5FPKKrzYnnKveiXAh3YZRj0k8rJMpdVgAba1n9MIRm4+Pp0nWkcQiQiRakkkMvNMjVyl4mpki8m6ui3vWGFZ53Fcqy3rSNdaYqeBEr7EEw2CUveu3itt/tkf2uSO29kJ2/Gu37Xm5C42gGUALZ7BiFWpMIWXlM8BgVUuw3juxUV8tatDt5JoAKSaEcEXcxyedaovboJOSGXh+bYa8cOOduxdMpCkz5mQc+az8Py0VVf8b/cw9fvKqImPU0nnvPsS4GbhEfDKZ0Agswbt3W02fve3rO/sK7k22/i2q6w5s4ddk3cmMhgES5klvxjA/xWFFYITH8eJukYh3Ra0S/9wE+2CU8DMZnTKWMqbEMh/FYOJgaaWHlcKAksFo914Q6VrBR3sfClRzju6rT72tNUP3GJZ+zB4nFJIOIi4wTh7a9bGrNKzxeaf/AubeOID1nfmJrzrQ0T1b7fq8NXsnCOIzuMVQr5qg2EJN5hkk/zIsISWGrGS26HI6hz+ZdM6hg3gjrOIQKMDKtcIkNzqgYjuCBxxvFNex2hV2qxr1To79d9+Ra3HTAvjI/bC1z9o9ZE7fXouNZhQWOzlXV0cpN/xnWCsc66y8Vsv4MmHyLW6DK9kUPh3lJIu1K/gYSjn6iWDlRLT6vZy/WuVj1235n1tlXz1+DiP0wVHNwEt3J1CMIjwk8G83NLgOHhVXu3zaZL3na7DRFsYP2QLE2NWmxglP2S1ycO2MHrAp2jHwCorqoQI9xBw8jyp0wVxSjz8PKs5Z3nXmVZ77gfWfvJbrGv1Kbxx6iZoBafv9byx4O0Ynuxickt5i2gudGpP+dL+hJc0V29sC6WiPbd8od7co61l0t/xYUNeepbCutdE10llz53jMTwMY/H6CKUz2/udawM3zT7gkwE4vbEG71w6T3+rvebffc8Gzt1so7+42ppTz7IOEe6bAtYA71MS5AKDZZ28rrn9L6zntRut79xrbeLWk605tz88YNMvvj4DxCvJHOmI4Ctew47lYQjiA8dypQk4Faeh21G8JKjcT+VwWyyrKyUvxwZNv6BpO4v3OSi4nuDy9XjNmSzkXJSt/XXWdsIWm9v5Nza+4y5OdDqt/4oPW330GaZVL4bWG61AxnMFoXUelZZvstntX7bpZx+xtr6VtvyiP7L6oYcwFo9HWg9bZF0ic5IVGVN7ylv5LOIDV+JIEEHx+kiDwFt2Xvjwel1Dz3+HdADtTqpHeG9bLJcEA0jAaynrBCKraLvrYFRZdHJcQ5dcRNO1z2z0lm86xsB5V1nb6gvxlL2crgIbiYdMSmoQMCJPsWO3/y9wzPrOu84q/V3g7ANnudMUnot5pMxR9pfvh4xTD3RUTlecGVMcLxcTshwRlztUQol4XnUigdKiQLGuhtAfGvxO2FDIS/yVEQGoctUxVHPhEAeDV9nM9m/Y4R33WLWrx/qu+Jg1Rh7HIP0IITiNHFkgifMs4J0bbebRz9nM7p3WsWKtdW/8PB75IDh9wMX5/goMlvQKMnut5LNEFwH4xUIuv8psAj/PJxSa+gAm4aKUsepIXk794kE5KbOESeQRQZSRgodkmmp5F44y43HWoW3f8d7B866xyqr1PNLIu5ZDV6G/d0Ue4OsElTR2x/c97zv/N3gsYgyid6UnAiEkWVMuhCSrPCK1p7y1X53enu5U5EygjWsasqXIsxanniNE6olJSSRQCqQoH90fAFJ7cFeNRsXqk7dhqCkcDE/pucxmH/2vNvHUg9bWO2h9m36PMOLRuA7hjT56kowkkhgwY2eceeSTNrv3GXbG19iyc25gw3gQHKxGfzhBEOzLGWRRCS+lasxd19jhmRy9KEZz3vzro4uwY9GT4NUW56V4h47UH4E8U1usO5OAqHtsZxBQvKgfZpZtZlS0JeqImKlD8dC2v3TYwfOvterQ8cG7kvJOJLD2hZx2RRhjd//Ycfo2vEWOShtxV0VHz6/cYEm3RZmd5KIuVKWXdledZ7HJH8qbWWNcumrXdAJUVA83IXgtVb19SX+EPabBZBDWlMbEA9a+ZrOd8uH/aSvf9Bk8bDsGk3ddYtMPf9Gmnt3OUfRq672YXW7kYTyFHSCuQ4lXmGYI2XWSTT/0ZU5id1v3ieuta/1/tMY4a5c2FJcSrwoiS/hSl0THxY39STcBHbvf2/0QOOd7Ms2+cRH3aZhsdBSykwpCqHhkv0vgsqkU+p0ou2GdOAibDV72W9YxMGyD52+xjpPfbY2ZBxggwjxcfOTWv3K0gY1vtMpAJ31au7QghbXLuQNY4JFZ+xprTD5vY/f+1HF6L3gbbbCcH7FCu2lQ+9dmMMTL9F6VNJIXjcqkPi5jkWc/DLx8ZI40iDcmUSKcSLgmZbYopDp4Wm6M321dZ7zf+tdfJGh2v+UY7j16/8BmOcd6fq5NPfQZm979lHUdd6It3/g5a4w+DGAPFFxIJ+5ssLq/dO0csukHv2oLY/ut59TzrOO0f887WeKujMFxLuEWRQb/VXqYOPPZ2Bzfq5GPcFLedGMRBMtYJa8gXDRCbE1uuyjEkf1JSBFv911PRhm4+J08yvXY2PY7rTY9YUPnX2Xta9/MeccuX2sK3nGM3PYjRx684E0EsBhydg992hkTc/Fio2gQpLLQ10cesLEH/s5x+i58p5Th4VufY8lgEYfehP6qDAYhvQ/nQXCe85lDTMUqxiJQ1Av9JcRdDreGs04yR+6eqY1raX9oU0DanL7P2tf9hg2du4m1t24vfvef29gjt7PGE7lv+h3WsoMAI86yU23q/t+32X3PWfcJr7Xucz9NDMXOqHUIRqXCIk3M5kE08e3kfd+02tSY9a2/xNpP+h2eS1m7mNqlTMArlfii5Q0OEm+L/RqYI/qb/r0ae8p8szGRF231KWAWKvpGMUUPjhGIHIHsDNJoq88FoZDgXBatRfV5OYENbf4Anz0ss0MP3mpzjz/NTvZD1p6arbzoOmtbuwUPeh7jHWeNaT4qTd51yTs8DmvMcDLaajBnkseXuVus9uJNNnb/z8XS+i/9F/BEDmI4HjSDnN4Tbi6nikcbxAGO1a8VU2fJmHD0pPGHJvKZhRpPqtm0LMgEjaZ1mpGLgMUk5qlcUhds6ExwGt3m7Ham2haMcq0b5+BN37C2E4+z2ce/Zocevt0NOHTVR/Cg5zBIJ8Y5zibu/ZTN7n/eek5eb91nf9KaE0T1emQKErR4iOIwbMJ6PnGPXmxMWP/Zl1v7ie+B7wP0heVXQC6TZCaVIlNIsqb8yP6AwMGI7FJkB7Kt1sz7mj36YhhjwVztLdTLMm2JaNmtthIguaTg8FDaG5NzNrj53wSveuROHlW+w/PcBhZuxVbfBqRpKy64xtrWXIgHvoCxTifAHLeRu/+PyzlwydsdtjlHDKWoH3ilwFJHz4ct772Gd4o/s8OP3EIPH4de+ttE9AISrAZfZf+vkqdSZApL+r2S6Ct3TcI05CBFyPlzT8+xtxczmoYylhpLgq3lxDTlDhiIqqgU8JgmbOPVVWfZqouv88aR2wgNNDPqs4QGW2z6gW+w2N+NQ7EzXvUJTkx30s+XiMv4cJ7zrbnRfdZ32rnEUB/l+GYHcmHhRQaBj8dhRPUsa+N3f5uwbdYGzrmSqf1m+OOt2gySrCkPVBb1exmDCRyrwD9jt4Hixq/er+PGKbmbBsMVDs6hfk+l8RLTlKtX5VYAfXI09ixG+Li1dffZ6I57bere/2Ztqza7EVlwOHJhfbopPBcG7zqLrf85POVqXrA+YqP3/sz5Dm36LVdMX9P47hqYBZl4fCoWRjkEvNbmn/qBjT92BxtCu/Vf9gH29/3Ebwq+gqDcFw3n2KErEPqHPUyIzaIZjCUEbMN3+e5ZTj/SO3Y5GSrlAlY5WrlZm8Z7VtjwJW9yMiO3/cCnk040dQrRZPpUBzbb9P1/boefuB+H6sewv2/1fY9hj+W8pJCnfM1PWRWbdb32/exyj0BLnrLU9cMb7rp71+G7vsvaWLf+c6/ijJ7dd4EgVYeRSknWlIfWRf2Qna4lcLEhJwTVrOYsyCVwIE5LMZpkEVYL0dJp1OwUW/pb4JAUoyy3xsFHbfDqP7aO/hV2+KlHOD//QulVOudy91UkzvQ5EL1raOMbrLr6tYQSz1h18I02v2ubjT54I7BE/le81wNYhR4eZyWeEoYBaMq7+q+12R3fsPEn7mFqd1vvZR9h/dtJN3GajoaUSjwvhjY10+6JghcjnDKmX2W+xlTP8/2CcdOzlPnRcjkN1ZOIqHisciRaCqFpQbigY5Phy94sCnZg2w/dbfV4kIT2narOd1x9m5ieX7bxpx5yww5c+R94C40H8SJCQenYHd/yAHbw7E3Wfso/Y+HmeRJPcVFaeEs4vbjQ2eLYHX/pfAfO58hn6Ez3Yv/ALinQgud0HLpFvxaDQVcglbm6bxYjAg1+mhX6Y6R0blPaKfEQ4DHLiblGr32A9eY+vOrPrGvFGpvYtdMOb/s0C/0VKAoveVWU0A3GMY11yLuCgisuJO464XVWP7zDKiveYnNP/dTGHr7VDTR05b9iodc2JxqtHuD6+NqV919tMw9z5POkpvYAOyNHPjw2haNnvDLyLgc3yS7lSIv9ARAH8p2Qdo7dF/xkJnhWE2PhVn6+Jiz9DzhlvoTgEuJUCALdq4h7hjf9I4Ha/lvwKtHQZuEnppGm02W+67mw9yJ2vy/Y5K4nrHPoOOu9gFdj+59ADs7x8a7RW7/pr+8Hz72CGOofY/TdpdGdDDeZzssYnycdG72dnZc0sJGj575hvAs9idUcslRKNW8KucqkspuCSLeFM76JetHFDhM9K8/ySSmlx4iA4KRakAUaUiKompfxqoxX9LUX77KBq79g3atPtKkXn7Wxm/7Qqit54zw/5gqmHTMJKdZ6TV9dsZFPKldBrGnzB57xtaw5x9HzwDUEsD+wsUd5PKq229CWD7AOYSyP6FkfpY0LoZui+nGMcyUP2F+wqV0ExP2rrPdSjoMO3odD8qmAPBkMP0dTHNaC73REhpT0wxLNCnsSdhmvT+zlsSAai4Bvyis4l04bHSFiJeSUC25JmVChqPEytB2vuvyt6rZ9t/yINgpLolzRDRIqwMw4rKuPPMlO+FFr56RUIcbkHf8Z411FiHGInZP1j1PokVu+6bvc4HlbrP14wg8esPkbJefTqrCXWbtYOu3Qbd/z/oGNHD1Dw9gl9eZbxz5+VqbzMgEiTzJ4q8HUqPfQ+iMnymMnbd2ll5pxzeI1jyroRhIainkxkEjGSXnqCgvrSpt/4Q4buOoz1rvuNJs5sNsO/f3HWXfOw2CTkMKDSsRoMO1i+lh3aJjA9Y0iZwe3/ZW//HH+sG3idZX+azhG/q6Nbr+LJ4EuG9jC49HI065w2jAkaJASPjxgampP3fdpP/LpXHm89Vzwn2zusZvYaW/Ey24FfxvXLbw/0TIkg0X8lNMqevKZGE6Nu8lo8zWLY9MZKRTO4SPWkTGNKJBKvUWSw7bmwrQ/tw5f8Zvev/fmvyEuko3wOOfqzYsGI8TQ55AKPgev/qx71fgvH7HJO7/EtOXBmujfF0/x5/W9zgBHbvqmE1mx4Woej85379J0LAchityq+Ogd4chn+Lp/bSff8Lit+/DTtu5jT9q6T+yy1e/H+D2nMmCcemihPhJf3Nwenvl6paawG1Zs1r+b5G+DpGB0Tgov7WEa2bxjyBZ232H9bPv9p55pc4f241Uf4lvS01FUnpvwxUqMIY4RmwtTrC9M20tD4Lr/ZqYNj0P4k0vnRpZHsjjn/Ztt5sGv2eHH77Vqd68NbvmE1bQJ6PtTfeelxVbJ5absL0PO4sjnD3zt0jna8hPPsGVrT+H45zRbxpra97qLeMi/jPO050ALJgj4iQ450yxQLpgeIbEXk5rNOf3hgP6MDCT98/N4PzeSwTiM8INoX4NEB8kY2eYC+wIDM3zlO5zMnm0/YetH79Wccmr9gJtAIaE1gAI7VudKW9j1C1v5zj9jB1xtk8/t5GMPPOy4TXjVKIB8u+CKC11Ti0MRovoDN37b+l93gQ1tvMYO/fw1PHzvIYRiy6S//ELD8ZBVu3PlNfbidz6IUS4FBm8m1mtM7bfht/0BxmMw2aEBRybU5Qq6UpeFvEOdHiP4eq6am5W/gpiTZ1ERaAm76ObJQwIVMco7+m1hz11Eyx+1ofXn2zwfgYzc+CU8YXUkAGz4H3Mx6PRpm6P88KVvESvbd/MPnKt7cyAflRAa4tSnWaQv5eH7vxDAPmztfSt45f+HhBg8HrXpg7jwUta9UQTFU1Md120Q3808eoPN7vyizez8vM088C0GRIcsAS4witVIQCKoKEP4Gp4XESEZiznjX+RybuoEnOFSIotTkqkir5rDq6A4fAVHuqQ9t/1f1qEd2GOtK9AqvFj750GdIcTo3/J5617DW5o9uwhc/4hXYBf6ZuDPcpKW5Jnk0BBqa1UAe3MIYIcIYKsrh/Eu/j5IL279BIIs4jo/jKgdt9J/OVN+Cwv/G9hQ6PE/Ygg8xMRxIp47RyonkGammMOTe1beyBbkWTid/M4HWb2J+RIP07bf1m21g/fwcuEDtvKci21hknOom/6HB5JIz7QmDlqCr+crNoP5Kd/xhi8Lgeu+bT/WssM4wFRCcrmsfotlNfParLL8fNahzxPAPu5PCH2XXc/RDkfPbXp9zwDGlOj44LIUFLXDHoMVnFzofUDSJbJzLC8nnhAQDS45F2QkYUhuLL7/40+DgcBUMprj+c2RHDIwoTEqzddBNrz5n/hasPeun/PwewvG4kMzvUANfCIemQeuQ1bbc6f1X3699Z58hs0e3GNjN3+UkT+LNSVsBs74pfhrcSQduCXEUEMX8tqMX5poTMu7WCOPNJiAfaIIj+fW9Fyp9pikcuKpJq97X1SeMi9Wy5EIxmry6Rn9PkcdONAIVlskEoLJLs6r7rdlZ73bhjdsshqfXB9k8dURL8FQWNgpLmHsmwFehdOt3PQ257D31p/4nxQKJwGXIlLwcmwISuGd3ett8t6tNrX7l0zjk633wi8QMz0KX+ILgBZ5liRDQXTS5dwX65FF6I99ohN9PS5UocONVW1W9NkfxgogiakTitTcs7Ttc16lo9vhq9/rjyH77rnZZh7/CevCRbh82jiEJOG55FXtxFV777SeSz5ug2eca/OHD9roTV9k4T5JO7EgHVYiOe+A7vqFG+1M7YwjIL2+P3hriKGGLn6zn3I0Zl/EYOwarF0uZySSZoPoB8LiEFJUi/bQ5fWjwTj4K4JLg+bGmm94YKClQ1u803YhhSzafiPnmaYx+SBf7r3FVl9EAFmvIfhfM5V6ORLm+Y7pkLWzivIVX9YerryLvxBTpMz/VZe/XdRs721/a7WRXwKzAh0UW3lzkJpiqqrgZd18mhFMdJ/I4eBWm+G1WQ/x0/INn+LFxnbWwuMCX31BKP7x4oAMIxOTsbZ5LBenjxYk2dTpi/2R5diBgTwCFEiIs6p1TMSvzshWaiWl3IlS56cofIo1DuFV73ufVXj39/wv/toO/cnXreM6lp3RnwQkGVxIjsNoMOALO3hV9c5324qzL7KFqXE7dPNXaIe11iFcRaO0GI/BmboUcTrkHqdpYujQsGMNjy3P2YHbf2InveNDtuKSt9r4313PV80/ZsBgquVY/CUHmeew0RFUfTfsamFzK9c40W/hJRQlmjwx33Rk4SkYK9XIcV1/mE5NQnKm/u6ater8d9jay97g3QNnnGcbH3qM6UgQyHTywC4hphyNJWAnR836NnP/PTfa/HO389iizUDbkzZgz45tsEjHDaYQAXp59wDe9RWbvfLtvNg4x0774yd8OmccE2jqubyJv/JoNb2v7Bpe5z1ZlfU1WYSWZDBv0o0r9msIPAVj5fp5h4JHnUXshOxIrg0H98haXb4SKqwzVJavXue7YSL20rnoZja973k78Iuv+wsL5gnuSLwXd6lFz3I5gY9rqIgiTIhpcA/WTH2jWtt/GyexP7Z1b30/0/F0Qb3iVJ8+bLXRXb7huHGjsp5FKiq7JJkxN0JyY3EaxIOOTgckl25hbBzZDUUTMUul52ybfvKndv8nn7G2gRPwGL2fDYQ8O0bZRxWSeZX4ZPRp1rxniZk4keCjNi2ZjiKW1FQOU04F/Q8GU48rBTOXj6i+Oni2jW77nE3t+HsCYdYjnVdprpGSTMLzRzNRduL6/JyvdKb3cArxOOvceZqXQV2U9Q1O+OLNFcMoiIfkxsrqeYWXwnIYbggkSZ16QHLmSXgWzoWRHTa/92e+PbiyUZYkU0SNQktgKckvAnWexqLOX1QgYJqy5YCINTxcp0Qv8XQBWgymnRHDZNVVtnDgDjx0P7Lw0whZWrCgI0JuPOCkvap+tK1TkpN5rmQj0u4pXuom9wGhoCriZqws2gF5RAjJjVVU+S4+eFagKgRZWhSciBiJgv4jaMdKYlN2Hycb+0TPwQOO+hxHVISrpGAYQ6nhKCNFmJc3mNCTfJLlBOphHXL+kY5nunG5HuKvsto8xJDBVea/2qW56q4T6yx/FKBfUgFo4Katm6tbtt5cD8ZqZp06FCSm8LjT4eVhUPDTAvpK5dQuhV3pQF98kiCBp7iLbTCYzB76wVUhgC/SpF7ST2XlAU2EIq2A6wMpg4kO06/k34IjXCUZpORPvaQpfBCPNJjTFEVGRN+tATR4ph1k3tmUT/KqNbp0KljE0F4IukTZp6RXhKdGkrdLCvVLqnDpSFrlAEZZ3qo+NZftFBMdFV+qLBT6ym6VS2B4qOxtgWegT/mYMolYlDX1R8IlyUAu0AQaz8prvAZDp/65rnafimFFrFS6dd7ML7H5oIl0KagTT5Rojkyi/mFkoKIR8iVCuXcGQJ8CXow0In6i46xim/PlJnQnIVpqVB4vF8zbvEelYNBENzYcRT82OBi3lDt4xC11plGTSr8Mx3rH7xzyxoPk05CFrFdvpFk39exRyiOAIKgklY8EAcXXeUcmIVNjhKfkTqUWtOS42jthTB7XMCelbi+UNyBoii4a+IffPgNOQBoQLdi+btEQ0AUoyummQinOYtnZB893iYQgichjV0CimSUpxy6Nrva8wqd/xEvRWOgyIFHkWXS5QP7rXXzPrO3TT3vJvAYwyus1UVPH7NUqZX5KQ8dERAecI6Ib/yr8Thzlis71NcX1hwkSyi8ouYDQlCtLUF3ipZ9x4mLtZDOSo/NVhpep+FbOOkJRorjJ9NGiClDQN/1+2Kta4pXKsKJRN6C8UWWSt4Vi7HEICGSNRrPRWW2rzGb1tYJwz8Jr3HLzc0W2MOvLsvqabTwKVtuzZhvBbkcHvxXXkVfa27NqV2eed7Zn1sHflrVjKBlEwinpeLqO5vpxRS2QlElWo1vbIOYPn3OAICvhKO5HFQxSpSRq1TZKLAsVebsMrR9QVApGXaStH3HUpekCvyY/bdVgkHWCUugDY246cvKfjCAUgJI8VsQQg0zeqZq3ioHYCEJlH7jwhofHMt9ug7GKbJWYdnZl8x0nVvLunkpOubK8K8+XdebWxreCIjCPBNPzPlPHsMPBmXpz30zd+L6nqd8c5TtxO4jS47jAJOM8gYAzGHKhXssW8ry20Gy0Ndr5ZT2YN4u2rJif1U/rNXJWzEoFY/GLLG2VarN9rsb5c27LAOzhNwl7cJk+ztkHmJ08FdsQVhtCySH0GeIxt48B46pU+VGwnDI6IS2dPnAaNBnV86aXNZa4bVNxFDJqMD0ht2anks90lqU64QMBXHGSGt1YIK1Z1pHbaad29nbiLXN8OTKz0JjFK16YmG/80uYaT/Kjrk/WG9mutrzYzTH2yJ6R9sOXfunO8nxaxP5/pq1bLf9d29BZ6a/2TM0WfYzDAD/+uKI5l+uXIY/DuVaj5DC+QxScraQ8UGnL+tva865OfpauvaoFR1YJUvsU56bcL26ztWa3Zg7GXC8oWTLb86cb78PGg7jl3+LDj+Olj+ART+/d2dznH7sFei97F60w4QH9lDvjy+K8FMCn6Lj++kgNhfgfB/2lMF66vcCwz3Ru6OngSJWAgDOcfBDPHeIwgqd7PLTQmp1zjmN9WEQf4C9nai7HOPrJLC1RTx2enL36/wFb6iVp2EYZlgAAAABJRU5ErkJggg=="
          ]
         }
        ],
        "meta": {},
        "name": "icon"
       }
      }
     ]
    },
    {
     "title": "🟠Lambda💛: Last ${limit} Requests🆕🔼 (Filter by 🔴🟠Target Request Id: ${api_gtwy_request_id})",
     "type": "logs",
     "description": "View the log of selected log group\n(Oldest first)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expression": "fields @timestamp, @message, @xrayTraceId, correlation_id, @requestId, LogLevel, @duration, @billedDuration, @initDuration, @memorySize, @memoryUsed, @maxMemoryUsed, @type\n| parse @message \"START RequestId: * Version: *\" as requestId, @version\n| sort @timestamp desc\n| filter correlation_id like /${api_gtwy_request_id}/\n| limit ${limit}",
       "logGroups": [
        { "arn": "$lambda_log_group", "name": "$lambda_log_group" }
       ],
       "queryMode": "Logs",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "🟠Lambda🌼: Last ${limit} Requests🆕🔼",
     "type": "logs",
     "description": "View the log of selected log group\n(Oldest first)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expression": "fields @timestamp, @message, @xrayTraceId, correlation_id, @requestId, LogLevel, @duration, @billedDuration, @initDuration, @memorySize, @memoryUsed, @maxMemoryUsed, @type\n| parse @message \"START RequestId: * Version: *\" as requestId, @version\n| sort @timestamp desc\n| limit ${limit}",
       "logGroups": [
        { "arn": "$lambda_log_group", "name": "$lambda_log_group" }
       ],
       "queryMode": "Logs",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "🟠Lambda🌼: Last ${limit} Requests🆕🔼",
     "type": "table",
     "description": "View the log of selected log group\n(Oldest first)",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expression": "fields @timestamp, @message, @type, @xrayTraceId, correlation_id, @requestId\n| sort @timestamp desc\n| limit ${limit}",
       "logGroups": [
        { "arn": "$lambda_log_group", "name": "$lambda_log_group" }
       ],
       "queryMode": "Logs",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "👀Traces: 🔵X-Ray",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "volkovlabs-image-panel",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "X-Ray",
          "type": "string",
          "values": [
           "iVBORw0KGgoAAAANSUhEUgAAAFIAAABPCAYAAAB4ZJLeAAABYWlDQ1BrQ0dDb2xvclNwYWNlRGlzcGxheVAzAAAokWNgYFJJLCjIYWFgYMjNKykKcndSiIiMUmB/yMAOhLwMYgwKicnFBY4BAT5AJQwwGhV8u8bACKIv64LMOiU1tUm1XsDXYqbw1YuvRJsw1aMArpTU4mQg/QeIU5MLikoYGBhTgGzl8pICELsDyBYpAjoKyJ4DYqdD2BtA7CQI+whYTUiQM5B9A8hWSM5IBJrB+API1klCEk9HYkPtBQFul8zigpzESoUAYwKuJQOUpFaUgGjn/ILKosz0jBIFR2AopSp45iXr6SgYGRiaMzCAwhyi+nMgOCwZxc4gxJrvMzDY7v////9uhJjXfgaGjUCdXDsRYhoWDAyC3AwMJ3YWJBYlgoWYgZgpLY2B4dNyBgbeSAYG4QtAPdHFacZGYHlGHicGBtZ7//9/VmNgYJ/MwPB3wv//vxf9//93MVDzHQaGA3kAFSFl7jXH0fsAAAB4ZVhJZk1NACoAAAAIAAUBEgADAAAAAQABAAABGgAFAAAAAQAAAEoBGwAFAAAAAQAAAFIBKAADAAAAAQACAACHaQAEAAAAAQAAAFoAAAAAAAAASAAAAAEAAABIAAAAAQACoAIABAAAAAEAAABSoAMABAAAAAEAAABPAAAAALueOWoAAAAJcEhZcwAACxMAAAsTAQCanBgAAAIEaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj4zMjg8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+MzE2PC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+Ct2GFjgAACs5SURBVHgBxX0JvFxVmedXt6pe1VuS95KXl30PCQlJCGQhtEYJq7KEBARBehRUhlGUHm20B1sYFh0UBAewHdtxUJRlsAODhLVjgCCEPYQkhERC9n15eS9vrf3O//9959yqSh7+Gof+zU3VPed859vPd9Z76yUmEsZEYuGCK7eOiyfjk8OSxAKRdChhCrlULCwhH0NekJc0UFOhAB4L0yKCfAx5SUmJ+EgBA78apPgCJkESaU1MYslQSoDFUOZXEoDjK8xDh3/3qyhhmIe1OeiSh+x8GMZy0D0ThmE2FotloEE2FMnA/l7g9UoovVCsBzCUg+5YWOwGXRds6oIfOlHOhkFi42M/H/l+Yv5NEl9+kxTiycTf1fcb8a1sb6sEcfoB1kGK2Uhf88MyWIVgDSl6Ic9/VvR5pIpTstTju7SS3vLGqq+7Sizf+kIxFaMa0zEqugygcQmCOGxIqx3ONrMxOMJWbyl5OX7Ep/74IiAkLBWkpnag9HbuehxIixARy1VUEIaJfLZDsj0d2bBYTIA+RHTiMmKXcw4z9upALwgIkIWg5WXCWbYilUAeibsZkkegkgpxBIQrCEqQxm7AUAZlHo7OnMFq48OykVtZFVP+VCMgN2OFbsW86cwE3ZFlwIlil2XpQ2ijvlScYrGYy7SjF2rvQ/da7tBjsf6xIJBcd3c8n8nGA+T1qlDOK8o0cHCVrIqDPT8Kt7z6jlIdrjOvzJetS1rVEogVZaOF9jA1hF2RMyvLtB30ntxnNMqVL2WbOLpDVSFDp4+CAFS9tBKRyX9Kw4rKPIuKiTSQUrEQy3cXybwfb4mWlvmUwatJFVDdPBPlqAyJUClAFYsEsVIxeMPl1WbMQrgrmoFA9XFAhhXOUwEVZc+FzP+iM71Ex498yrJUIb2VGwdFj+OqVX0IpBzztUlnI1G+siaNklpkqp2h1BEjmDpV60jcFJYwHpeK5j0aRC4VX2PqYCBjveGAk8MzmCtTAnEoghpo0crKy24VOBGSoStZWUaZj/E7qqw6qJAKWeWy6kIRimeyVAVqqEXjS2W1bEDjxbsrGyU7EjUI6y++OIwHN90U05FQAumvjkSldjVHaPwdKQkNQFnkrGWy82WfKp4hqwJlHBZJ7HgpHy0SorjkTMZa5W+k0Y+lruBolKC63sk2Y40fscp8yQdfA/Hui8onKiuOyVRs1QM5DTe4Lhark5E7a3QgPPuajSnAG0sakRrckZAqwU6qyTfmXqA5QRHKijh8JsbH07BItZzyxlDpjA/rWK2lCK40ysLzsfRI2VHZ8f0wZxo/k2WooKzQpVo/L4t6UTX6iYMFunZ3vTky1ZmoRQ0cWUDXLqmvlX3EVFUjtdrH1LLG3AtULCNUYRFeJZ1q4dkQ2fGKcBSCW4Usoju+ZrzHcRWoO1K2lrXa+JDOWFi5kr/Pm0jq43HIwKmiMMD14+qtkOpOHK7ViAziYSNDNCwWsK72TI4WrDWV9QZQ5moKykrVB9wry7SMA3ynoCVKqPwMx5e1pHCVQGT9WOoKFXxdvTL1ngAWyqhhhndNo7KDWQK8Chzy16LdWLSvSgyTNTXptDoyTNQ0wZFpRiQpnDiXN4GUa3VHlE2TMmOUlb4PuGnj+SgiuQJMZFeuyBsfZUQkYiia4Rr+kbKOKis/FUJqlWV8juCr8g1mJOAU0SolVVA9LMOOq107GcuFFpEIw6Z4PI1uHRaxCnddmyqBEtQ+Jbs+y4rGmyKoHKOxciXcVR7Fx6IFVOShX+N3tGyrJ1wNJRqJSMObfhwfX6YNrNcbE1KXy4SzyvhoRstkpjDHx8pKiBv8pGuyOJfUtdzrYhEkzbEgIdjRkJsj5oTEdRNncUdD6bqgApoukn0ZFcQFrS1ZlQowo2XKtRlTjNFANbw4+kM8biy9rqwLArZlDO0rUsDEaHwBcpct4lFQfkZPR2gEKE61rCrZFARMakidKzcDkQ1qo9lAfbzO1XyUPAyCRKwQ5tPqyDCIDdLVegmqU4671AA6CP8+kjMrFKGxlbuSIAilJhlIvhDKnkMl2XQ4lDY07kisG2oTMQFY2nGkwAYZ2y8mwwYEUpsCfjGUIhuBurGxIQOsgegNVbA2ktnwF5xJQgYHEZWPpeT7b3WmqkEuCMBYKWcRCXJzJCISeejGOzMuypji31/rTNJy85XGWVAHzlKe3pSXecPj8tm/Scu0yViGDU9JU2NCHZaDJzs6i7J3f07Wb8zKilUZef6DvJw4NC4D4NhsXjWEcuBa5UyqS32Z4qYm/Ps5kx2MF2UGpVi9RiSCZBCB1rWZc9cRLfTXOpNdNQlJL20syGem18gTXx0kc05skiGDeer24df5nxVpO5yXt1d3yuKnOmTJqpycNDqu53wFjEK05f+LM9lK9KQ6U9NyRPKoB2tIqmatSvtUU21iwBCRf0VkJtld0S1f31qUu781SBaeM0QarP0QdVn5YHO3bNmWkf0HC+juJYyZgQxsSsi40Wk5ZkKdjB6RltM/PVDmzW2S815skx/d2yZpnGwOaAg0OlXFvxSZtEONpl0YDly3Lg8J5hQGCSqtNyJ1oR3ZzTI8oPTAVDz4A0DVwByJ8iDbZ9tuUYlQb2MbFfnozqTj6cSeTEm6cZT61N2jZfbMATRL1q7rkCf+tVWeWdEjL+8uyRAc+w7EKSHmPxxkiXRjjNyXE5nejO5/clrO/8wAmX1CfznvrGaZMqlOfnjPXlm3rShjWuKSQVf3zjRf0GH0ievmBOqlBqHuQ5wJLtT53+RM8LN9DeZpyEH81WLOFJly0rXfiMUSo3raW8OwWApiOmuqdLYBmFueQnhRSU1dhS85oCYJHKHm4BCe8P36jnFy/LRG6ewqyL3375Av3LxXdm7PyZDGQKYODmQkJpSBGP8YZQMbMME0BTKpOZB6TEDvbMzLPUs6JDyckQlj0zJ6ZFpOmdsgu3b0yjubCtIMOt/NTR06SlVwabmshmidh6Hgy0ZSdfd2eoaeL8v8hx5cCqQmKJWyz8ORNwVTZp/4bcRDS297m24Rj2JAaSqQcizjcchQoZX1yCfAee2ukjxw51iZOqVRWg/l5LpbNsktizvl7CkJaawPhKstOqGIxUIRocgvlzwKZx5f4k0YFJfn38nK0hc7Zc60FJxZK3Nn1su697pk+76iNCCaicuIZi+gbOZ5WTx6xykoupUdQ1AFTlQBqM+71BdpNoKuFA9SQbGUeSlYcNVVeA4T9OeuhqsfXhrilimXrYq1ZZiWqsvsV2l01afX5eXu7w6WGdObpKe3KDffvlmWreyVC6Yn0d1DRCsO7IFbZsucdUuVoRWhLpN6siU5dlggCRxUXfYPu2TD+93SvyEh1109FEsiVQdLKiybukry3q6ivLOjKOv3FKWztyQ1mOS45DLTgOzwmbIn66UZLxsQV0E/HO0LUhgfzNfGgV372FlXNcKr38WMne5tP8wW8EF2dGuwGayh2VSqg28xT8Qu3dZRks/OSsu3rh4niUQgv3lgu9xw/2E5ZXJSurD8iUaOiuatyIKvjw4vz7ovGwhLUFn+epecMa+fDB+akuEDQrn+3k6pr43J3Ck1ct68OjlzdlpOmJCUEpZSXCk0JGNSh2GCi/tqOTTBy9LsEWVvLOlc3qUswclYNKBrF7NvJKSU6ge/Y5/Nh2wY0Yios5wiujIcDzhbRx1mXMow1uEf67jMeW1jUW6/YYik03FZs65d/tNPD8rCGXQi+ZMvlbdW9XwjgxgNVTgoEBdARnH/ukDWIep+9/v9cu3VI2X+vAFy1zezctq8/jL9uAbglS+uFta+1y2/eLANk1NBhg+MSw7HCUE0cwOXUUfNI5u8flZX1g8amPKogL2qE/UivaSCWDLeDwgpO0IDkHWs0pRMowwrrOxADjnC4XPc9s6SXHJKSmaeYDP0I3/YJ8cNimkX1YW+0lbKMWaU40VZxpdR72govzdXkmkj4/IDjLXvru/EIj+Qa64cpk7s7inKqjWd8sLL7bIG42cRjjxxeoP85PvD5FPH18i+tpIkMX6WbTTZBPQtWw2mWNQTx+FX+IfZAI+dscEu9YvH65BggAlDdHoS8OEWMD5iZHKgX4bx6X9eNFDq6xKydVuXPPRMpxwLwxlNbF3GrvE1OR85MqETt4sT+sfk8WfbZNqUfro3f3NVh9zxq4Py6macqUIKRhQ5C8679j+2yCSsR6+9arBsvH63ZHMhhhs6prpXAKB0Hy0y1cW0KIVNR4CnhzywwNBPj+NDpjoR+LJrEa0kzJU16/BJp05CRE451rrYuvUdsmkfFtnsNrxAYDRAVjauzIJjZi1PXMNnRqsqcPL5EsZGrE1f7pFnn2uVpS+0yqXf2yOt7UWZOyaObyBzkK7fmpcrb9gr23dmpKU5KV+/tFHewSTEqPR86T4vm2mlDwxHFXU4TBwOWURXDP0CR2j2eBEjsWls1eSvRmhGYdUGAUSmrHE3LmNGDQ1k2FC+hCHYsfRIEx5WEh7xjmg8XypG7MpyBV9WksaQIj7stlxzXn3bfvnKrftl2nCsOyG2F+9KMOq4MuCBxyF0tEeePEQBMnNGvW4xuTqx4c5kqrQKHaKyk+lFexsiZ3oavGHCCbSRjsTOBvWmtCcw25wRSuTtcHjUDjQkY7fmUmPHzqLU2BMMacMxTjOMUz86XCZK48vK13igQj+8qbKK424qUpEdDteZocwYFVfncGLh11eyd/TAqRNaMNy8kcE6No+tZ1LGj4jLo2vsADvFl2d0CFOJjtR0gAZWVi96/cjedGB9JC0Ma/DaQay/dkrM2k5lU8YRGD8ycowjXiwb01qcPWzdW5An1hbkm5c2YLaGR3HV4ty4C0sQ7dnAVeyIb0WZFaw3BDOAikY05IZKfhTJ8oRmMflwm2jMrd5wSIJtKrrxn7FopyN5ffHCJrnrigasO2PyypaC7tcZAGSrGiFlzj6Or5OpiVZ7OA/BNV+TALE6Eq3rqJVd1FLWB4DuWo7TBT/E5ssYXO4880ZOvveVJvkPl4yU46Y0UZReCHJsoCgKyLxAZKc1KLulRFWZmNEkQDksg46TlKZ6U5hFkulifInudSMeytaEgIeyCQcjk46pk+OxROL3y50FeePtLrnvsQ5ZhwlyEo7psgxUCKo8P43KtEHt5iQF5qoYUxWUjB83++8XJpK1c7sP7Q8LvdkgFs0MjgB4RqkELKmCZMat2B83FOTxu8fI1VdNlJaWNM4S8/Lmylb5/aM7ZMmyDhmMfTO3fp7OMs5E1QgQOsphWMZk80CAR3BsME0NSTF5M3IAPVyz1WXKbsFY+vqajGzZ0iMHsVVNIhqHDUnJeOzdz/hkvSTw0G/JmzkZ7nWt4mP8vIZelq0phSfk2Gvnd2G6DvtVHqH54CEBne7HENUaZR+ZKewylq4qyLL7Jsjppw5X455Zukt+fu9ueeqFnIwaG8hEHN7qi1hsZfzT1nWMqyIRgljGSI3Gwa4fDUQHZDBpZNh1C1AGVy1kcofCHU4cYzJxdFzUqDCFNSiPjEzwhiby5Ipe+edne6S5rl0u+GRaLlk4UKZMrJNvXDFEBjYelBvv65ATRiY0MtkFPjwyYQt9o1pReIgXIudce1kikZqKiMROJx9w/2YIioWbRYeWLASkFocES18vyIN3jJSFC0ZLNluUn96zQb78xd0ydHRMpk1MSHN/O5SImIGpcvYpGYIfZbF16RxOSpv3luTVLRiv4aThOEabMCopk8fWyLgROOho4HpUZNPeoryE7liDoaMJ0ZbCvlHPCehAXl6GKxosJo11MRk9ECdMSN/5ACdRT3bKqKZQnTl9Sp0EmZw8h8PjFuiuR7NVfLRgNjgZEIT2jwfYXu/jrNDgIjISqw1s4ahhqfHEQQqfuNtLf+70lJy/YJTq+LsHN8t/ufaAnH9JWvfSPTgs0Aimo5QZ0DTqVHQUmXhqKSnugTEhPfluQWZjRr18QT85aVZ/mTCuQQYNSkkdFvZ8SMaLEdjTU5CDrVnZhG765qouefJPPbLhYF5OHpPQVQPHOc7YfUVmHpFtM7tgaYTnRM0xufDmVnkaOpx9+kC5dNFAWfpar05gPD3ieB2NkWp/RZnOUCmQJaVk7IKv73whkWyYv3/ju8V8TyYeY7/i5aJFHeLKbOk6PApfuiQvv188Wj5/0XjZ+MFhmXTaGjlnTlK6sXbT1gBtJZ3BlKuDW5TXYRm7ZmsBRsXlmita5NRPt8jwYbUOUSSHbn24Iy9cgPNKYuZq7JeMlleE7d6bkeUvH5J/frhdWrEZOBaRm7EJ2tlAXYjJIjMmmynHXgbGPjyAW3z3SD0EeeCRA3LL7zplBndjbBS1Ral4U3qm2pfQieJBOigWs+8xIutwmouxjJ4lggshN25VPa5kLfvfYMFBre2lV7y6H4NZyboCqiwSyIPMIDHiwzKLoUZYAmPck2/n5MdfGyBf/MLoyIF79/XKqtXtshLPadZ/kJOt2Im0dYMfaAfi4HfssIRMOQZ7+eMb5MTjG2F8Wi67aLicOm+gPLB4r9z4cJeciaGF0au7MxqtSplsU4nORBxh9cLjt22HS/LKGx1y0fktcuK0OtB1QFmzAepCdEUkHhGZ5rWQu044EgMCxhj1oRGSutIJViZCb1bk5OlxzNAWOavXdsmkcXhBlWdUvLQ7UHlTpJqPzfQUvuz9ojz1s9Fyzmdsotq+o1see2KP3P+Hw7JyW0kmDYnJ4Ma4Hto2YUyjL+icHXvwMOz9nFz/YKecNHK//O25/WTRuYNx2Fsn371mLPbeB+TqH++XqTi/1McA0EP9qLejnVlA1I3Bvn31+gwcKXggVyMTW2APoxoy6dAPd6bVA0VHn1odI73hsF9dEJXN5+SGYQOHtCUZjaiox8EquxxPvjmTcnA2EmMQ8ajgw7bh9R52Py//r2PUiax+7ImdcsZl78kP7j0kg2DUgpkJmTAsjmHEePIZOA2mAE5047HmWzgNExommp88eFjOu3KTPP7UXpV/9hkt8vBtI2TLAT7kwFBDmaBTK1QpFpkxBzFqaxGV+w8VdaxuqIvjEQje0Idtzo+Kq8xBVuZjPFAJGXjXGchpP9koElBNMOmJbKknM5BOP1pFB/pQJr0nUTaO1gO5g1j2TkEevmu8nDxnkPRmcG5515/lwst3wDk4mD0moZMBt3Z5nqBr45hWqhOU4CKfJ0l8qKbHZDicGI1jukXX7ZU7/mkreJZk7qwm+eVNw2QFnlzWcMhX5VU7y6tJziIm1FuHNtjFcRNfb6erJgZgKOnHUp1IAcOxGaZu/vRDH8U6JFQok4qUogjkEqMePXrz9oJ0dnJhiwOKIUnp7C5ptHohvsWtTFK0OraRz2IH9C93jpBPf3KIZODEH96+Qa77Rass+GwS55VcN8JzSqRqq0wvmxBTzPhxM0CedCadfsHspPzgocPyo/++RTJ4NDHv5IHyq+8MkuVY5qTxI43IpiP4oEbPSnnCnoAHM2iIQ5i02AC6BqYf1H67mTPpI/jDvScFh2LewnjLiKQk/eeoVDAhLFtBWy2NbvzWn3I4nMDPTXB94uQB8sHbBUmpsjSWH0dnBd1GbttdkG9d1iAXLBytdPf+drPcek+7nD8LDaFHoaQhpdEbKZkRokByVRyeNe46WJTHV+RkV2tRI4iNeebkhB74/ubBnUqy8NwhcuVpadkNHD06U+Ymw/Nll2zFZDYO61UOA+14IWEbeNv+27QhrmrhbqYSClqGqBg2OKBNmiNLuolRM44gUEJnkC588V7Giy/tU2VPPWW4nHFeWs8CeZpiLaZcnK4ciWN4KFWSr35ptO5cXn19v3zz6n1y3uk10gEj/DhGhkrPlFrqhzdVSMuMxJ0w9IqF/WXFQ2Pl8vP7qzNpeCceZVxwfFKuvvuQvPZmm8q64tLBsh2zsh5UO57kR46URX7r8Ixp5nR9p15fVtgCfO6UvS0OWRN/K6tEThgkkSR1SVOuMTNUdwisTFHIYvw6FVF07Z375f2N7dLUlJLbfzBJ3liOkxRs6eowGSgR6Kgu1wXrt+XlhiubZNpU/MCntyD/41c75KRT41gB+K4MkbycDh/qTPCkw97FjD9nZj/5xNxmvPrST9ZsQsQBDsk6PHxqfFx+ef8+HYOnTukvXzu3XrbuL6rTqJV+MExxN7UHk8xX59TI7BMbVYUXX8OJflN54e5crnXUz7mDyqKoJeb5KgCHV4egaCbIEElPgoqUzPCd2Cxy250bpBuvRZx4Qou88dY0KIVlzdqcjl0cl8iOLb59FZ4qnoHFJ67X3zwgD/y6W1pw6ModDXFUusogjcuoHC6YbY/NlHK1Grx5fMZLU+0JVs9n4s2Y+e/7U0beWNmmOGee0iSrWxFlsJTRz8aoR4PvQZfvwhsd/4DHunz28867nfKbP/bICGwjbQ9fqR/z9lUNeVNlKAJLLZRwVmDOUbjdACaCU/yINIfIGzUkLvc91SW33rZWt21zZg2W5Y/PlJuvapalb+Xlj6/ldALqRnc75ZykTJlsx2vLXjggY2dyncaZnyKonErSlCDCuO6n4RzfngSvPejO3pl8mM0xiZemRFa9mdjkMX1wTF54qV1xJk9qkHOwSOeM3o3l2waM14/iufusyTXyyN2j8EynXg+hf/rLfTIB20Y+E3LsjK/XT7mZLGBQbdTzi4jUOg+IKrXWkAhzFD6lB6jQ6RiPbsXa7zvXvS3bd3TKyBENcv11x8vGl2bKvT8ZYdGIZzafmFUnAwaksObEdu6VbhkzOK4zZdQ1yNg+TiaeJiHK1u0syN99qVnef26qfPPyZtmAMrswDzT8par5srOe604+Znj57V451JaTAU01Muu4lOzH2DdlHJ7dXNhfXv3ZSLnrh+PlmHH1cqA1J7fcuUM27ChIf8zeXAlQEccOWaefS6lr9KUimF0qHGnIapAisuxgylSBABmcAcHn1GeckJRnl3fKgktWYv+9Sfbs7cZbZI2y4JxR2N4VdKAfN9Z2Qbv39MiKNXlbjjjjjZ9FVjJuEw9FcEjY805RJk+ql4kT+slkHHdt/7Mb5xCB1IZXtIYlkVOePNkQK3FCxL04r/FjamTVW0X5/rdHyX/+2mg5eXaTFNAruE//xj9uhV4ZPPfGQhy9jZc1Mp3pJLnUw9U3lKc9o8Sf+ppzTQmWcKGyfFJtIA4uZMJNvKVEw9tmcOZYnDvyHZ5LP79ZJs3aIdd8dTAmJbzHwXFyT0lacIrD6xAiUnBMpsJVMXUDFmF4uRSz9x4cHvAFqn71gPMUHw/OeHDBS1NMrGpIZVdmJcva2GDt9sIst2NJdAg7L16D8BRRsNvhqVEXXubi49vnVnTJb3GgeyYW9YxgTpaRfVCSzRWVObhSZ2c/U12QK/eY/l66bBeAapptTkEH5EgxrXROBJY6lVzwFi0U4L72jHNqNH/N9/fgSWIgJx6blHdxrtWAc0ReRd2Pm9F0D36Rq4P80rV5+d8/GiFnnTlSli7bJV/A8+dFs9EK8AH156UpIqjPi8yUrZquNrCRBfhFbtBx1fF3BzMCuemuPfLazpLghQ05HtvQRVh78pRHx2wVAkaw2x9CVwdP2Zl0Kt3krhIjsggtuWxS56ANys6DE8vOJAmwlFdlS5HQWq+3F3CM/qefjDdhAONYRQt9VHmneKOxcsWEApzNeE49LC0DB9ToUZa8jxl2DkiPdBx8QlfRiOhSERVlxVAlFcXL5ARJugGI9rMm4q1foOhuikswRQJAeSN1wVNulkp7HW/SgB8bDPcSzSiQkaqiCtJ51IGCLS2XPYw8tNKlngZwdLMM1pp0nuHEpBWDOa+GBvb1Mi0FOTbRmaOdPdIEXBguqi7t0oBYkLkqYLJMRvol2GZ9/i2DhgZ0aVytbXmcY9qWkuMgn3+7YDU60Jgu5EMKS1UTZa1A4FhKZHR7LQCG3zOgYfhcm5QGNSZRwQHLZQAURgLLWOoViTjp3lxGYju3u5dM0d3rZBS6l64fHRNzGZVSFCpnGfLW2dOKelfHAq5jYgUcZfsHGOnw4TpwOg4zhrr31HfvzcoIjLH2SAIIinqkzr5sPJSRZq1cba+Tpb00LHINib/rAEdqpJoAs/FoptXONNxq5p7GhHBWPGFUgBebuhClRRkKR54+Ny0H22x/TKP9epDy9WJaj/GTbatLT6cTKwHXF0ixCPD+1pT4pDMFdf3Zjm3fydNqZOiQWp341m7IyAjsWLhGNAeV9Xdkjt7bgHpFsRRQagAR1Sn1xoFFkS8IZPiXAxyWIioy8UFkdMaMnKvKLPBjQJcaDsm5HmvGLPwvj/TgUehhfVfyrNOaZc2r+HsQGJ05oHCRzD7M4zFemuKX+YfxExFpw8uvHs4oxGm5wrGs8ZOIrvk+KOp2k06lLlxrvoZ3zE//VCNkxrB/7pJnVmalCW//MiLLNlAmyw6mRQ+jNsgrMlNmy6nRoKxWCP52RRj2Yq5hC6OO85AbQEGk3YxCgBzN3lUTEND7HJipAxiymhrgWc5LL+/D7magnPLpYTJp9i7t3vzNzMSRSVl0SSJ6OyON19rP/3ydTByfxiFuHG9r6ApN8wu/UIcFdErSl5XhxP/c5XXSgFP0LVhQ8w0KjrOzRgY4rtNfvciK1w5Jp18x0HbodLRN9AnsdPWGRZC2Dg0hmdlkhrFIz7CiwIdfa4MgNW3n6pUle0HAlip+rPKpCiENCV1KGZVlq7J6o7MHTMTK8JcNj54kgwfXyf0Pvi9f+vZOnSReeHSSzD8FA+n/4/XiS3tl/oVb5OLzUrJ4eU4e+PEw+dtLxsj+Axn5/JXrcXYKTdUpEGSKa3qkDcTxZnnbvC1WYfTEQU8u1fZvDvDUcDWbuysW8EdAWNXBxRpBvLuI9CkAfbRidaRaFFZGNAd3HDpgDffy8zn5w5KtctWVx8mFi8bJ8pfa5Ne/7MD5X04X6j04FVIj2A5qCTRzeqheNDCCIwYYHQwJaMWo5cJ76LiY7MJ7Pl8+t1YWLRjBSlny9B55CwfR8/HaNde7ZBI90ANteXlHwSyDSHGYakFh5R4JOMBWE8VvPrbo6zv/mKzpd8au1W8Uew93x+Pcm/FyWltrsOisoBDNUrAiHlUm3OP7lL9ofv7ZvKx65wQ5YUYLXkLtkPMuWaUL4QCnE91YjtRgPONQWEDXURm48Z1xvn1BOIdLPUGFWKZ8lEqD+Cx79CB7qM/f9Dx27xQZM7pBVq9tk7lf3CinH4tFtz7MUoXVNlOdivZtA/V2VUAg3pF2AxSPF+sbB8WL+d5XEJFhF2dtAPksAYohOsnbwgCJjZU+Jfzo8YVCYJKOHZY6LOAaPR8HzP5kXL77j+/hGG2OjB3TXxbfN10u/cparD1LMnEifu2AgxATSwdReX76MIBeViVZF8PbwYFsxYkOXsORh/5pkjpx3/6MfP/WLXjSaMst1dnZpDbQMSyrEEYieZVtsCriEIVw/dCfZqcH6Is2JbyiEoaHOWszKtQKINBpernUl31KPKty3JWGFOWyZY0P6bh27IenfhvxFu33bliNY6usTj5LHp4ps2fUypOP8g0H/nJWPaQzPp8ccrmiTxGRssw9vX/fh8+kc5hY/vBYRmZPS8v/ufc4mXxso7S35+SG//Zn2YZDk3pMQqRRnVXFsm2aoyGW6cMmhoGZ5W0zH5Rp1LP402DY2cQOw+8YI/GaEeq1BZBRAnIhUJPqlHCt4s0ymqhoRSWcVZaywC3kMaMT8vQL3fLt76yUbds7ET395Od3zZLFj47Xffe/LsnKjn0cL+2BGR/11uLLZ0V82MUXqbhm3H2gKE8/m1WaRx4aLffcPl0jcRuej3/n+vdk+Vu9Mgq/KrNxURVSPTWn+pptUZkZwK0KBatQ/Y+2idXaZ9gHGdRZjErSBi/iT8HF8eiG1crBmBKLIU8YYppOYWhTmI59FKxdhNwcHbHhhL7e5KJzeNA77Zi4vPJmj5zzuTfl53cci1l7hFx04Xg5bf4IWfHqXln2/AFZ9kqPvPc63kZQtlSEX1xYVM/Aj57Omlcvt13fLJ/4m8HYo9vpEmfuv795Gw5H0GA4keIaVX8OCBv8IQSVN53Npj7LkFXdzSG70iaoQR/wS4egFo4slfCCNXYYXLlyRGelIjhsYOn4QaA6kwmU0aJWlp0JuF5ecbYXYRVlc6bICDzkz2MCOHX+Ornxlv1y2aVjZdLEAbLg3DH63buvB1vLbjl4MKOPbsmXbwK3DErL8OF12LHYwyrC38f7Rw8v3ik3/qxNnyfxMXEv30PiPkMdRzU+RmfSF85UcMZWP8wmMP3hl5w4bYlzJcRai0n/vox5jPpURuZfcCZ5wH+VzuvLmVkEG2ddHr3d9etWufmeVvmv1zTLGacNkSlTBqijKp0FjlVXa2tG1m9ol+eWH5RbH2yXwXgr4+xPJLFeRXhgYrMeAxLVhVGI7MftTMcesZJJoDsf4E+MA64xeKkvy4K9Ikw/TmfSuVxjduMndTMn4c8ZgP/Pftsqt9x4UGbOq5F5J9XJhPF1eijc2N9OcA53FOTAwZxs2torr+IxwpvPF2TkjLjMn8TXSO11Gl22kJlGIhqfFbTsY45MjRfypSz8rUkeHLYWixmMkXhnzglEdZXgCI76j+RMZfThY6aLfUwI8CgUOgGvrCSmQCt0yyeWdWLLh7fC7EGgclKP4GcgE/Edhl/MfmZRErM7D5bL1XSYiVVlK4YdQD9OZ2rTURKdBkfihb5DQamQjSeSKdvdsBPgiloVWe0XgFHJj+JMDQfSfbgzGTK+cbIYM/WkGtPyGIyh40dyhkZUcayDYLqIKjCSuaTpwSqA9Bx0qK7JIYiYuCIbPu7IND0waeGj7upJxAthG14R6I4nalJc0OrLAjAkWqxCffUjdXOKVTkTYDVFHUIU9XQ5EipajhFIo2m8dy5Tm7xYYxic9DDM2Qk7+KmqprDp4FRBATmyMn7kY3wJpCxcvCkYfJBa2WwirgEtiYqRDa7alx0z5cvGgghqjGx3kOwe24nsgXgyxXES8w6amzgUqhkmRLeUiVUqAy1qvdIQRkwt4O5xrEy4rSs9jjIzdhW4xoI4uPqUTbDnQd7KOeLDspFanVYoH1e2Sty9vkbv+Ri+VhMDlRFDUuIymLYt6tCA3cHixTH07tg+RKTEU3wNCI4kIlkoPYlYVJaaouRSj+PLWlFNZyAi6Ic35Wu3apiv86kpAJy+ZBOsCka8iWUgL6sChxX6Kdc55IiPSvE4RObly14WUp+1NSoQSkGnjj44DtgdxJNwJF5McwepxscTKTdq5cBeCFOPw6zPl1OjcfSmldHgbhqV60zBMq2WDfghsgl29C4FtbGNZDkcyuOl6F4my8hr4lJHRz6+rkxjOGRijcjBBG874y9AmyPD2DZuERN4Nw9/70IZO4kUUa0YBCs7p4BVehzVKMI3FCqknwiuDMiHjOxmCBWyPG0Zx/FG4hhFaRSZRNaP18cJVhLm/Zdo5TrPz/PxdZYCj5eil+kJ4mEP1+D4E+Md6kh4dTMxk2n+oTnKO1KRI8qsV+ZeCFOPw6zlq/l4XCUkepmGBhJQCYv4Ob6KQ7S+ZBOsxFpvrLw+nm/fOCbT+OIe8VEpSsqb542sMncwLCpKRSw1Yq5rw3mbCUik0m42V5aOXrlRRHW5T4M8jmpEJrg8zISbIganTi5HNFxHyzIblArVnsCVPQOXeqhnyrIn8aiRw6vFKYlH9jjKT1Xizct2qiIO8ZexEYz5YqxQ7OS+EH28tLOY7y4lUin8zgYHQljYkcytHBDCLk+ATlVMdBFQXXYgJcSNKLrg0dR4UJ7n7VUioAzzCKoGiFgJBrrQIE9i4gJzpVE9rF4lsB5Fy7sFFXCI5tfDdJDlFdHJJgLI6DDlSR7uAshUcHXqVPDEcIgLDw+lXR0ZK2R3lRI1B5Lp+iE8BSrmCuj+6P+eEVITaQazZLIcVBPAiM+bak0cw9PTFuZZyQ/r8WjD12sZIMNz9fQYz8scPnoRK4yW5N6j5KUf3HixHCWWx2hFSmXHOs4CrEHkWWsQBucYKV1mujCNdEbO20F4gINw/OUF4JY644k6RCSYLYnFOi+8eufWeE3tkFRjfSnb2R1L1OAPkIGzEWiKU/SA4YyW6PvLw2Gt41YElurJO01Ay2GpoF4gVHHAnPVqolaV80DWWl+n5gDHLqSaVRMBcnBfTaQoAizjuygrLI87owpjGlNOGLhpann4FZ5lHstBl6Je19ia0pYwiOOXscXMocW/aOlOzL95eXw5H5OUwg/iqfTcYVOnJrgU4utA6gg6TR/X0gA1ECmNYJnam0FgTxNUoSqFCVcl+esyfPkrM26fuG7A/xoBep5f488XMFBokeAXgzH+1WS+k4QzcRLE+Bc3UEdcxeGPYBhEHIM4ejC6nQIUp5EGEAcEPr9nMLLV8BwF/9EGqhFKYRLvmeA8nl89Q0Tk4O8g8O+KBEnECx87envJAhTe2VCN5xPxBP6vj2IWL9Pr22jzwR9XTNYW8j08l0RFmMej2l4Q4ov/OQNfIOAooZSB2r0YXzJQtRc0GYy2gCPFiwYwEe/tlfAYi2XWxfB+RTELM/mmTT4e1OB4AqkEeQwf+WIqng+KhQJWsPlMPl8I0jWFUiJXbCg2ljJ4da0zly214CR484DecHzbrNLixTeD9U109l9xhbGLL5ZgwICVwfu55ng/7IhjhWS8mMI2OV+sCYN0Ckdh6TDI1WbxlDURZuvCWAkvUQeN0B0/AQ34m8FmtBpehOGPCMOWQq57Ghp7C5X5vyFZEefrRwYbAAAAAElFTkSuQmCC"
          ]
         }
        ],
        "meta": {},
        "name": "icon"
       }
      }
     ]
    },
    {
     "title": "🔵X-Ray💙: Service Map",
     "type": "nodeGraph",
     "description": "Only allowed the time period is within 24 hours.\nThis panel visualizes the service map of AWS resources, highlighting interactions and dependencies to enhance understanding of application performance and behavior.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "group": {
        "GroupARN": "arn:aws:xray:us-west-2:699881639058:group/Default",
        "GroupName": "Default",
        "InsightsConfiguration": {
         "InsightsEnabled": false,
         "NotificationsEnabled": false
        }
       },
       "region": "default"
      }
     ]
    },
    {
     "title": "🔵X-Ray🐈‍⬛: Trace List",
     "type": "table",
     "description": "Only allowed the time period is within 24 hours.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "group": {
        "GroupARN": "arn:aws:xray:us-west-2:699881639058:group/Default",
        "GroupName": "Default",
        "InsightsConfiguration": {
         "InsightsEnabled": false,
         "NotificationsEnabled": false
        }
       },
       "region": "default"
      }
     ]
    },
    {
     "title": "🔵X-Ray🌙: Response Time Root Cause Path",
     "type": "table",
     "description": "Only allowed the time period is within 24 hours.\nThis panel visualizes the response time root cause path from AWS X-Ray within a 24-hour window, aiding in quick identification of performance issues in serverless applications.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "group": {
        "GroupARN": "arn:aws:xray:us-west-2:699881639058:group/Default",
        "GroupName": "Default",
        "InsightsConfiguration": {
         "InsightsEnabled": false,
         "NotificationsEnabled": false
        }
       },
       "region": "default"
      }
     ]
    },
    {
     "type": "canvas",
     "gridPos": { "h": 2, "w": 1, "x": 3, "y": 22 },
     "targets": [
      { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
     ]
    }
   ]
  },
  {
   "title": "📑Logs: 🔴CloudTrail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "type": "volkovlabs-image-panel",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "CloudTrail",
          "type": "string",
          "values": [
           "iVBORw0KGgoAAAANSUhEUgAAAE8AAABSCAYAAAAVfInDAAABYWlDQ1BrQ0dDb2xvclNwYWNlRGlzcGxheVAzAAAokWNgYFJJLCjIYWFgYMjNKykKcndSiIiMUmB/yMAOhLwMYgwKicnFBY4BAT5AJQwwGhV8u8bACKIv64LMOiU1tUm1XsDXYqbw1YuvRJsw1aMArpTU4mQg/QeIU5MLikoYGBhTgGzl8pICELsDyBYpAjoKyJ4DYqdD2BtA7CQI+whYTUiQM5B9A8hWSM5IBJrB+API1klCEk9HYkPtBQFul8zigpzESoUAYwKuJQOUpFaUgGjn/ILKosz0jBIFR2AopSp45iXr6SgYGRiaMzCAwhyi+nMgOCwZxc4gxJrvMzDY7v////9uhJjXfgaGjUCdXDsRYhoWDAyC3AwMJ3YWJBYlgoWYgZgpLY2B4dNyBgbeSAYG4QtAPdHFacZGYHlGHicGBtZ7//9/VmNgYJ/MwPB3wv//vxf9//93MVDzHQaGA3kAFSFl7jXH0fsAAAB4ZVhJZk1NACoAAAAIAAUBEgADAAAAAQABAAABGgAFAAAAAQAAAEoBGwAFAAAAAQAAAFIBKAADAAAAAQACAACHaQAEAAAAAQAAAFoAAAAAAAAASAAAAAEAAABIAAAAAQACoAIABAAAAAEAAABPoAMABAAAAAEAAABSAAAAACYBUDYAAAAJcEhZcwAACxMAAAsTAQCanBgAAAIEaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj4zMTc8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+MzI3PC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+Cu3VVQcAACW8SURBVHgBtX0LtB5Xdd6emf+/74ekq/cDybYkGykgHNsxEC9XoWBD6jrhYVIaSEub0qR40dZtKLRNLNNAFkkTE1bAhJU2JTzqVCtNHZ51KRjC029jybFlW9eWjd7SfT/+10y/b++zz8x/77ViVuHo/rPP2Y9v77PnzMyZM/P/SiSU/3HTTdlbDx7sePvR627ZlqT1PSIJPsUloNtANyZJOga6CnrD+PS4/gq0AK+BzwI+c7CZA2MmkWQa9WnUp5MimZQkmSyKYjIRmZC0mCAtJJvuJPl0fTGZGlqzOL/14O2L4BPvRy1JceBAIocPJ/ec2QsIkf34PDBzPLlieHNxD+rVsn/dni4f95x5TG2osx8f2s3Abv9+yZMDB3IVwiJhcA+97jd21Wvp26H382mS7O3PevrraaZh50Uu7fDp5LmwnUPRS/TiDFBgADiRVBLJklTbykPbKBzjX4F/eYEPaAe4jU6HvCYwFxDbDKCmkkKmADQBwTlEfS4FLUBhdE4kP59m6WSRdKY7C/XptDM5t0fWLyb3HGhXwvmxVr++/0CNeyZlFg+/4f231ZLktwbrvdLstGWh3ZRW3unkHfQKQwMdQ/yFpgPZRL+Yb27LtDERgRuoJqcQWGLEcq+iYrxgzCYcUF3TqASM1JOcQZJ64lXHdgp9e8JJm3lbsFNbQFoE3jx2yTTAMMplJi8wyrEDEP80oGYw4mfhEkdCMY/4F9CzRUTRTDoYHxm2KEmepBg3NezMPngcRBdG4X4MqdgM/EuB19Y+PP66927O6+lzGWKeayw2W512VuR5arliz6iGUJSwf9oMXXG5alBieq6vbbUIONQzJYMzmVqHqmbQE50gbCug6C73hJmjH4TijgTVOl1bfEw+R7zvBFOCLPigMY8cUhYia82aynNdIvqRQjGPxvOtufEatVq19PWjtb707PxMa2FxsSdNU3DNkYVi0XHLcaLjDyg6/qCpvYAn7Rp0GA/7XECBAUQ5BNwRDCAJOEGZVqW+aVg3zQQWxGQ6SENUqamYTCWE1oKBzkBxxMA/nSAWbGDLOmNSqKCtOyDUjdCDc/Wogc80y2gpcwuNOsh5TR5SdR1dt9sYieytFnWFGvXB4x88qlxjgapTajEaTQyjgmNVBQZsCWntqp7h6Y6Aj2BV6pOjfqsYAGUgqm81tujA/HugVAGTMeMfR43WlFJdRbTUulJrKDrxHFctrYHjMi2Yozxpy2LRaqQFTnzwdOVCu4XkdTjkEFoo7LE22IFYNSEYJgqUdlQiDQjWNFvlmriip0aKzU20dj0iad1pQA9yGpjYGK5rfBMSlXzGpmduUL3YaRt1XPwo43kTp6oVaQcnTbUxOfcQSyN9uD53EfbEjkVcIKAQ+HRpRWvaoPOQmCgMenTs+lRCcY41zVa5QbFMtBkqO+K4vuF0YwR0GKgPpXRowK7LgEr5clmQqvMVY/EeBFzFIyYOJcWVpIHDWHYNZL1ZG1dWCjQ09WUqIVT6QqE1/4ySw6BNVNH3jpgk9AtyUwyUpsooqQG6VakHzlJbDYTuqW1/BDQEI4Hv8qqsgqcWNHW5UwoUXXEDV3n0h0Q10qRId9VxgcCkRM1LkIpxgCFAGSxahliCA6FkWc05FhtaynZK06AXadWvW5vfF7SlV/vTWBQh4Bnf5e4r+NBmxUeMYYmeAWrsVAkWTYy8ZDtlnPhSSrOyQ2qlPNbUmoQcB6EBS7CNVFkm9PAsNrSU7dRsDSLok5iS4RqbzGW2MdYYU2nrsmqsLxgLA0Ap5ZVYAlev1KbGoddMi7zYwnkwT5xWzNwdx466NHREtVB3qmIoq9gpmBHHJEs6D33FUMUAYQ64DWix5rwYk6l2+wBP2aYUZWR6rI7bjRO4bq8hKVJ3zDAKXCQvSdbb1Se32SclSxxHJxBpCGbdHUzg0VarThXOhNGtKcSgaOA26iH6Dx02poelfmNMBg2ZVdTHC+CVfkrcbpwXjt1sXY6AkrTJ6fCaNkadOffuGTjDiUFpbC4HtVi1Iw7MPmqB0NRdv4JjkmBvOKoFA7chhvvtxi7xqN3d8dLGtVbGC1L1pxpLcFzuKIZrWBqYdhHum5zXjfBmHH82pY4dN0UaeUdisGoOcPPNbrAvUc/EKwdBmYfleJFnMAQKEKbJpttQRqlpuCp4gVHGagzdVvACsNlD6LilfYxGwQNsrFNPbRJpMXmDmjzM8ch0Z8uNjGNOossyaLNEO1pGh95hDSvISwSqWUu3MFcEx4k0BG0gqhMxzKCMxX04DTZV/zEm9acAGkepGtCBEePzWKCEuysmL+nV2TWtWKhcpaFuxJ1oy9NFEy2eOKeBuQzP5eoJtu4volZ4LjPancCoj4rFwI6q1wo1huOoTUVpKW7ofYlncGFLbdPIkwTJS4q6dgaA9k/lsUPm2kzUNDg2El0tD9YDpFvFrlCtGrIioOrYStkKvGW2yqcWYQO1aEMMQFS206qemnXZlvh0qeBGFZ+qyg2+wjUVDrDshOTxBtqLxVIBoa0ZE5dAuvWgAy9wQ9A06dYLRgEi4BHN9SixPzJNfQlPuZAZVfUAW9FXTLKhFxQDXOnLGaprtlQucVHTP5M5DlFVz8RYSraRp1repRfqUFAyJxXHDh5chaDpJ3ACjc49CGVonCayiBWftrTWLSqKFKl31COu+DLNEAPkwdBDWCmmiBJ8EkJ5ThlH8K1w6oNrQNLmyGtxiYbFgaITQ1J1IqixUwUNcCYwObZ0xhJxnGHMbpyKrAxajalNNG4CXRLDSrFQWe1sa/AXiMmxVd3x3V+glFkEoJiUYItbCiQPa6FcvaIT/bhz82om6oD2Dh6osghltkqtpVjGN3lkGNO8BDxPstmbM1qFEC4cg8ek+iEWotsfuQHHKXGDXukg8lSfgaBoL4lDHzSxDQW82jJ5BVYHOPJUShszIg3gEUSF2qJQLYxF26q+tsxX4Jtv06M02ruPQHVhM5yF6cHZ6g3mihBpiGGlWKjpehGngrfUrwUVHXT5DTL6Jp9escTaxlOZZIEPWbhuqwJqUMkIlK3WHfwFgo76hhKaMQllhU6AzaX03kyS/poUNcTRwQHBD/hJH9ZpIdOFMqiWMWjDYgSGRuhUYZVT0a/GAn0Tgwa9SE0vAJoeVOhBVdwQaoy0hpzNpgmCRyvHiikHoS2d08SWo+mE50XloCfsTFyChyyseGswqhf17QwR8dRQe4dbQ0tOMd+W9jfO8xmApBcNSnbxkEgtk87xeSkenZWkJ5PsmlWSDOARcaNtMTD0EB27f8FYqOcx0wr1Cz5fASDloZPmRZ0wL5ZckiJNkLxCZrLKgxQqlOAeIg1/TAnEoGJCWFpfPiG1/Rtk7COvl9HLL5WBLRukPjKExKbSnp2XhZNnZPrBJ2TqL++V1hdOSv0N69WuaOFeEjFrTEzk37YzlyZQB4UnstI372PIQTWB0FLfTrBDkDw8ubfnoni4UXRshP0EE5jiMMzPLYqcaMmmz/2ybLr+Z6V3zagFVtn2jA4hmetl7Iq90nzLa+XU3d+RMwf+SpLVdcnWDeL9g6YkGSYL1cSg83oUOAUequgTu14ZgVG+PIFuYHYw5p6BLVD0z0OEPMdTb5nSC4YelsEJ9+ZPIIFpD0bU0Rnp2bdedt35LhndvUNjmfvhKZl85AmZOXRUWidwCCPY2qphGX75JbL6yr0yuG2jbPsljs6XyrMf/LQ0v/W81PeNSTHVkKQWEsiYYbn8EGaCmEDKqwm0vChXD2W0TVExmHHPAbNGbG4slUBKk7yGo2iCyeNHjQGkTirG8TwBUzUG6vJgYAWbGDx9BT31Ws+k/eyM9L1qq+y9/V9J37rV0piYlmOf+7Kc//3/K/n4nCTre/HpMR9zHZka/6acuGRIxv7t35Wtv3S9jOzeLpd+5D1y9Hc/LXOffEjqP7dRiolFS2CMaaUElrGUCawkkj2OCeQe0OCtj5p4bJg98kPBlTbP3n3JNa/ur/VcO7kw12m2WnilxB4sU4cJMqpb7gwUS6Dxg5yo9kcj8xEpNHl4YZTUto3K3o/dIv0bxmTm6PPy2M23y/Qf3Cu1q8ck2z0s6YY+SQbrkgz3SDrWJ9llI5KM1mX2ow/IxJHDMrDvIhnAKFz1ypfhwfMpWfzy05JdMoqXJvCWRThvL4vZArWYsA1dYi3E7FQVyz6CbaZWMVwcp0WR4mEZbs+Kv8BKMl6YgRacmxb2IP+x6EhUqi20AyVBiXLXN6a1FIcMjGRMPfKnFmXnh39VBjatk5lnj8vhf/hhaR45Kz03bJYcneenaOA1kTaOhRZe9OFnDjy06zdskdb4eTly4+/J+Ycel9pQv+y45W1Sv2qjdE7iioyEFx0Exx5w2s+LCRseg1NwrQ8cSNDXP6eMNfY86nnF+orYQuHI46rKOSyFYnBgPkU0FgdlNXgz4s6jZkVutrqNwQIAnWl/65xs+qM3y9i+y6Q5PStP/IdPSufMnNS2j0gHh13op/mPvYMPJgPtHBeHdOOgyNpMjr7tozL12FHpXbtatn/gVyT/7izPP5jK4NoHms/g+fMUMInDeaLlUDvlEUYX1tHgFyosEFb1WPccBIGp4X0ODvYzfIahR5lamanhBpjgzciLTCBdAJzJ6bvpEtn+xteq0/HPflHmPvuI1H5qrXQm8eoeI9ACX/an1FjeEbCamAmM9GLpNpHxf/cn0jg7KaN7d8qGO2+Sxl1HpXNiTjrHsEN2rZf63s1SLObS+uJpm3TXcdrgyISD0CPNLX0oR/16v8hcrme63IaS5EVNOun5VtbBvDTj1FDBOehtl6ENLs8PzL5eJCC64DyQetTn4cPkPTolmz70dqkPD8j5Q0/KyX9xUHr/3sV4o27ezoX05Sdr1G1Ca5T22hHuWXYIh3CCc2Hz+6fk2J99QXbd8nbZ8IZrZPJXHpDh1/yUrL/+1TrtSfAkvzk5LRP3HpIzv/95yacXJVvVj4S2Mb0BpgEDGrjwwVS5X48l+qWU6aCV7mfLjuAMk6Y1mWjmnTbmehgDjFDjhWqwYDvUffgamIO6lHZmYyBo4zxWf9UGWXf1y9X5c//9btBeTYLpBh/0sNSWPqM4+MDoISt96bBMfuJbMvHw49gpg7Lr9nfL9n90o/RvXCt5Gy/ZzS9I79gq2YjEXvSJm3FO7MU5tWm3ejhtEcWgQYMP5Wi95IV0aOy6odwNMIJSvHo5AdZ8jVdZpDbCBiA3inx32+XIpcSGgHsIn/YDszJ64+XSv26NTD11TCY+9NdSv36d5LPoCH05hjop41I0yEpUKEBZz4G87+VhiCPi5MGvUUlHW2t6Tsb/5H/KY+/4oDz21t+Wp//zp3FoT8jQzm2y+bfeJq2vnrF7ZaIGv+bW2+bPZUaDX8ZC/90RSbo4uYi3JGWynvFmAwdHUCKwA7HOIGkcaUXepafKplvgleTVV+KVZpSz9z6KNbBwqOIeWpNMxNARJbFd8UUFE4JCnxc87JhkXZ/MfvGwTPzgCenML8oT7/+4nP5nf456Q/JGQyZ+43/L0f/0p3rVXnMVJtq3/LS0Hj2LUYh7ZPUffGh0Hoc2ypjcbwjAYlX3wqM/ffV3b18A83wNV9sEpz3rVAlsBgHF+6HUeC4nRQgWijUku2hEhl6ySXlTDx6RdGRET/xkUNNsnUbrkk8txzVoteTJP8HdSrKqLuPv/y/y6Ds/JIv3HJWeX7gY0xycF/vqUrtuk8x/+m/k3L0/QL8yGb72ZZI/jp3Xj2lNcFyNmY40Jt+qvzKpHitjZ8FbFnjVUkt+joctznumY6gBruycqkIWcJfLIaA0QYCdyUXMzTCPGx2WvIWXAZ88KckOnO/QuSpOtSPeAaUh2uDNfKljWHsMmHznC3iv8IeTkm4bkmKmoXq8sOA1EiQqwS3f0+quf+sGackzuFDhTmagbsOHOCHmrpi0oW7oLOxMUlU2KS4RIXlySt9WRwLplDHqtgJMO3K10GlohloIAjFhbtX4OlZLNo3Izrv+tfStXWVOuVYX8NyGDOKsnEDy3Z1VVDvw1JYKnOpwNHFSbeoRT+CzPcmX6UWGLt0hL/n8B6S+E0m86xR2KC6XvThVLT2EPaaAZjEAOYAbQV/yDq61KFA4yeRleG00apGPf34Jt+kKkqMTGgRMJzjps6nTGV7HcSg1vvFD2fyRt8juf/xG6cXKCMvUM8eldfS8pKM9eqVVJjawUBy7eMBXuIjoVAhSvXz5dAL+/ILGmNSYMRCHV2HGonDQI2VSR2vSfP6stKZmpY5YNt1wrV6Bz775QTn1kbuk8/QE5oWrMWKbgrfgAURb0NA3VLSNpskCRQt3ZHhFmZVf3/mz+wZqPa/D/W2+0GxieY/uAUNiNTYVSNvKd6EFzTW61rdPycWfe5fs+dW3SK2vRyaefFae/sznZfx37sS5Dl+JqGNfca4WOkoHDhVqKqv6MC+VWEJQqh9CKHEcBbFClgxiGntsSia+97DMnz2jo7Qft4eDO7bIyGteAd5Jadw9rvfH+O6EjWLvbxkEaygE5D5JUt6R4XXG/6XJu3nnNRf31upvmmksFPMLC/j+gR/NlaDNGNvQHSUKqIubre+clK0ffavs+advVldPHfyKHL72gzL7lSOSbMJqCZKbcJoRExaQYpuxObZTCzq0NCHK8QQGqg4jTkDBKOFO4jJ+jlvB+U8ekok7vinTi8el/5ItMoBz4MjVe2X29PPS+PYxybbhC02Ltp4ZYzRnGhVRAWfJ0xFf3KVZwmFwku+r4G1vjZPDlCOUWx2yVnOOUVXQCHXJfOiXXyaXvfNNKnviM38lT7z1Nul53Rap78fqLzsRzqVUMFM75PQQCczAASt4Dz5Cq4wlyk2iTsEzdUcJfnjhwH1v7fr1Urtxi8z92SNy5Bc/LBNYYOAEe9u/vEnS1f16/yzYwQrtWBqX4XHLuChnkrBjcIVAaabNcwudluCKyzbEDMOMlLJJjiJXJEDB9EY6z0zLmr/zCqljtePMI4/LU++4XQZefxVu0DHnwl0GPUa0iEFA/Qtyb5uz6Eub0VqD74ol4JFnflagSGC+iBWa2ZZkV64VvGAiz978SZl//qQMYCq19t+8QVpfeV6SIZyT+bpdxLJYolPyVYpRmHMChPLui1+F15KzX0Mc9alZLPHoeLcBwzzrcLRha3WOJBSXZJsGZObBozJ1/pSc/tr90j62gDkdHo+0eZIPmqRoBFP6IIBhkDJOyk09YodQgp17XIKjpmpJ6wqO4zmFDDGlQzgXHpmR1nBL1rx6n9RWD8vENx7EOQ/nYyza8igpY3GfiquHLV0gxV/UkVfvq03iTakZfi2I33a50F73vUIAHU/BEXaZnHr/l2Xm7scl24m5HU7AvCjawICmGdpepW0YMTqmIHPcoKbY6sP1uuwdz/FLPNrQWTdeaFPEkcWdtKVXZv/PYTxkOiu8iPRft1vaD+JOldMe9qkLQ9GUp/jYAMWuDJf+9ABmjnKujoHIqZ51zAwsdnduQQcoLF5ikXMKC5nTPCTaUrucjwhrkp/F9+DmkLwZ8CtB5LOYi+HQySmDfo66Uqx2sChu1A9t8i0I9ke1QmRlOwTketRi6cbzPlAACS4knSNTMo+FWZa+XVskP40lMk5ZIO62tTZ59MGjAfc3We1A/Nbj+zR5GHkwRCf1LtwU6SvOvXh04MTa/P5x2fOl98q2a6+W1twCoHQQMw4tdMA7i0du+4RM3/GQDL5tt7zid98j9cEBwVc+NAAqpvW6TD5+VA5d/QG9wBRYNIjPQeC4a/4GzK5YEKktKzktOxcUNQldeBaeJqk409alK7LqY7h1FN+JYX4HftXWzikGgGX4rLYHX+S1ppzhanKGL6c1m1j10LNhGUwZtJ4OMGyb0rdmlfQgGfy8UEn7cRKGLu83BzesQ7J0Xt6lzodBxNO9DkmcAyMynSjzMCMfH6W6M73tiXNaxrxyAkvXukDKjrHwkNN/1tQRRu+MIexEavLDYcI5cm2dfgP6INm4y8CXinGXoUqaLQar4RuFQFtY1a3v2SxH7jgox+76mt4a8TaJHTMLEmji/DL/0DNS27dOGkfPyL3//nZJ8TaAnZCpAhsE3Z6ck/rlG2y6wGBpq0iGg233CGQUiK/U88Q5pQGDBVigioc6x5TyeF5bhbuqgX7CSxtLWpYWYvjIA0X2PIEAxB+RkOhOXovDIC+S07yzQPLU2B3rrRcB6DZ0ioucMp/L7Kcew9ew8eiPZwBGgG2VJoInYPsw+cS5sTM+iyvat1Wego8e4AMc0BTfts/24EE2Xr2IOwG+2HdFZJ2abPNZBa6I2mZM+KeJwbZ6CFOBI8b7Qep6lPFhU7pjQJ/GAVoWj53GFkdJWHBlgq2/lQSqD4OETBfxaAu8/DR3Br8SxESxU+oMm+q9a/O+E3LpnTfLJT//c4Iv50KfyTZANVAwRAewh3/nj2Xmv/5ArrrvQ7ogSl5jZlbuf+OtMnTNTtl366+ZCQEuVNgR7FR2ZvzOL8mpd/8FlvJ36DPbAgP5RSfQYwPNzzRk8KaXydBFW/Xed/67T0r2SjzGxHzQSzm6w07ShEDKHZPinOc/SoC4TuPyy4ky86YJYUXN2FYD7r0F6cMSd+/wkH7c0Uo07cMS1FRHhjfioQxm8yx1HCY5HimmOAf2j61eyeyCvDreJOhgtCNQhsl+oKAWR5a20DSpxk0VKvKihuWoztEp/fWCre+8gRIs5/+NLNx1RPreshtLVrj44RTkAyImkDtQfYRE5gkPW57vOFDSs/z+GUaSjjwbd/QZEohRwwcodVzSxz/1BTn5zQdwNeVX+rnfmVndKhaq2oPZB56W9PIhuf/AH0k6gCdf3AlNJA6rK3OPPCv3/eYfgkGmdV4T4XiA0LYiEh74+Cw+eUJ6rtiK6RF+OANLThohiNsG9QofPaAcLvJzC9L56vPSs3+bXPSn/0RGL7tIGuen5PgdX5DaVeu1f1DTOHV2AUP2pZJApkN9IRs4bPfuLeTgQUk7nclGZrdoMIDM9lnYgqEoek6a+cwh/NTEd3GuGtTzFZfbC5y/ynMfHeD8ObhK0jU1mfyD+xAR5oTh/Ji9ZBXOgfNy5u6jsK/hw3MgC8c+3j8BR5MBju0S21IjG4PPDb3SmcHUlHMyFHZQNUnRCFyjGGy4lcLOq0vvFdtk9XtvlA2vfSXWGVdLZ6Eh4x8/KI0/f0Z63oh5Hl/dCJi2Py0NlkDzAw6dsdRqtx3QCn6qocDPbxRYj8qwyK9jgUSvNowi6U2lef8J2fXf/rns/oXrdG8cvfubcvgfvEeu+upnZPPP7JMm5nvligzM4bXTaMpD7/sont/OyZV3vE9qA306/+OhkfVgjodlqx/8zG9LetmAbLj5tbL7Hb+IcylwePpYVhAIe6UdsBQtU1nCoBY7jImF9K7C6xthPjr33EkZ/9hBmf3w/Vi+3yQdHq46kk2fu6A7gUykgRMT8qx2q9xaHJAD0moWMz01WcCzjB41hEOnqorO5vhtmf61a6QPQbDw3Mel7cF1Yxc8ByYAZgdGtmzUkavGYTOwAQ+/Bc+gTmS6YNmL9/P4+UmUNkba3HMn5OxfPyjnPv41PfRrN2zQRwaaVCSHcXad28DrPoQRmQ51HrYcVij1Hvy+SFHMYaqC3w/BijIOW73K6h7gqgTOdzu2yvhnvySn73sUFoXMP31ChnreJIc/9jl5eguemeKOIp4DoaFB4G6Czy/wYy3yvd+8HTfeeBmVl3W6xehqn5+R2p71+kDn9Oe/I3PjP8SCApbIlx5+UPdCXBbbOq3wUK20tJ7PNqT51Glp/iVvx9CX16yV2lpc0Hju5GjEsFp2N8NE4l8cgazjnxWMU00sTL+OH2rYMNA4nBXJ7sPPjeMNjBzTPouCALTRd+FOLkrn1IyCZmuHJNs+KJ1DeF+kgWGvtyXmkA5ox/NX7eXcH3ie8PAU2nTOcxop5FgGyvbgbVA0eS+cP87bbDtkPQHqX7UNE1VakhhlommC85VyOX1hXe+SQBn7aty34y2sdBQLs7wFxco2+dxJWojBilOtVnyYKMeRmQ719slCq/WxYEkrEfyqz0O9afqKQ8+Nd/ATGLjuhvMOtBQazlJOUPGsQksLDDxISfAghYmNrgJqCEdHHXOV6os3kYs4ochJaRMrzIDUuRxXnA3d5Khb/5bYKT96ZIClf9p7EpSPDYcPB3QY9YrmMlAt0WYFX+YAyUvT4d5+mW83P4HDloNKByw2xTwTBgxencHFBkY6KrBhZ/k6Q6LPIdSdBslDks9LVZvGtGK8tI1qsOW7IvhnV/BSLyjbUhB0uuWlnuOtLA968OeHn+LSvwZhsUQMRgcgPTUZIAw9E4ESCzz2GxzTZ+eUz5kmy4HbFB56ixw/2kFmTwvNULAJNaVRbFLLNtWCwIhbkK9ghlHFcnD1sbKvICK6eaN99GPA3lYvkJHrvO5YIDOT7lgCj0KtOq3imERdYKDZdfugr6zg9oFZ1sOJ0EAxRw6odrohx2TskpUyWON02XbpE5h/3XoGXPrSGvWCo268lf0SUVGhrPUVbSFTpRAD6u6rOwbDIC/GAE0baTxRVQpUG5Y8KqsJzWK9DMY8E9r1jFNx8qMETS/RnzW8SR8sMfggMOLSqtz0g9EL28bYYUsf+tdtqy0E5lz8IpCfhXheCjNGdcE2vsSHup8dtEOG0NW5akcJ7e3SidVW7HDUXx6043jHg2tarJiELj00Sn9uYT5oXcpo5XKPPXCg6HrUYscsBqOML8oLXDuocxM3KBDaiySeX1AzVinlpVsVqJnyKCulxDKFklblS4KuWDoOtekwwJZ+jUNXkRf11MT8Rh6bP2osQZ8hlDiGG9CXjzw/htlhfiyHZQdCxDFoT4z6IFeRg776DQ5DMN1y12d8HpjrGyK3ZfD0Djn/oG+agRf0VF9NgryqF+rRlwI4DmgALOXuoYzBtc1POGxtXUXjsqnLEqAYIvgqUmpK5szqqhcUIidEVQZF1x7GCkGHtJhZQAkdpyhakufiaONe1YVx3VbdmvxFx+IO3Jb+Aw/euy8Y0OmhUD/q30NVaw8xBFXtCOVs29bwS9vo0B2rosvpTw2rgQUkw7NG0GcHgietua17dx9s2x9ol0WAM0NTdzmo4zmOM2BFkWviqLQLxk1clmLBGhOnunw7Pmh2OVZT1QwQqDtYTJACeRAuXUGvihNR6M5CUUvFJ6DxYhKUX/Hh4qC3IgZwVU1tNcjSVxAYjONWYvEEkpoSY/JJ8q1uN8TflMKiqF5w3SYGrT4dvBpMMA8GDmbNC+ipossdtxI0I7W/H3MCg0+ieszVWODU++5yMvQaQIbq2jmP0+KCv1oL6Sh/zjfn20xaCKKa9BJ4JA4ecCAKtahv2i9CTxWjdXTjflWi+OZXg/D4g18LzX2tFIsBmKvgyzHYm9C3QCw3sY8mp23U0yBwe6aAaHz/++eG0Bjjz/y2O2HkmVJp5OjK92A9mJWCpuKL0LNeLQvaM6keoGOxhoi988qv+HCxa3ti2LY/UI85UEbpek67+qgmyrGYMAoT3tseOKCjcaA1uBY31Ksb+O3QPMcPr2oQ3eBkuZOAZFhQVnXKQ831jB+5JgUzcjxYVYxc1TNWBUHt6Nl4dG46hmdQ4Lk46JWxGIDZuK37BEaMxQB8W8Ulzz64PfP72jzLtw9k9TqSx99wxJIXc4pPIEy1ZhlUC0XkGdNkUWAq3kkNwiKBwIOONed07whE7IF6NpQDZoSim6BHpuqrEJpBKRC0rdaFEW3Nl8EFvaiv3IAHGf8gwyJTLb4xgPfD9/ZmdZlbXMibjZY+DaWFLRJYoghjqWPmvG7crkRSpsnWCp5jhyUdGBmfAUIWSNgtBOou7IDagsQ6AyduMKYFZLoMpZRt+mECA6VfVbP+MFXVNwFK2yV6wGO85olbfUSlnlEt3xjAtwqu5PluuH+gs3PHdqyX2uIUvcIRURm+BaqEwRmHV2j+mFfXz+biK/f8wQd80G9Of4yiwm7puqSGCgigo6BFX7rBrEmZ4FGuRwEo3amuhgHdCoMQLIHF0P5/EhiBKqljX7D2jpcK9Bff7HHR8b9/YGCitXh8rHdwtFHgVyYQOJ2zk4zFS4ib3VSWjSL2J3QcVG1oqwmzpPKVXX74I4f8oi+fD+sHa/364/PIrPP4W8ZMOviadDQBymBRGBRTHAJxvzGjFOnHY4Ki/ll8xtXQVY813Vmk1nBotqItmchJkWW1Tl9Pj4z1DdWmmgvP6O3YRHMKi/u9/3GiMT+TJ505TPMWECi+5Jq28GNdyDe+08zlGD4QR/KxUF7DS2i96FUvRmUfBuYAxukAJtdDWKXGSycyDBme8yUj6O4IZHgcVgwjiOF6rYZ31KUP3entzWppDSvX3Fk20jzpSB4TziSD4gf+y4Tjl/6Ra+QX03n8UUcTzh3GkY7vYHOPY+ehy/ywcNQzgdi1zH+1sA3/TJAaYnwzUZjFgeKdCtxH8BuhPVktG8JboHwBdKI5fwiYv849StOlkFX4H0ud/9/GxYurewfnx/qbWWsEZ4XhjmQjWZ6vwmE5hgE2hodPa3CXg19ewCdBHf/vBoIbQYdHMULwTVt8/Rgv0/SgAzypMOH8x8I7o3B6sMRXkh/+YwXV02PJe6sJI9swiMevkTFBfO2kZr83oztvrt3k/+nxvSRPP/XSV/V+lv+Tg1nBGk/P9FkTofz9Fdat+NKBL16JVP+jDersN0Xd3hPqirP3sQLTIR0GFZUXXb3/infVF/tW9fUNNYd6imwU71GP4OftR9HR1Uj4GpwO+cLLagyWVTgC+HUj/EcnGPGacMFjOYz6ohhE8nFN/NtK0YTdJLTwDT85DrtjSPYRJOwRyToP7/3S7+EZqhU+bfx/GaONhuknHdkAAAAASUVORK5CYII="
          ]
         }
        ],
        "meta": {},
        "name": "icon"
       }
      }
     ]
    },
    {
     "title": "🔴CloudTrail🧣: Last ${limit} Activities🆕🔽 (Without AssumeRole/AssumedRole and CloudTrail as invokedBy)",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expression": "filter userIdentity.type not like /AssumedRole/\n| filter eventName not like /AssumeRole/\n| filter userIdentity.invokedBy not like /cloudtrail.amazonaws.com/\n| fields @timestamp, @logStream, @message, eventVersion, userIdentity.type, coalesce(userIdentity.invokedBy, userIdentity.principalId, userIdentity.accountId) as InvokedBy, eventTime, eventSource, eventName, eventType, awsRegion, sourceIPAddress, userAgent, errorCode, errorMessage, eventID, @requestParameters, additionalEventData, requestID, readOnly, eventType, apiVersion, managementEvent, recipientAccountId, recipientAccountId.serviceEventDetails.serviceAccountId, eventCategory, tlsDetails.tlsVersion, tlsDetails.cipherSuite, tlsDetails.clientProvidedHostHeader\n| sort @timestamp desc\n| limit ${limit}",
       "id": "A",
       "logGroups": [
        { "arn": "$cloud_trail_log_groups", "name": "$cloud_trail_log_groups" }
       ],
       "queryMode": "Logs",
       "region": "default"
      }
     ]
    },
    {
     "title": "🔴CloudTrail💃: Last ${limit} Assumed Role",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expression": "filter eventType like /AwsApiCall/ and userIdentity.type like /AssumedRole/ or eventName like /AssumeRole/\n| fields @timestamp, @logStream, @message, eventVersion, userIdentity.type, userIdentity.invokedBy, userIdentity.principalId, userIdentity.accountId, userIdentity.accessKeyId, userIdentity.sessionContext.sessionIssuer.type, userIdentity.sessionContext.sessionIssuer.principalId, userIdentity.sessionContext.sessionIssuer.accountId, userIdentity.sessionContext.sessionIssuer.userName, userIdentity.attributes.creationDate, userIdentity.attributes.mfaAuthenticated, responseElements.assumedRoleUser.assumedRoleId, coalesce(userIdentity.sessionContext.sessionIssuer.principalId, userIdentity.principalId, userIdentity.invokedBy) as InvokedBy, coalesce(userIdentity.sessionContext.sessionIssuer.arn, responseElements.assumedRoleUser.arn) as AssumedRoleSessionPrincipal, eventTime, eventSource, eventName, awsRegion, sourceIPAddress, userAgent, errorCode, errorMessage, requestParameters.queryId, requestParameters.dryRun, responseElements, requestID, eventID, readOnly, eventType, apiVersion, managementEvent, recipientAccountId, eventCategory, tlsDetails.tlsVersion, tlsDetails.cipherSuite, tlsDetails.clientProvidedHostHeader\n| sort @timestamp desc\n| limit ${limit}\n",
       "logGroups": [
        { "arn": "$cloud_trail_log_groups", "name": "$cloud_trail_log_groups" }
       ],
       "queryMode": "Logs",
       "region": "us-west-2",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}