{
 "title": "AWS Serverless Overview",
 "description": "Provides a high-level view of key metrics and health indicators across your AWS serverless components based on CloudWatch.",
 "tags": [
  "AWS",
  "CloudWatch",
  "Observability"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cloudwatch", "label": "🔴CW Data source", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "🌐Region",
    "query": {}
   },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" },
   { "name": "refresh_interval", "label": "🔄Refresh interval", "query": "off,1m,3m,5m,15m,30m,1h" },
   {
    "name": "account_ids",
    "label": "🔴🟠🔴Account IDs",
    "query": {}
   },
   {
    "name": "api_gtwy_log_group",
    "label": "🔴Log Group(CW)",
    "query": {}
   },
   {
    "name": "api_name",
    "label": "🔴API Name",
    "query": {}
   },
   {
    "name": "lambda_function_name",
    "label": "🟠Function Name",
    "query": {}
   },
   {
    "name": "dynamodb_table_name",
    "label": "🔵Table Name",
    "query": {}
   },
   {
    "name": "dynamodb_operation_name",
    "label": "🔵Table Operation",
    "query": {}
   },
   {
    "name": "eventbus_name",
    "label": "🔴EventBus Name",
    "query": {}
   },
   {
    "name": "rule_name",
    "label": "🔴Rule Name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "❤️‍🩹Performance: 🔴API-Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "volkovlabs-image-panel",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "API-Gateway",
          "type": "string",
          "values": [
           "iVBORw0KGgoAAAANSUhEUgAAAFAAAABSCAYAAADD2VOmAAABYWlDQ1BrQ0dDb2xvclNwYWNlRGlzcGxheVAzAAAokWNgYFJJLCjIYWFgYMjNKykKcndSiIiMUmB/yMAOhLwMYgwKicnFBY4BAT5AJQwwGhV8u8bACKIv64LMOiU1tUm1XsDXYqbw1YuvRJsw1aMArpTU4mQg/QeIU5MLikoYGBhTgGzl8pICELsDyBYpAjoKyJ4DYqdD2BtA7CQI+whYTUiQM5B9A8hWSM5IBJrB+API1klCEk9HYkPtBQFul8zigpzESoUAYwKuJQOUpFaUgGjn/ILKosz0jBIFR2AopSp45iXr6SgYGRiaMzCAwhyi+nMgOCwZxc4gxJrvMzDY7v////9uhJjXfgaGjUCdXDsRYhoWDAyC3AwMJ3YWJBYlgoWYgZgpLY2B4dNyBgbeSAYG4QtAPdHFacZGYHlGHicGBtZ7//9/VmNgYJ/MwPB3wv//vxf9//93MVDzHQaGA3kAFSFl7jXH0fsAAAB4ZVhJZk1NACoAAAAIAAUBEgADAAAAAQABAAABGgAFAAAAAQAAAEoBGwAFAAAAAQAAAFIBKAADAAAAAQACAACHaQAEAAAAAQAAAFoAAAAAAAAASAAAAAEAAABIAAAAAQACoAIABAAAAAEAAABQoAMABAAAAAEAAABSAAAAAPfS+p4AAAAJcEhZcwAACxMAAAsTAQCanBgAAAIEaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj40MDI8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+NDExPC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+Cvh0/TIAACwDSURBVHgBpX0JmF5Xed53/2V2zSpZu2RJXiV5k2y8yDaGUIMBG+xUFExpiMPSJA15TCkECEVJTUnzNA2hpAUa9iUBsXnBJmBjgzGWsWVjY3mTLNmWLMkazWhmNNu/3r7v+51z7z+S/NA+OfP/95zznW8/6z333H8SQ9j5ux9bV0qLf50kNtVs2jTiWYBn0jSdtiSZSpvNqcRsspkUPE5tstBk3qaLxdpUY6Y53Sg3ZidfHJs9f/vna+T5LwmpWWJbtiS2Y22yffedhc7VSyD++LAWoCeOBwvycmVrBxan9syBdOuCHenmrVthgkHcbw/7rv2vQ5VmfUmhkK4G9hmJpevTxE6VYnuu3fJnJ88b+uRoZcpKhaIVBAVK4J1CBNONtGl1eJhxrdlgaQXwChKzdHSSplOATUHABOIJsJlAeryJb8FsrJkiX0jGk2ZjIimUJhqomCIqo16uTDUqqIBFa2bP//x7/8UV8NvdMRfjoau3dA0m1XlJuW0gTQoLLG0uTlJbAqyVqMoVsG857Flmabqgq9RWKsNHPeV22z89fkiu2n3dllt6Su1XHxgbOVpvNNoLSQF8En4oCXGBF4aCR0lSLBSsCHhBceJp4BOXdMCFbA8QrtBETdD5WUVYSmdVoVgFuNPAm0Z+Bukp1O4kFGeFTDMPuMpSS2bAeBawKvjVUNl1sG0iRj2ZoZIoHvWVFJEpA68NzawDgHbw7Ea+B3y7gdwHWF/T0l5o2gtSfrthU3sbHFSCXbAaqOQJvcGegpBPwX8maVpXtVG/p7Rj85aeQjM5u4EWNT1b6UwbzRKs5ycLcAb5KMCHTMPB5EWHoYz4/AMN87QAmeh4wJjzS7iyJohb5heY3VB2kHTxS3waILog+0RRphiMywJlZRlPtJSivugIeN0dogqNaTgU3aqZ1pppE2zgLDSOIm0uUlG1oGazWS41WIP1iVJb1VYkZVs+WUVPbKIiYRgdA7qW2B3gqnhhKHZQUIh0DTQB8GaSiF6OCLUdHM2yBI2BkZDgNCioJB0IPFISwSJcyM4t4LE00iid5SXIcQOMEStDIaOHdKaDofCM2JWQ1x/rT4qQSkRQjE432AgPkmNih9lSV6P7Fl6anoHtKbsoCICFTx4cxqsso8MoiGhsgBQQA5LKK3Z8lrq6jhSUDhToeym5uUiwVoo4qA6kEbMwi8ULOYIClSNAHzYZwskECX0I8CwBGS+HZle2SspkTHqo5DIyDFF7jvYjhegw/NVcxUERY18DxJAmC7JrzJGv0kwwBCYEkh2hEs6Yfyx3oGLPO63wROd8cCXRcSGCApXzC6iEiWeISRzlkleU5ziuy3GwyCPYxHLxUURuHvLYC9AK6WLqM4xZubCcvoYDM+KcFKDAVOqBniyiIJY5S5IqlZcR5EJa4pw2ynD6yCdCj8EDkquBchJQrotD7IkYS2pWCFQBGEc8Alr4eTaUEt6KF+VEuSTkp5lwzESDPcyOvAjjJft1YOVIRHNWOVPBcqDjg5FAYuyFmRLCOEYJss+UDPjEy/gcLzdCnCzLkUThWH7OLiv87fo5wXH2ZvLEyuXyCnclXM6h+45gvZLOR981jItYxslFMjAjdh3nwoSHAkdqMd7pWw1wMyA0KhFo5hjdws/RXNm5fCInl5vzIxZVcCaRr2DRJSgTR6EEPsJv0cuZRArnJ77OyQuIT/o0qafosWkyyjm3j62vyemFWM5faeECkIGylAsW3JFAF/DEwimiMcwxLWgR659Ak8WBr8ojXowDLSJgAcM/nnMCivZQ9AkDqxDPC7c1LTLnw2RepAJlTyQ38CE+vxzy0OhqtbQ5Dgcm8+q8q9AEIv2oY2DujiKUMIZotDDJ0IEqI5Hncwripw2MF51YXnaUuFQyrFIzPpFfFgd+ka/iFrmSAKDDozzkuP4h7/aiGeU0kJbFuS4vp19mHBLiG+1olesCOUNrokd21pql8RIS3erCWDcSR/2YhJzvAeA6WVO65h2f2t1YlANGSEYnGuAjJjPiYalsSU/Z6rvGLH1ixoqnd1nSh1VUfzsM5kDsS4c5MfWQMeQT+AVjhIeyuGTBaG4pK+RoxewoGsKBWSss77Diyj7caKKb1eFIOjfo6u4M+kX96WhI9A/4IXEiubECqAOQpotJ/Si7cDsnEdyp0BLA5bf8SkfwL8Yo8UBMlHmB6AKSF8OopKtszfGKVW55ztrOX2qrfnmjnX7HR63tvKXWHJ7BTVbR6SOfObEyGV+XFuSxiCWUjW6bjlWsdMZCW/7t99ui77zHSmctstrW/dachFPR8onDEHUN1IycT8ZPoJhDxv0RaakDecAyOvvoyWWbLmE6ZhsRIyIwxY9SsdZUQDgJyRQ1FJjFFqE7UdRMoQsKo7Dx0rQ1H56wjrestmWfeLuddNlGK7a3kbF1bVxjM597wgor5qmViD1o1GJbWyRws5ZAY1A2Ry7qPenALe/OSet4xyrrOnmJvr3nrbWxtz5iR776U6v/ZJ8VzuixwlCn06JVwgTemrgdMiu26BjThGBni1zqzqasmw1sgiRbt1Rx5yKNVSaPq4d7loJi0wefl+/O7CVobRzj6rvHrbljwjrffrqddNPbbOEVF1ips0PdtT4zG9K846TH9HFlIRea/L87ESrGaqdjNf4B1pjGMNHVaYOvusD6Ljrbxu592Ma/c5/Vf/yCFVZ3WWExKq2Krs0vnchKiXZCh9g81FZiTk4Ec+Ax6C49sXGmeb9H19B3sZxwZMiKMT9KZTjEFZQJDAIczxqHp61y67PWds4iW3n7H9n6z37Qll51mRw2/vQe2/GBT9nk7r0ktLQO5RmLL64ZP4GRj/JCLOSozzFx4BN5Tu/eZ3s+9nmbfPo5K3a229CVF9vKv/1jG/r826x4ypDVvrnPmhPY7uxBb+AABllBfNAn6AVglB7LpR2UExm26Jgvwft1dosMPSjP5pB3H5QCUR2I5WwqWI4kGMOaY7NW/dle67zmNFt+0/W2EF21PK9bHMee2m0Hb/mZjX/pAas+9Ywte/c1gru0qF5oSWqBdOb/T0uk8c4nYwzrpm661yo/ftq6r7/ABl53kfWcfrIc2XfxOTb+u4/a+Nfvsfqt+6y4aQBrkHY0W3DhSgGsZCdbIu1VHPRz61W5HPLQ8tyBwKmFQRG+BRGdIwvB9FgnQllsBGpgbhyescbDR6zj9Stt2c1/YotfdWHmuPGdz9v+795l45/5paUvVq38xoVWHl2V2RhNVl3h4mMbYjkvxjAm6JPF4NDSyVCOPI3mTJw5EttPmxZaclKXTX5hm0199Vdw5EYbfNPl1n3Kcht67cXWtwmOfBu69td/Zo1fHbLCab1W6IMja5xMI9MTOJGyaAX8Akx3ILKzRQBYEL/EYchboKtH56W1htXuPWDtV660pVuvs6WvvdTaQoubQBd98fs/tdEP3KnlS+ly1PB6rMvAuHmI+6F5cI6BL8CULef8NicCkXUs5wW6OYqjoHmoYoUFXVY8o1+T1NRXHrSpLz1kPe+9yAavvhQTzVIbev2l1nfZBhv76a/s6LcwRm4ftuKZfWog5M2a8RYYY+rHwEKNfWOMS0Ce5a4yWh5K+HEEaslU5kR0DQ7U3Ddb8a1329IrN1l7PwZkhPFnX7ADt99rh2/8MbpCxdpes5j8LMVAnVZrVugukxO+gTeJEGLuuBb2W53oPYXud6d7RThXXNFJtJDWYhrZU7EmRJj8H/fa1BcesHn/fpP1X3mhda1eZvPfdIX1XXG+jd/9kE18+R61Zu2JQrm8G+dOlE/ACw01jIHYKmcLZHDPIw4ZOQFpOtHaMMPefcgW/PerbPVbXkcMm9izz/bdfLeNfuoeazw/YW2vXmyF9rKlE9ilB0tXhJoQO8aelskEgbfkxBjFcjXK8kX8CfCIL3qyRiIEpmJOMctm6yotvmKBZt+Jm+62yX980Hreer4NvGGTda5YbPPffIXV9h+2yU//wkob8VhkuuZ6gVvWEskF7KhzEc92mGVdTfE5hlogCrwuXQUiMsQr95oLnb6WG92x0x5e/QEbvvGHlmDl3/Z6PHvBQNwYn7UUXOkFkpM2fsmrNcR24/yJ56k8JnbMIRX1CQSxJIBz1gCoLAhmZcJALKxRsWg6xUtPsqS/bEc/e5/tveKvbAozNkOhG+PgEawQ2KBAK76MlfE8sgkfp2Hv4KhogAQHan4lWhZy5ZwTmaEurFnz2mxUoIzVrfx6PLzCXQdnY902adWfUZMIgRclxF+KcRjm4C/GiDl4azYEXNgxzxjrxkDOSlKe+PygIJ1geUAgbUhSC/7xowvsJH0KR+JpmBXPGrLmSE3DjDCwvEo52ogBiUQtUnECnHXhe4GJHMiF9ARbIJ9LSJkg3CuBBBxl2KCcoWqHec7GhmUMmrphYsm7u+QhT5EUhxikUgA5hqRUtGRlpxWwFmtU6lgX4vaou00TD/2azqD70I+4h5YcOgtyyK8QYXTqFPAwNidndIAWk1UWXCale2AeOU4MtIQFXIvy2V4f6OBMBRoNXWQpLhwieHEqR0EOt9/YvcLdNyG8lYMDwRaKiNIvEnisE8kvBncKrXRoFMNK8DENsqVBpMjj2uiEzT7/oKXPn2XFjb2W4DarevtBcMJzfCtb+bKF2lWp37ofsApg7VZ+NcYv8K7e/CIYYWKyTiu9br6cXX3sKauPnJcJoG7UyyNcaQhy2VgGkC+dAK622EACJwqJ4BM6Ma8AbaYiq2UFblxN0zFnYop04W58tqiVcGCKuyRkaeEDJBUhSDUMYGyRTkXOxPBwEtZi884+1YodbTb8g3tt5mtP26KvbbbOZSdZfWrGhr/+U0xK47b4O++wtqE+q40dteHP/bMVOsq28OZ3Wqmvx6oHR2z4v9xqHa882Zbd8lHrAK0CncWhAZlYf0ojLy1guXwR8txHyQMwwtBABhoWwI6OV0tEjEaBzdQUe1cN7IZwGWM2yoQcSEkSTWIheyyoK0WMGISujFSTwvGORS2RTos10uLA+RvXRxY2+dQem5j4iS256nJrh7MYjty13eqPDNuya16ddc3DX7kTi91OW3LNq4RTn5y2g2/9qpXfcYEtvvoKwXShSI6TCFG/bCkWoXQI3UmE4GwVEQqHEswvsTyBnGgwP6K7gqSKqcgdiOnkCM0HnA01s1e56ESwEjOWk2lLEARApwaeZOUtkah0ZnhaLMqRR5+y2eER7c7M7HzRSrbUDtz5SywnFlpjcsbqL2GFgFnyxR/93Nrm96sFNrm3NzFjB36EZUY/WuCBw1Y4vd+q+w7bwR/fZx2L51v/WadTmCz3CpRw766C+0gevCKbWlugbGMLpJXEZxItOpAiwz0/bAxjKm1Ly6EFJs0jdXDB03f2Yadxue4UOhFQ8jrWfdF5KAp6AwKBrU5UgWjzvnLwjl/YoQ//b2uzdVbc0G3F3xm0A2/9J/DnqY0ylhlDlnQXbd81XwZlFbA2K716yBpYz+276h+AV7dCb4eVLhqw2q5D9vxr/9KGPvlv5MBoNwiDTkqBhk0TVlA/BxHDWyuNC0EtMPhBIND4mK6Y7ZDk1aliDZuNnESa6SifMOFMCBohsNF3yS+fCCgGeRaRoiUQImgUgrKsu1AJcXL6FjKMYd3W1r3e2q5cbM0jM7pjKV4Jp2Fml/MxM7Nrla7Cei1OblwMI116AyYYzrxcjszUsRnQZuU1q6wInlmgbOoEgHTGJe8h0hiAUJjXq5OH7u+URAq82BLxxwkXE3WlWOHyAw7E04Ox2UbNSkUu4LR4EJUUIBEUoTApIhYkOz5kCrOG6WzFAY/5wIEQ3mY1p6rWrGBpgrQqi10US1S3zOlSOE1V7sJlcxMwsAY3b0mUmz7nfJzKDWZaqusSuyG1CC1QyMiryzolS/WwjTFl6gJ8eiS4gboiVNonuuTAQqXanADedLmonWSgBW1FH9JzIs/wKoFIMGbQFcxaYxmo0lbOTOejdVSWxghfADJ0voZ76QQPi1hGmM+UlMM8PmyNQYYAZB0AjESXsXPcQJ1RKUFktsBA64XAFMgp0EdYXjl5wVp3YDPtwFm+dLJcxOKWfViScw4kY8jgeZHzZ7k+Ac+RI1XAIUpOGNOMPY0y3M04aeDDloGumqJlVm/ba7UHsVjg8w/qx4dIgTPjyC+AMl3FPXjS9acdkiKdlZrjfIDRCcQTiJEmIhOk3oIxMNn6FnYXK2DnZxoUY21ogRoEQZ0JibIc4IwJC0EKIp3p1IJHJsxSiVyRSEkaFoY8N2Zx98GHTAKDhs86GnuOWscFK+20Bz5i/R+8DLddOMeJh0Qpxkg+7XPyyCTGrpByARTl57GLVr5lDBQ6K46KOxvXn2nagZgdGF/cCyokhVfdswVa2REeMMKADbxArMjTRA1QJzvu6syFF+mPwckxUABm5CdZ6JqNFyehQsHq2KDFHrmXo/U190xZ/+Xn2PxXnGULr9pkjUcmrLEfZy2xh944OOXdmt1evFyg0sEJc+BBLwh1xGgRcUOaBTEn3TJUT7D9cwTFMKgZmJLVbzCmjOrEabEoBwaVgqzAEoIjv6AB8vjL4Hm5hFMZloEop/NUvBZ6261y1x4b+P1Nds73t1j/f9xk9Z24xUTr4w1/4ex+G7rAF92HfrINo+aU9V7/Clv33T+3vrdfZJUfvYBnzm3gj2bEphFDlEnhlO4CM13n6NXSAh0x0IiX689ktENdGAtpwv5iy19gF4GFOGUkB4bbOcF4geSog7LMe2LuNdMxL49OlFJg4iXRSnTRgU6b/d4+G/zY6+z0911vnQuHrG/DmdbYd9Sf7j1x1HquOcu6ly2y2ZExO3rn4/BRh/Wec6pw1/wHrPv+86us+uP92DDtcAuDVpIddHLDMwXlxEx56iUDHULbsi9JmKHmIWYuWCAHfhz5OHIPs2kWC0X2YeKJk6fcdGcdCoQg1nKMMEAXBeUUniKfPIUMJqzKkcds4GObbN1H34V74nZ7aduj9vyfflkbCdzJbo5O29Brzpekke07rHrHASu/bontvfFrNvzAY6I57SM3WO+NaIk7d6Lr57sx1EPypFCUjDiYxgTtjNlgjqIcyhT+hOQxadQC8Rwp0ngLtGSYgCLWgtzrIhGJwwclyikmHoMLd5w5eF7g5UxLgwxbtI3pWev//Wtt7Ydu0O3c8MNP2DNX/S22r+AEbEtxU7Z8xRIbwgNyhtGfPYIyqEon4TT1s1f/nY2Ahg/qT/vg71nve6/E82C+mRHDXHnUIULctoiXW5ZDqHLEJxRpEWsFyWUpW6EcuHXHDu/CzWbjMPa3sKqO6wRnoCuIA31QIogKcJZleAExCvQyp3eOTsv73dU3vtVKaHmT+w7aExs/gRcKcF5mfhccWLDatmEb2HyhtfX26LHB5D89ilu+Ph3VKAxiH/GUTtu58b/ZFGjZepf90bXWnM0ahQyWKtStJeFJXPmhk/iV/q6Xp3nNg+eI63awBEnfVUZaLRDLv8N87wPjIF7b4H0EsTJSUcwVJQQizcXLyFygyiMq4xAK2Mbaf9vPlevBGHfyre+2xqNjLU5IbcHlG1U++tDjVts9ols2imtW61a/f8SW3XaDxkciHfrn+7NdGxFlszC1jrqgJHOY2yZcMp0TSEFU0nlZhoG8ZmEst0myGX9yYCNNRvDOA3oI1xAMkUlrzqEZMy/SVXJQkAkUkvMg1bGUxd4u2/eRm+zpL31f9CvfeIWt/O57rP7zUau/MGHdf3CO9Z+22hp4ojdy+6+suLpfu9aGtz5qdx+0Zd9/ly17wytFu/srN9uhD37Wij2drgulURfmdAnSQ5owJvUFYgQTnYTKy6AcR0UtmHDi3BaIyeMIDgvW2nBnjDVO9AM5ShnSSiA5zQlRfK5ITEkH0gXaVjLe/3bYJbbvhm/Aid9T0arr/pWt/N4NNvPkNpv/xoutgKeAPNkw+WV039PgQGx41O48bMu3/oGtePPviObZL/3ADr7z29a2dJ3uqTMZQbjr7DpSL/dLVMrhbplT5piyHMAAcULl/FY43wRTC8T21jhwprWYlgNJmLnCU0GpoIUkRoHijHJRANhKmSkhJFeUsCbWoh3XrrIXbvis7frGrXJAZeQINrNOtaEN64R46J4HEbuK2LdEGi1wHC8w4czfnm/+0Pbf8EVru24FTj9gXRuMJGHckpJsV5Jg6UU0glq/KgyXDD0gZLa08ndyUXBLH7eYZaxe06O4H+7jg3PdrMPV8CX+GJ9YIEudL6UBC1H2MDpQSmEhZaoRDV/syExXrX3TGtv359+1I/f+xsY/d7cNffhqm4fntBVs44/+4zYrXbxAOzdcPhQ39dlLH73VJu5/0ir3v2BtV6zC81s+Hcx5K6m7C8gAWLor4XYEJd2iY/QCUHCNf57x7TUwcR8EOS0CVb0je3l/ZOP+omHow8AV/0w9EgcGgXmMHBrKEEWsFjmCRXhEYFemjMLKbpv65bN4xjdki994mdgOP/Qbq27b73cavOGnU6BtYV2vzf7yORxT6/RdGIDJl98saEPAodl45MYEPNfsWLo5eeBnjgzpjH9LQg7UK6rYUKADsS8IXaM6ZAJsMmDUQsgkoSpBgZcFDOE7MFMiYEQWgVLdES+m6SxLsrLDJna9YFMHhu0wjloUMNnwLI43blCQPfKFJd2Ao0urW7smka/isCUVtHEdURCdGeFOIwsCeaZVrm2wXQhzCQXiQyWOi3TaEd7OJVhMq7axZqXCKgSqby7nwpxXvHLxww5PfF3lUa462fS9AhxXWV5aAlsin/sWlnba3t/7iu3v/K4Vz8Wp0vW92q2mEtqpdgmAYTfGOcs5OWdnyi0pBRRQ4+xxJmjkRBnFwuiwgB/JyFC1FWwSHtNBUhQOtIJt/raP0tiR4XY1X57zVuPIIgqCMgZRkOS04EW5URDpUEwMxwqEyh9LB1x007bXLLMCnpNEWcKS/EgLiAMjoIUbQSwPX6Vz9MjTndNC7gx1jTgUIT+QlVDzKyrTfQZ4gW+EsxxAPd4s4nZJXZiEwXonFRdcWnM5U5ZmwgWOeC1xTGYqOSCCSd88ymMX3nQlP0oMTqRKDK4aKTKpDmcZGrTQMsYBB/kc21MxnxGTntSRNiSU5cWL0D89tL5O7w7ki7zACrghBYgI54hTGfFYmBvrlG6oSlXmKRfqGJhA0OKcLsScLMiLpwU4abCc3ZtxlBNgGmacEUqix5y/rIzauSKuo3gwKW7IxTjSEQKYPkgFPMXUSxSKtXox22qltskRDVMYNnRCAYvqIIEjGDl53/fRIBeUpQJjMqGgsOWtEYoCczrmPPi7uTjP0omjcDzzAscVkE64rU80PkxCzNck/KkcMnrAhG1X4rGO6UjSsv+04cSYzuo4f7IQPRJM6+Y0jHvxSAfLZZ4wIh2BTuMQ8sltElMUYJRTC9yKdPAkB0Mb4ws3fDoXeIuHFEDKYS5ABYJ5rbAUYtxpmcAweIPEnZjT1o5O4TWfbWY/vASnQnFyfrDDqj8fBg+8JAOVShvny5m1uw9ACp4BY3lduni+ZuDqfdw4wqyN8zKlSweNT+6q1WesPnFZVEuaMUOJmnzg7+OdyNJcJ+IzyCLY4K0ONrEZBTQMbfIN0HTGb/O6dWnmwGZan+BvGYQ3rkVFQj1PZYxvdJcktVyEp9IoMNYa3RpDnhrcsNYKf/OXOlM9etcjVrlzry34xGusfeGgNWYqduS2B3GSvmKL/u5NeGWhwxo4LzO6dZsVF3Tb/M+8Umdqakcm7Mg/3GftGxfbor/5Q+tbv8YF0WCmgtWqWvYiwOc4MWjG8uigqKnolWEZbYoQ5vFtugOJkjkQVe4OVP+IPAMDICIVWCpSjrBWOFuaC6T+uRNdQc1VIl712svN+EV4FO91vPCtW+yMd3/GOhcMCLbt8T02+8xBW/++dyhPYT+/+UFrWznf1v7x9YKxFd/7n7Za/7+90Na9/52Ohyt+1SDXCnTeAkNvaHUiKVDuVmXkolURC0gPBrRJQfgEovkzbPl4Wqr2DBHVis3GVL1Z5K40EeQAwuUUXMlCzhI2S4LwwJQYLDrOicInJXccPYzt2WvVo5NWKJVtZu8h1OLJdujhx613zXKrTkxafXQSPbdpL+FupA0nsSo4Dmd4IZzw4UeeQMvtwl7gS+jGfVYdHrPDgLUN9FrvycuC3lGS6+y6HeNEqUK8VlzHl50B3toCMeyGvT7shYSQtcA0Lc6gjze4J8gyMpnjlEiRCXThEo+L7oFFF9RV048KMebq1pXd/e07bO+ffco65p+L1xFwNOOiZfb01X+Puwueg+EY2KtJ4TcXYKMVdIQVL+y1KvYFf7PhJsAw1Ay0WfGSQZt5bK/9esMf2qK/eoet/9C7ICKaT/09tPYGX1SrjajQNQqILVGEZw1IADQDdqfQAmFpWprhL/kg4LDHbFfSid9hSfzMOaFBAyWlmCsX5YgQTpGz4TDhscmDMAoWEAStlAW8QVSyVVY6d0BHg3m7Vtgwz2dX4mJWpujiJX3QgWoiwyUONsy5ocCZnny5K5OUcRjJFmZnt10n4CPENHkd70TIEELEEon01JCjS7AJKMTiJMKzqch0fHvz5uJbtm5tFGz7dlG2JwX++E2ddyP0HA3WgElGYka0Y4XhTHEARQd5PuRCIfm8bIhFiIXGPNOSz7TzElrGL3ATrkrmaOa0uAaGjhH4iz0g+rAEDgkh1zPIjPLEnbjeAuGhjguG1/E0tRU2zlvCEownaRX4DdUuMAItiwK5MxWAFzi6YHj3F88w1FyIFxUWx4ivDHh4TFLi8YiaFslBkHZm0KLYqoQLdIchBxi1IAeluYvDL/+Ix+EhZ08RWdbZOy2h0UmaF3gajPMB20wI4hkziDN8wtBo+bs4ENU1UprRRFK4hwUItZkU29RpI7RA0LlQXVuUiwy53T5td1htB16khgJa9PKFGh72Ji0EUaJfKaGFSZbz8qwsyCRqlBs5tDoi6kCuuYycf07LYuSoCxlgoc43SvngnqFxcBLbuk9kbx6QlwJxSec5JJlW69MBc1jbOdhV1ESSrS3qHfgtDziYo1fggshZODkbe01vQLJ8/ulrbMPW223e5vU4jjtuM/fvstr9WAyjZfDdXJ464EimFtOijPPmFVzJPisL6sY8spQbPiJzjHANeK0wIYWLnMxWysrlGwDUh48FnhzDw/gD1nhuyjouXmWrv/dJm3fKSlFxPOWkxd4lvpLhEgRAnmtlFLc3CoUeEqE6PHRVwb4DGMF/SGXKE0THFK3fxnfssZnRMesc7Le1//oqfUc+9JwdfPAxe+nu7Tbxf7bjfmIY9w6LrLwJdxR8iQ8MfBZ2WXKMJ6UXB3MZ6jlkgAEtHc7BHgYhE2dQclNFS0nmqGBgiASXTGptuO0zHESq7ThizRfHrTTQZ13Xn2kDOG8zuHGt9a1ZEYnwoH/Cpp/EO8WrsIXGA54IZJnrptESXbiJTlZqw0w714GiOObiOlEheACnQUvn9duRv3/I7nrqQ7bousts8SvOtpPWnWZDp+B1UnzP3PwGG3n/HqzfHreXfrTNxr/xAGinreOsUzFedqtmowhy5R+DJLgHlXOPA/oyTvQKCbShpj0HctIsbNfJ1+pPcXYGbaTnhrNt8DV4YxN3QHRaIZxiqOOuZ+zJXXZk+5M2/qOHrf4Uzm2vnqd7bO0IZRXpuqhicUC/DeehcSwaS4SWFjjdlhS6OC9IE178S/20GqfWs3h2fN48qzzyku2663/aHvySXM+bcXLqta+wJZs22ElnnGILwvfMza+3kQ8/bwfuf8QO3b7NJn7zDWvWQ82CJ7kzyHngzTg0Q0rykBnAotgCHQ9+yoJoA8cmlkSzL+3Am5hX2qI/fQNOdq2H01ZasY3dE60IL9iMPr7TRnA8ZPzuR232G3sAxdB0br8V+ZhAb7Kz9UMOhUQdXENksWLG3Q7WM4PkV7qCV4Syfi8kKXKh6BOAw2UiWoecSIY48Fg8pddK5QG95DJ953O26wcP27Pwfe91G2zxmy61pRefZ4OrV6J1nqpv499da/sfvN46BvqdqYyHHOgov+HiuzjuJPUbYbYYIL/l5X575a5zVDG1jsE+O/f+L9gCHAuJv9HA4Wds1/N2GE4bvf1Bm/3mTgkurp+Hw+uDOCaHkYyzPxoIa4+cqNocJxIKhfkLbSXeLiZNvPnT0gLhozaU480lLBWRcOeTjQcaG1siX9pj4PZT8bQeOBOtGQhTOKr25PfutWfQXQduuAzvflxsC89bZwOrV9jyTX5QiHR8FZ8TknSi8/DHQT86kS3RW5jMEG9XiELpeK9QWQkQx1eedmCYt2KJvuQ3vvsFG/n1Uzbyk4ds8rOPohS/2XDmfDgNtmNLTAfVOdHAHo51lCHnZbpQnAwna4mjf7TUM9ObPaXtp+1P7B404mq9s72jja9+oQViOYgTVHlwQ5wXa90NZM3qDgGtkgoUV3dbuedsbTuNf3G7jXzxh/YU3gEZfB8c+coNtuTCc3E6v8uOPvEcJqQ+zNC+foM/pDgrwT3nTiKQBjFkDhZKdCLgeD5SGJxnU5gAqnhmXJ2ctEMPPm6jv3jUjv6vX2N3Z8RK8wbxqhhO/HOJhbHcD6qTuXNXY5HzWvhCF69QoNF8ug8w/sIT1cS7hYsILXUe8R94LZVKGOUxPWOWIVK2rwqge5xc2FKYbxEkKHhzkxPjR2MY77uhZZYvWYh9Tvw+DF5jGPn0vTb86dts19o1Vl6BDYBHh620AbdxbMlUHEw5YTBQWXdoTFAuQ0srlQ4ySUNK4fR5dvSOJ+2B3R/Hz61MWfVXe1FB6J6X9Fu5d0hP8LT5OoWHUXoZwWUdVymQodE49ICs3JuMtMBvjKGH6oZuMQElP0BGOxp9JdxW1HBGhgitAeaJtat8rBNDqZwAPjheQ0gTP4YD63SmuW0T3mA3vBNyeNYqjx/ywRr3tgyqfcaZE6PjACOnYEwuO7QM4DstjMb4lQy1W3UXDiFhodz+6lUoAzV6RmMUL+8QkV0Wq15KdVnkT1siP+TZMByayVU5YDHwR9r4YhLYuQN3hS19/IzbfB7tgANB48YphnBvFc46NyQIlIHRiSgFshTTHZ4bwde0tM3YjYPseF3VF9ekbzEgM0zUZJS1RE0YsAEQYp3YaAwn3Nlm4Cu4fKENAiQ3dxptga7H2CQnSReSnMCJkgvGYMTXDPVbi2mycOdVf9JeOCXsB2IFs7iMzf5qvY4GSCHCJwU/ThwZhdj9HMoBIxovIZXH5EU+eBiu31EQYgteEOD0Tq2reGVMmUBw4rySA5S4WMLogTtlhUaT4YnUecumwCpApF9AQZRB3XZCgi5N9Bz9BHSSLmj29M4vbB/Y7xol6UrWfaXGPYVQ2a2MjhGYG+IF8kHElzBnK1WUD3iKoiEtqjq6u8eZObdAS4oAJgeFzDkqiOUxbuUddQEZcJXL4hPgOYLjSS4BzgOHURMeBcQr6r1t1cKywm1LlmAqZNNN1nDsq1Qq/A1pyImKtAgMfAIkYyr9JYicIn6WcghoXYVYHuNj8AJXyY/cXIDnxMQ5ASA9PdY1OBm8A0qQkuMFZGdzAh0CYWYT8RGyPBL4udlmF3bT8TvJqwtbtmxp3n3FFp6sPLUCz07OzGAGxkobADqS4xTTaJNk44wgPdY+YSpxjXJBju7Oc0qhBmynCsoyI1MCj0BKIcKL4Iw2AoiIEHXJjRQ06CKxc/G8ONMhsgvuPI6fiHmRI7BKq+PHtvXoIzlDmwkrB2tLk6R9+URlBo8Iq9aoN9JG+HEJPKRJ6FC+kM2tLs1o4hUc657NZOQJqgWvh4hwKhg3BDghcLqRleQLPE5AHLw4kIcaU7kvcY6hPQaPTvRJiaQ5n7jodo4tE5B0oTjIQzqTh1RrYKXIsVyZYL+KOzr1Bt5vRR6Ua3w3Ji2/cmFnT9/hZMouOHNdebZWs9lapTlTraSVSjWtVKv4/Zya1Wu1pFGv8yQ/64KWwr2IYkslCGmN4I4BSB4y5xMkxZVwHGeYI3sREXMeGTMh57iCh0IVhXSOIT4xG92lmK0clSEnCYFQr1pYl6LxNNl4cHo3LZWx0MOrDOVyGS+laZlxpRyIH/U9un9m4j6oOtiO1W9Xe0dvZ3GooHs+MOPimgPnbB2OrVdtBq20Wq81arVas1KvpUjipgKHv+Fc4BYwU+GEF6rL2xRdiQDuwTgHMO/OcceG8oh9bCx6GhdcGnjRWHqYMmS2MJCP9CJgqeNICaS1JKSD8HobfkSHTkp5tA8bLXzdo1DGKwv4FjrwrwfaMd6Fdwk1A0/Vq9Uj1end4LoNjT2uiqAAxsJdg7YIr+2uSArNVaiY1cW0sAq6LIfgJYhPQhfsB8NSO15OpIOpP5szf4e1ikePVbx7zLGUDq/V61jyIWDQxbABn/LnluuqEL8lgqPRAtiiEbN/8ePWSi85JbjCXcCM3I4YrV8eZUthKZ3BNHH4My7sDdg5gZMw/NAxPgzhLrWId7sTnKMq4QfoSnIOY66DicPWWIOu02gs2EDFlru9CNizELEDpv4a/+bgsZPPsmcSzB9SNt2ypcCXRviUiYqcKOCfFrThVbXBQrmxoJgmiyAL94Ap/m1EcQnSi2AvbjZtPowbhAH4Ua2kuwMK8rhcCRL9UQE400mI6PTw2626deROL7+8F49xcK7UcSomQ6tlCoLIF87KYj5SpBO45eRlXi4muFA2f8KYazn2KNQXjzcfARhnRtIDWAPvA+fnkX8OrzQ+jwawb83CFQeTE/ybjoc2vof/LSIPdOT2W/cX+Q9QeOiID93X2tpGfDc2xzxxigyL87q68Ur/vM562ocHLP2lUtKPH80cwE/cDkAY9rOK/bgdnQdDepDHs8wEb9fg6RT+RQXiTtjP24kOtMcy2hM28fBbQvAB/IrmHgNKsEcOHthgTLCtk/KgNO8dZ1DA33PBK7wpjy1PQsZRVBScZGOgGQXeKO4T8G2MFIrlUYxDR9JCbeKMW/6aOC8bUIGJvefzpV17Hy+csnx905YcaLAF/l/6jCmtrZDEiQAAAABJRU5ErkJggg=="
          ]
         }
        ],
        "meta": {},
        "name": "icon"
       }
      }
     ]
    },
    {
     "title": "🔴API-Gateway: Request Counts⏫💒",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "req" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "dimensions": { "ApiName": "$api_name" },
       "metricName": "Count",
       "namespace": "AWS/ApiGateway",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": {
         "name": "SCHEMA",
         "parameters": [
          { "name": "AWS/ApiGateway", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "select": {
         "name": "SUM",
         "parameters": [
          { "name": "Count", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT SUM(Count) FROM SCHEMA(\"AWS/ApiGateway\")",
       "statistic": "SampleCount"
      }
     ]
    },
    {
     "title": "🔴API-Gateway: Latency⏬(Max)🐉",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "dimensions": { "ApiName": "$api_name" },
       "metricName": "Latency",
       "namespace": "AWS/ApiGateway",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": {
         "name": "SCHEMA",
         "parameters": [
          { "name": "AWS/ApiGateway", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "select": {
         "name": "SUM",
         "parameters": [
          { "name": "Count", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT SUM(Count) FROM SCHEMA(\"AWS/ApiGateway\")",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "🔴API-Gateway: Integration Latency⏬(Max)🐉",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "dimensions": { "ApiName": "$api_name" },
       "metricName": "IntegrationLatency",
       "namespace": "AWS/ApiGateway",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": {
         "name": "SCHEMA",
         "parameters": [
          { "name": "AWS/ApiGateway", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "select": {
         "name": "SUM",
         "parameters": [
          { "name": "Count", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT SUM(Count) FROM SCHEMA(\"AWS/ApiGateway\")",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "🔴API-Gateway: Longest Running Requests (Top 25)🎭",
     "type": "table",
     "description": "Identify 25 longest running API Gateway requests in your API Gateway access log group.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expression": "filter ispresent(responseLatency)\n| fields @timestamp, @message, @xrayTraceId, requestId, ip, apiKey, requestTime, httpMethod, routeKey, path, status, protocol, integrationStatus, integrationLatency, responseLatency, responseLength\n| parse @message \"(*) *\" as @requestId, restOfMessage\n| parse restOfMessage \"Method completed with status: *\" as @status\n| parse restOfMessage \"Received response. Status: *, Integration latency: * ms\" as responseStatus, jsonIntegrationLatency\n| sort responseLatency desc\n| display path, responseLatency, httpMethod, requestId, @timestamp\n| limit 25\n",
       "logGroups": [
        { "arn": "$api_gtwy_log_group", "name": "$api_gtwy_log_group" }
       ],
       "queryMode": "Logs",
       "region": "us-west-2",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "🔴API-Gateway: Paths with most 4-500 Errors🚨 (Top 25)🐉",
     "type": "table",
     "description": "Paths with most 4xx errors.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expression": "filter ispresent(status)\n| filter status >= 400 and status <= 599\n| stats count() as errorCount by path, status, httpMethod, ip\n| sort errorCount desc\n| limit 25\n",
       "logGroups": [
        { "arn": "$api_gtwy_log_group", "name": "$api_gtwy_log_group" }
       ],
       "queryMode": "Logs",
       "region": "us-west-2",
       "statistic": "Average",
       "statsGroups": [
        "path",
        "status",
        "httpMethod",
        "ip"
       ]
      }
     ]
    },
    {
     "title": "🔴API-Gateway: Most popular API paths (Top 25)☂️",
     "type": "bargauge",
     "description": "Get list of most popular API paths in your API Gateway access log group",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "hit" } },
     "targets": [
      {
       "expression": "filter ispresent(path)\n| stats count(*) as requestCount by path\n| sort requestCount desc\n| limit 25",
       "logGroups": [
        { "arn": "$api_gtwy_log_group", "name": "$api_gtwy_log_group" }
       ],
       "queryMode": "Logs",
       "region": "us-west-2",
       "statistic": "Average",
       "statsGroups": [ "path" ]
      }
     ]
    },
    {
     "title": "🔴API-Gateway: 4-500 Errors☂️",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "dimensions": { "ApiName": "$api_name" },
       "metricName": "4XXError",
       "namespace": "AWS/ApiGateway",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": {
         "name": "SCHEMA",
         "parameters": [
          { "name": "AWS/ApiGateway", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "select": {
         "name": "SUM",
         "parameters": [
          { "name": "Count", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT SUM(Count) FROM SCHEMA(\"AWS/ApiGateway\")",
       "statistic": "Sum"
      },
      {
       "accountId": "$account_ids",
       "dimensions": { "ApiName": "$api_name" },
       "metricName": "5XXError",
       "namespace": "AWS/ApiGateway",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": {
         "name": "SCHEMA",
         "parameters": [
          { "name": "AWS/ApiGateway", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "select": {
         "name": "SUM",
         "parameters": [
          { "name": "Count", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT SUM(Count) FROM SCHEMA(\"AWS/ApiGateway\")",
       "statistic": "Sum"
      }
     ]
    }
   ]
  },
  {
   "title": "❤️‍🩹Performance: 🟠Lambda",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "volkovlabs-image-panel",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "Lambda",
          "type": "string",
          "values": [
           "iVBORw0KGgoAAAANSUhEUgAAAEsAAABLCAYAAAA4TnrqAAABYWlDQ1BrQ0dDb2xvclNwYWNlRGlzcGxheVAzAAAokWNgYFJJLCjIYWFgYMjNKykKcndSiIiMUmB/yMAOhLwMYgwKicnFBY4BAT5AJQwwGhV8u8bACKIv64LMOiU1tUm1XsDXYqbw1YuvRJsw1aMArpTU4mQg/QeIU5MLikoYGBhTgGzl8pICELsDyBYpAjoKyJ4DYqdD2BtA7CQI+whYTUiQM5B9A8hWSM5IBJrB+API1klCEk9HYkPtBQFul8zigpzESoUAYwKuJQOUpFaUgGjn/ILKosz0jBIFR2AopSp45iXr6SgYGRiaMzCAwhyi+nMgOCwZxc4gxJrvMzDY7v////9uhJjXfgaGjUCdXDsRYhoWDAyC3AwMJ3YWJBYlgoWYgZgpLY2B4dNyBgbeSAYG4QtAPdHFacZGYHlGHicGBtZ7//9/VmNgYJ/MwPB3wv//vxf9//93MVDzHQaGA3kAFSFl7jXH0fsAAABsZVhJZk1NACoAAAAIAAQBEgADAAAAAQABAAABGgAFAAAAAQAAAD4BGwAFAAAAAQAAAEaHaQAEAAAAAQAAAE4AAAAAAAAASAAAAAEAAABIAAAAAQACoAIABAAAAAEAAABLoAMABAAAAAEAAABLAAAAAAIHqMMAAAAJcEhZcwAACxMAAAsTAQCanBgAAAJmaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyI+CiAgICAgICAgIDx0aWZmOlhSZXNvbHV0aW9uPjcyPC90aWZmOlhSZXNvbHV0aW9uPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICAgICA8dGlmZjpZUmVzb2x1dGlvbj43MjwvdGlmZjpZUmVzb2x1dGlvbj4KICAgICAgICAgPGV4aWY6UGl4ZWxZRGltZW5zaW9uPjMyNTwvZXhpZjpQaXhlbFlEaW1lbnNpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj4zMjg8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KI5mc/AAAJpRJREFUeAG9nAm0Xld13/e93/cmPb1Z0rMkWx6wsZHxKHmWbckDJkALYWhaoE1pSiirwCoFVpIm1AIWIQZSykrbFFaZQ9owhZRFm0DwIM/zKNmysS3bssan9/Tm4Rtuf/99zrnve5IcGy9Wj3TvmfZ89jln33Pv+7KtWy3nalpM923dsGxNV3FiM89O4TqpUti6wrLhLC8GM8v6i6LZa1nWDXhnZtZWmOVWFGRZPcuyBYpzwE0XVkxnmU0WTZvMcjsMzFizsEOVLDtYNxspiuxgs8hGiurC2Mkffehw4v8P5cX33lWxsWfyHXthQVq/urOwvT2FrV9ZfGrH94vrt1pBB7K8uoQWmX3/XXnicebW7QuJkvqc6Z4vnr+hyLJ/SsdZKH0Gyg63Va2zrZpbRdwj+yaFRsNMOYp7u7pExC9uec4F2UoOFTWqj1w0dAm31vBLAzTLNU7/GJWDWdP2oe0eSLzQtOJFyyu726zYP1HJR077yN0TovVKUoEDfH/7u7J3vcvs5h0Hs80R6eYWZLWpvhlDG4bOWhyG5jLt/uKG30a+49Z+7P4bXJ3df7rx/rWDHecfmlhwhRZqKFOXYfAP/kvBTEUpnGyQDCEzhf/BYrDBTrKhG5Cb/rkBVZLhZEw3KoAVLIO3UadMn2CV6vBeQIZ6s5ijOs41wrUPwnuzotgNkRcza77YzKr7ijwbySrF6GxzdOq0j/xyHrhXlZ644bKerraFdW3NxrlFlm+ByOXDvW2v3T9Re2Ltx+57Xbb7houOz9saO/GYZZMT9ToTsiKruIbSjP/osdRIobnFc2hQiu2ylFDdZOTJeIsI0SbqE2nBKpG7NT136ExGxMHdU6uUJYuMLR5u0EZTRmVm2xSkmM7ZGCCHGVtNbYyc0W4z1GXEGnWcuMjzIm/He7sh1UffKpxhNbzXoPrqnq6KD+B0rQHvzGYXGrtGmrXXV7O8eUZ3R2XZocO1er1WVKsMbyaJSBkUuCedQ5vuobnM3bjSmHYtGgFb+I4i73QbuNvSGMl6Lk+Vxzqs8BNtUNWGVxd1pj6yqEfklQd4tUrxPKviof2VLO9n+p8kb5VBhS8REm3hleTVQdJyoqvBDS+2GtdsUTSwprUtqxSNuWYVpBUDzUpfFT86o6OaWb1esJ7H+QOyaAXCqtAeslIZKeyGCUC0R4u0tLcaLuGLgFzpaPyoVOQadZEQAJMtknflxVbt6oRPoRWjIagGWwcFdUsU5Sm50bziiEJnWQwNOEiWYe22DGdmqQ6tWC0wXg7gYBWhX6OOJqNHexh16skQIVfHosFcCvGTNDEX51+bwVwQETySvovhcoqfnC3aMkMOBIz9yC9XjhPEjSsdHQc8Ly5arjQ+6K6TNjF1s4tDNWt0tGHGejGUM4FP0NxvNqS2y6csCLokFymaQ3aMfu92gwXAUHeFY1EZ486dyxVVg/+PN28WmNNxVi/RX+JRSHDepopwoN9kSoU8TjeUbcZL0y6VlbtekZckVN0lzYqmz7yiWKG1c1hrAgjB1gnBMUAiX/QgUXglHtZwRkB7KvFjPXhDYORTknbBCs7tqIxhDY0IINAoR7RzELZsxyjIJZFLWJWVWhBTvwC9DHBYTAXHpcZIk1I0WMZmC+2iWFmF1soaOwqWdPxAJAK2IJcKu8lf2mAilFd72L46IAjnpIS4Qy/R92qqpPYyp9BgE2vOQ4G5AI2kRGnQQLql/QiDiZ2joZgMBoElBg3iqLU0WFRNojldzxkz0eE2xNJu/Szu6lQTWVSIWomsbuovbzAA83ZrzD5rxcKLmvOBkfMSdZLohNKSchAodKg/X3aeZRj812UwKaDBW2KwpNORBoO/7BBuQQdUGazS2BPmL2RYESWoAJNCr9xgMhTx9sJ+qw6cZ5XetxHZTGCwsLGItxvEC4v0YzU2aJSBB6cx9pA1a+DjpRnhUZADqWCTBk5CtsoXhD/CICVf2n8FgzltCUcSD5b1/irlLi1wJLePM6fiBosWaxUoCRpyoLCA74J5FeUmrbL8FDv+X/536xhc431O+VXcJrbfaqM/ugrDrMdgPIoSUwY5Xtpg6pcWvksiV1CoVRcAJDjavRIPcyNAjr1AtHo1DT3cc0GiVZyn6AbeDhm7vPEog4l9RuxW22eV7g3WMbTGCh4Gpl/YyVTSeIjSYnIlFquxFJVo1Kzr+NOt98zLberR37P5xz5rRd8VkFhwz9TAqLC4JIAO6tHyYRA63JuTLoKTLCKhUqtB6XOatGuNdGmAi5CC75EmZVKfW05dCTnmwj5aINpEVQzUaRisyRMF9bmDz9tznz3LKoNUg+e6ALq5AsrpCreQZW24+wEW0Xd81Va94f3Wu+E37cB2jFVnOlY64S+DgQUvVxSWSU7ROUo+GQQA5yfYxC7Bqh/Esp/2ZDBJRFU01aTqMjeWRssZJYLeLdtH5EhE2EcJ5JRELQhTxlGsOzJU3nMlHTOgAijuJBdDZdENDUhE7NLWD8J2m3noa1a76G22/LQNdvjkD9rCc3+Ox17qCIv8X6XBEk+oBVpHGFT9UXE3JHCahqRlLPIxhQaviIhTUqYWbin3qlda2lVUGwq3Jq/q5g8iPIN49KeHEj0uhOCO8zGkIXQRem3U8u6zrbbvbpt4+EYn1Xvxe/zxN3hsENd5qZdCkivlsdlxS7kpeL93Olro5x4G94j+Es7bWbPALqwrGsvHNygcyQTlA4skSMqdVugSkRKPmDhiJyLq5l9gRqPKjh3aIrKLRId7ODtfvrzXJu/7mtWnx613/aXWtu69Vsw9DjTiRr6Bjkg6trdH0s58sT+iJLjAPsqRZEH/I/udSur3SlswlmBjZ8mEupdjQxIk5U4mIXlFCIt0UlNY1MKUTkwSDzdiBAykOHRdGGPqXmK13T+3ice20ZtZ7yXvs+asTlp0ALDIJNEpFU1dgdiiQcr2aNjEM8JJavcwCLY0Jf19N0QMN1Zao0vipRAQ9XJscEIlY3GM/cq91lJQg2agTzeOm5p1yiFnxaYcvPAog0lgIvesu8sm7/mWNeZnrff1m6y69q3Epy9CVAZb5FPKKrzYnnKveiXAh3YZRj0k8rJMpdVgAba1n9MIRm4+Pp0nWkcQiQiRakkkMvNMjVyl4mpki8m6ui3vWGFZ53Fcqy3rSNdaYqeBEr7EEw2CUveu3itt/tkf2uSO29kJ2/Gu37Xm5C42gGUALZ7BiFWpMIWXlM8BgVUuw3juxUV8tatDt5JoAKSaEcEXcxyedaovboJOSGXh+bYa8cOOduxdMpCkz5mQc+az8Py0VVf8b/cw9fvKqImPU0nnvPsS4GbhEfDKZ0Agswbt3W02fve3rO/sK7k22/i2q6w5s4ddk3cmMhgES5klvxjA/xWFFYITH8eJukYh3Ra0S/9wE+2CU8DMZnTKWMqbEMh/FYOJgaaWHlcKAksFo914Q6VrBR3sfClRzju6rT72tNUP3GJZ+zB4nFJIOIi4wTh7a9bGrNKzxeaf/AubeOID1nfmJrzrQ0T1b7fq8NXsnCOIzuMVQr5qg2EJN5hkk/zIsISWGrGS26HI6hz+ZdM6hg3gjrOIQKMDKtcIkNzqgYjuCBxxvFNex2hV2qxr1To79d9+Ra3HTAvjI/bC1z9o9ZE7fXouNZhQWOzlXV0cpN/xnWCsc66y8Vsv4MmHyLW6DK9kUPh3lJIu1K/gYSjn6iWDlRLT6vZy/WuVj1235n1tlXz1+DiP0wVHNwEt3J1CMIjwk8G83NLgOHhVXu3zaZL3na7DRFsYP2QLE2NWmxglP2S1ycO2MHrAp2jHwCorqoQI9xBw8jyp0wVxSjz8PKs5Z3nXmVZ77gfWfvJbrGv1Kbxx6iZoBafv9byx4O0Ynuxickt5i2gudGpP+dL+hJc0V29sC6WiPbd8od7co61l0t/xYUNeepbCutdE10llz53jMTwMY/H6CKUz2/udawM3zT7gkwE4vbEG71w6T3+rvebffc8Gzt1so7+42ppTz7IOEe6bAtYA71MS5AKDZZ28rrn9L6zntRut79xrbeLWk605tz88YNMvvj4DxCvJHOmI4Ctew47lYQjiA8dypQk4Faeh21G8JKjcT+VwWyyrKyUvxwZNv6BpO4v3OSi4nuDy9XjNmSzkXJSt/XXWdsIWm9v5Nza+4y5OdDqt/4oPW330GaZVL4bWG61AxnMFoXUelZZvstntX7bpZx+xtr6VtvyiP7L6oYcwFo9HWg9bZF0ic5IVGVN7ylv5LOIDV+JIEEHx+kiDwFt2Xvjwel1Dz3+HdADtTqpHeG9bLJcEA0jAaynrBCKraLvrYFRZdHJcQ5dcRNO1z2z0lm86xsB5V1nb6gvxlL2crgIbiYdMSmoQMCJPsWO3/y9wzPrOu84q/V3g7ANnudMUnot5pMxR9pfvh4xTD3RUTlecGVMcLxcTshwRlztUQol4XnUigdKiQLGuhtAfGvxO2FDIS/yVEQGoctUxVHPhEAeDV9nM9m/Y4R33WLWrx/qu+Jg1Rh7HIP0IITiNHFkgifMs4J0bbebRz9nM7p3WsWKtdW/8PB75IDh9wMX5/goMlvQKMnut5LNEFwH4xUIuv8psAj/PJxSa+gAm4aKUsepIXk794kE5KbOESeQRQZSRgodkmmp5F44y43HWoW3f8d7B866xyqr1PNLIu5ZDV6G/d0Ue4OsElTR2x/c97zv/N3gsYgyid6UnAiEkWVMuhCSrPCK1p7y1X53enu5U5EygjWsasqXIsxanniNE6olJSSRQCqQoH90fAFJ7cFeNRsXqk7dhqCkcDE/pucxmH/2vNvHUg9bWO2h9m36PMOLRuA7hjT56kowkkhgwY2eceeSTNrv3GXbG19iyc25gw3gQHKxGfzhBEOzLGWRRCS+lasxd19jhmRy9KEZz3vzro4uwY9GT4NUW56V4h47UH4E8U1usO5OAqHtsZxBQvKgfZpZtZlS0JeqImKlD8dC2v3TYwfOvterQ8cG7kvJOJLD2hZx2RRhjd//Ycfo2vEWOShtxV0VHz6/cYEm3RZmd5KIuVKWXdledZ7HJH8qbWWNcumrXdAJUVA83IXgtVb19SX+EPabBZBDWlMbEA9a+ZrOd8uH/aSvf9Bk8bDsGk3ddYtMPf9Gmnt3OUfRq672YXW7kYTyFHSCuQ4lXmGYI2XWSTT/0ZU5id1v3ieuta/1/tMY4a5c2FJcSrwoiS/hSl0THxY39STcBHbvf2/0QOOd7Ms2+cRH3aZhsdBSykwpCqHhkv0vgsqkU+p0ou2GdOAibDV72W9YxMGyD52+xjpPfbY2ZBxggwjxcfOTWv3K0gY1vtMpAJ31au7QghbXLuQNY4JFZ+xprTD5vY/f+1HF6L3gbbbCcH7FCu2lQ+9dmMMTL9F6VNJIXjcqkPi5jkWc/DLx8ZI40iDcmUSKcSLgmZbYopDp4Wm6M321dZ7zf+tdfJGh2v+UY7j16/8BmOcd6fq5NPfQZm979lHUdd6It3/g5a4w+DGAPFFxIJ+5ssLq/dO0csukHv2oLY/ut59TzrOO0f887WeKujMFxLuEWRQb/VXqYOPPZ2Bzfq5GPcFLedGMRBMtYJa8gXDRCbE1uuyjEkf1JSBFv911PRhm4+J08yvXY2PY7rTY9YUPnX2Xta9/MeccuX2sK3nGM3PYjRx684E0EsBhydg992hkTc/Fio2gQpLLQ10cesLEH/s5x+i58p5Th4VufY8lgEYfehP6qDAYhvQ/nQXCe85lDTMUqxiJQ1Av9JcRdDreGs04yR+6eqY1raX9oU0DanL7P2tf9hg2du4m1t24vfvef29gjt7PGE7lv+h3WsoMAI86yU23q/t+32X3PWfcJr7Xucz9NDMXOqHUIRqXCIk3M5kE08e3kfd+02tSY9a2/xNpP+h2eS1m7mNqlTMArlfii5Q0OEm+L/RqYI/qb/r0ae8p8szGRF231KWAWKvpGMUUPjhGIHIHsDNJoq88FoZDgXBatRfV5OYENbf4Anz0ss0MP3mpzjz/NTvZD1p6arbzoOmtbuwUPeh7jHWeNaT4qTd51yTs8DmvMcDLaajBnkseXuVus9uJNNnb/z8XS+i/9F/BEDmI4HjSDnN4Tbi6nikcbxAGO1a8VU2fJmHD0pPGHJvKZhRpPqtm0LMgEjaZ1mpGLgMUk5qlcUhds6ExwGt3m7Ham2haMcq0b5+BN37C2E4+z2ce/Zocevt0NOHTVR/Cg5zBIJ8Y5zibu/ZTN7n/eek5eb91nf9KaE0T1emQKErR4iOIwbMJ6PnGPXmxMWP/Zl1v7ie+B7wP0heVXQC6TZCaVIlNIsqb8yP6AwMGI7FJkB7Kt1sz7mj36YhhjwVztLdTLMm2JaNmtthIguaTg8FDaG5NzNrj53wSveuROHlW+w/PcBhZuxVbfBqRpKy64xtrWXIgHvoCxTifAHLeRu/+PyzlwydsdtjlHDKWoH3ilwFJHz4ct772Gd4o/s8OP3EIPH4de+ttE9AISrAZfZf+vkqdSZApL+r2S6Ct3TcI05CBFyPlzT8+xtxczmoYylhpLgq3lxDTlDhiIqqgU8JgmbOPVVWfZqouv88aR2wgNNDPqs4QGW2z6gW+w2N+NQ7EzXvUJTkx30s+XiMv4cJ7zrbnRfdZ32rnEUB/l+GYHcmHhRQaBj8dhRPUsa+N3f5uwbdYGzrmSqf1m+OOt2gySrCkPVBb1exmDCRyrwD9jt4Hixq/er+PGKbmbBsMVDs6hfk+l8RLTlKtX5VYAfXI09ixG+Li1dffZ6I57bere/2Ztqza7EVlwOHJhfbopPBcG7zqLrf85POVqXrA+YqP3/sz5Dm36LVdMX9P47hqYBZl4fCoWRjkEvNbmn/qBjT92BxtCu/Vf9gH29/3Ebwq+gqDcFw3n2KErEPqHPUyIzaIZjCUEbMN3+e5ZTj/SO3Y5GSrlAlY5WrlZm8Z7VtjwJW9yMiO3/cCnk040dQrRZPpUBzbb9P1/boefuB+H6sewv2/1fY9hj+W8pJCnfM1PWRWbdb32/exyj0BLnrLU9cMb7rp71+G7vsvaWLf+c6/ijJ7dd4EgVYeRSknWlIfWRf2Qna4lcLEhJwTVrOYsyCVwIE5LMZpkEVYL0dJp1OwUW/pb4JAUoyy3xsFHbfDqP7aO/hV2+KlHOD//QulVOudy91UkzvQ5EL1raOMbrLr6tYQSz1h18I02v2ubjT54I7BE/le81wNYhR4eZyWeEoYBaMq7+q+12R3fsPEn7mFqd1vvZR9h/dtJN3GajoaUSjwvhjY10+6JghcjnDKmX2W+xlTP8/2CcdOzlPnRcjkN1ZOIqHisciRaCqFpQbigY5Phy94sCnZg2w/dbfV4kIT2narOd1x9m5ieX7bxpx5yww5c+R94C40H8SJCQenYHd/yAHbw7E3Wfso/Y+HmeRJPcVFaeEs4vbjQ2eLYHX/pfAfO58hn6Ez3Yv/ALinQgud0HLpFvxaDQVcglbm6bxYjAg1+mhX6Y6R0blPaKfEQ4DHLiblGr32A9eY+vOrPrGvFGpvYtdMOb/s0C/0VKAoveVWU0A3GMY11yLuCgisuJO464XVWP7zDKiveYnNP/dTGHr7VDTR05b9iodc2JxqtHuD6+NqV919tMw9z5POkpvYAOyNHPjw2haNnvDLyLgc3yS7lSIv9ARAH8p2Qdo7dF/xkJnhWE2PhVn6+Jiz9DzhlvoTgEuJUCALdq4h7hjf9I4Ha/lvwKtHQZuEnppGm02W+67mw9yJ2vy/Y5K4nrHPoOOu9gFdj+59ADs7x8a7RW7/pr+8Hz72CGOofY/TdpdGdDDeZzssYnycdG72dnZc0sJGj575hvAs9idUcslRKNW8KucqkspuCSLeFM76JetHFDhM9K8/ySSmlx4iA4KRakAUaUiKompfxqoxX9LUX77KBq79g3atPtKkXn7Wxm/7Qqit54zw/5gqmHTMJKdZ6TV9dsZFPKldBrGnzB57xtaw5x9HzwDUEsD+wsUd5PKq229CWD7AOYSyP6FkfpY0LoZui+nGMcyUP2F+wqV0ExP2rrPdSjoMO3odD8qmAPBkMP0dTHNaC73REhpT0wxLNCnsSdhmvT+zlsSAai4Bvyis4l04bHSFiJeSUC25JmVChqPEytB2vuvyt6rZ9t/yINgpLolzRDRIqwMw4rKuPPMlO+FFr56RUIcbkHf8Z411FiHGInZP1j1PokVu+6bvc4HlbrP14wg8esPkbJefTqrCXWbtYOu3Qbd/z/oGNHD1Dw9gl9eZbxz5+VqbzMgEiTzJ4q8HUqPfQ+iMnymMnbd2ll5pxzeI1jyroRhIainkxkEjGSXnqCgvrSpt/4Q4buOoz1rvuNJs5sNsO/f3HWXfOw2CTkMKDSsRoMO1i+lh3aJjA9Y0iZwe3/ZW//HH+sG3idZX+azhG/q6Nbr+LJ4EuG9jC49HI065w2jAkaJASPjxgampP3fdpP/LpXHm89Vzwn2zusZvYaW/Ey24FfxvXLbw/0TIkg0X8lNMqevKZGE6Nu8lo8zWLY9MZKRTO4SPWkTGNKJBKvUWSw7bmwrQ/tw5f8Zvev/fmvyEuko3wOOfqzYsGI8TQ55AKPgev/qx71fgvH7HJO7/EtOXBmujfF0/x5/W9zgBHbvqmE1mx4Woej85379J0LAchityq+Ogd4chn+Lp/bSff8Lit+/DTtu5jT9q6T+yy1e/H+D2nMmCcemihPhJf3Nwenvl6paawG1Zs1r+b5G+DpGB0Tgov7WEa2bxjyBZ232H9bPv9p55pc4f241Uf4lvS01FUnpvwxUqMIY4RmwtTrC9M20tD4Lr/ZqYNj0P4k0vnRpZHsjjn/Ztt5sGv2eHH77Vqd68NbvmE1bQJ6PtTfeelxVbJ5absL0PO4sjnD3zt0jna8hPPsGVrT+H45zRbxpra97qLeMi/jPO050ALJgj4iQ450yxQLpgeIbEXk5rNOf3hgP6MDCT98/N4PzeSwTiM8INoX4NEB8kY2eYC+wIDM3zlO5zMnm0/YetH79Wccmr9gJtAIaE1gAI7VudKW9j1C1v5zj9jB1xtk8/t5GMPPOy4TXjVKIB8u+CKC11Ti0MRovoDN37b+l93gQ1tvMYO/fw1PHzvIYRiy6S//ELD8ZBVu3PlNfbidz6IUS4FBm8m1mtM7bfht/0BxmMw2aEBRybU5Qq6UpeFvEOdHiP4eq6am5W/gpiTZ1ERaAm76ObJQwIVMco7+m1hz11Eyx+1ofXn2zwfgYzc+CU8YXUkAGz4H3Mx6PRpm6P88KVvESvbd/MPnKt7cyAflRAa4tSnWaQv5eH7vxDAPmztfSt45f+HhBg8HrXpg7jwUta9UQTFU1Md120Q3808eoPN7vyizez8vM088C0GRIcsAS4witVIQCKoKEP4Gp4XESEZiznjX+RybuoEnOFSIotTkqkir5rDq6A4fAVHuqQ9t/1f1qEd2GOtK9AqvFj750GdIcTo3/J5617DW5o9uwhc/4hXYBf6ZuDPcpKW5Jnk0BBqa1UAe3MIYIcIYKsrh/Eu/j5IL279BIIs4jo/jKgdt9J/OVN+Cwv/G9hQ6PE/Ygg8xMRxIp47RyonkGammMOTe1beyBbkWTid/M4HWb2J+RIP07bf1m21g/fwcuEDtvKci21hknOom/6HB5JIz7QmDlqCr+crNoP5Kd/xhi8Lgeu+bT/WssM4wFRCcrmsfotlNfParLL8fNahzxPAPu5PCH2XXc/RDkfPbXp9zwDGlOj44LIUFLXDHoMVnFzofUDSJbJzLC8nnhAQDS45F2QkYUhuLL7/40+DgcBUMprj+c2RHDIwoTEqzddBNrz5n/hasPeun/PwewvG4kMzvUANfCIemQeuQ1bbc6f1X3699Z58hs0e3GNjN3+UkT+LNSVsBs74pfhrcSQduCXEUEMX8tqMX5poTMu7WCOPNJiAfaIIj+fW9Fyp9pikcuKpJq97X1SeMi9Wy5EIxmry6Rn9PkcdONAIVlskEoLJLs6r7rdlZ73bhjdsshqfXB9k8dURL8FQWNgpLmHsmwFehdOt3PQ257D31p/4nxQKJwGXIlLwcmwISuGd3ett8t6tNrX7l0zjk633wi8QMz0KX+ILgBZ5liRDQXTS5dwX65FF6I99ohN9PS5UocONVW1W9NkfxgogiakTitTcs7Ttc16lo9vhq9/rjyH77rnZZh7/CevCRbh82jiEJOG55FXtxFV777SeSz5ug2eca/OHD9roTV9k4T5JO7EgHVYiOe+A7vqFG+1M7YwjIL2+P3hriKGGLn6zn3I0Zl/EYOwarF0uZySSZoPoB8LiEFJUi/bQ5fWjwTj4K4JLg+bGmm94YKClQ1u803YhhSzafiPnmaYx+SBf7r3FVl9EAFmvIfhfM5V6ORLm+Y7pkLWzivIVX9YerryLvxBTpMz/VZe/XdRs721/a7WRXwKzAh0UW3lzkJpiqqrgZd18mhFMdJ/I4eBWm+G1WQ/x0/INn+LFxnbWwuMCX31BKP7x4oAMIxOTsbZ5LBenjxYk2dTpi/2R5diBgTwCFEiIs6p1TMSvzshWaiWl3IlS56cofIo1DuFV73ufVXj39/wv/toO/cnXreM6lp3RnwQkGVxIjsNoMOALO3hV9c5324qzL7KFqXE7dPNXaIe11iFcRaO0GI/BmboUcTrkHqdpYujQsGMNjy3P2YHbf2InveNDtuKSt9r4313PV80/ZsBgquVY/CUHmeew0RFUfTfsamFzK9c40W/hJRQlmjwx33Rk4SkYK9XIcV1/mE5NQnKm/u6ater8d9jay97g3QNnnGcbH3qM6UgQyHTywC4hphyNJWAnR836NnP/PTfa/HO389iizUDbkzZgz45tsEjHDaYQAXp59wDe9RWbvfLtvNg4x0774yd8OmccE2jqubyJv/JoNb2v7Bpe5z1ZlfU1WYSWZDBv0o0r9msIPAVj5fp5h4JHnUXshOxIrg0H98haXb4SKqwzVJavXue7YSL20rnoZja973k78Iuv+wsL5gnuSLwXd6lFz3I5gY9rqIgiTIhpcA/WTH2jWtt/GyexP7Z1b30/0/F0Qb3iVJ8+bLXRXb7huHGjsp5FKiq7JJkxN0JyY3EaxIOOTgckl25hbBzZDUUTMUul52ybfvKndv8nn7G2gRPwGL2fDYQ8O0bZRxWSeZX4ZPRp1rxniZk4keCjNi2ZjiKW1FQOU04F/Q8GU48rBTOXj6i+Oni2jW77nE3t+HsCYdYjnVdprpGSTMLzRzNRduL6/JyvdKb3cArxOOvceZqXQV2U9Q1O+OLNFcMoiIfkxsrqeYWXwnIYbggkSZ16QHLmSXgWzoWRHTa/92e+PbiyUZYkU0SNQktgKckvAnWexqLOX1QgYJqy5YCINTxcp0Qv8XQBWgymnRHDZNVVtnDgDjx0P7Lw0whZWrCgI0JuPOCkvap+tK1TkpN5rmQj0u4pXuom9wGhoCriZqws2gF5RAjJjVVU+S4+eFagKgRZWhSciBiJgv4jaMdKYlN2Hycb+0TPwQOO+hxHVISrpGAYQ6nhKCNFmJc3mNCTfJLlBOphHXL+kY5nunG5HuKvsto8xJDBVea/2qW56q4T6yx/FKBfUgFo4Katm6tbtt5cD8ZqZp06FCSm8LjT4eVhUPDTAvpK5dQuhV3pQF98kiCBp7iLbTCYzB76wVUhgC/SpF7ST2XlAU2EIq2A6wMpg4kO06/k34IjXCUZpORPvaQpfBCPNJjTFEVGRN+tATR4ph1k3tmUT/KqNbp0KljE0F4IukTZp6RXhKdGkrdLCvVLqnDpSFrlAEZZ3qo+NZftFBMdFV+qLBT6ym6VS2B4qOxtgWegT/mYMolYlDX1R8IlyUAu0AQaz8prvAZDp/65rnafimFFrFS6dd7ML7H5oIl0KagTT5Rojkyi/mFkoKIR8iVCuXcGQJ8CXow0In6i46xim/PlJnQnIVpqVB4vF8zbvEelYNBENzYcRT82OBi3lDt4xC11plGTSr8Mx3rH7xzyxoPk05CFrFdvpFk39exRyiOAIKgklY8EAcXXeUcmIVNjhKfkTqUWtOS42jthTB7XMCelbi+UNyBoii4a+IffPgNOQBoQLdi+btEQ0AUoyummQinOYtnZB893iYQgichjV0CimSUpxy6Nrva8wqd/xEvRWOgyIFHkWXS5QP7rXXzPrO3TT3vJvAYwyus1UVPH7NUqZX5KQ8dERAecI6Ib/yr8Thzlis71NcX1hwkSyi8ouYDQlCtLUF3ipZ9x4mLtZDOSo/NVhpep+FbOOkJRorjJ9NGiClDQN/1+2Kta4pXKsKJRN6C8UWWSt4Vi7HEICGSNRrPRWW2rzGb1tYJwz8Jr3HLzc0W2MOvLsvqabTwKVtuzZhvBbkcHvxXXkVfa27NqV2eed7Zn1sHflrVjKBlEwinpeLqO5vpxRS2QlElWo1vbIOYPn3OAICvhKO5HFQxSpSRq1TZKLAsVebsMrR9QVApGXaStH3HUpekCvyY/bdVgkHWCUugDY246cvKfjCAUgJI8VsQQg0zeqZq3ioHYCEJlH7jwhofHMt9ug7GKbJWYdnZl8x0nVvLunkpOubK8K8+XdebWxreCIjCPBNPzPlPHsMPBmXpz30zd+L6nqd8c5TtxO4jS47jAJOM8gYAzGHKhXssW8ry20Gy0Ndr5ZT2YN4u2rJif1U/rNXJWzEoFY/GLLG2VarN9rsb5c27LAOzhNwl7cJk+ztkHmJ08FdsQVhtCySH0GeIxt48B46pU+VGwnDI6IS2dPnAaNBnV86aXNZa4bVNxFDJqMD0ht2anks90lqU64QMBXHGSGt1YIK1Z1pHbaad29nbiLXN8OTKz0JjFK16YmG/80uYaT/Kjrk/WG9mutrzYzTH2yJ6R9sOXfunO8nxaxP5/pq1bLf9d29BZ6a/2TM0WfYzDAD/+uKI5l+uXIY/DuVaj5DC+QxScraQ8UGnL+tva865OfpauvaoFR1YJUvsU56bcL26ztWa3Zg7GXC8oWTLb86cb78PGg7jl3+LDj+Olj+ART+/d2dznH7sFei97F60w4QH9lDvjy+K8FMCn6Lj++kgNhfgfB/2lMF66vcCwz3Ru6OngSJWAgDOcfBDPHeIwgqd7PLTQmp1zjmN9WEQf4C9nai7HOPrJLC1RTx2enL36/wFb6iVp2EYZlgAAAABJRU5ErkJggg=="
          ]
         }
        ],
        "meta": {},
        "name": "icon"
       }
      }
     ]
    },
    {
     "title": "🟠Lambda💛: Requests(RPM) - [Filter by ${lambda_function_name}]",
     "type": "stat",
     "description": "Invocations - [Filter by ${lambda_function_name}]",
     "gridPos": { "h": 5, "w": 19, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "req" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "FunctionName": "${lambda_function_name}" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "Invocations",
       "namespace": "AWS/Lambda",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🟠Lambda💛: Async Requests - [Filter by ${lambda_function_name}]",
     "type": "stat",
     "description": "Invocations - [Filter by ${lambda_function_name}]",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "req" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "FunctionName": "${lambda_function_name}" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "AsyncEventsReceived",
       "namespace": "AWS/Lambda",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🟠Lambda🌝: Duration (Invoke Phase: Max) - [Filter by ${lambda_function_name}]",
     "type": "bargauge",
     "description": "Duration (Average and Maximum) - [Filter by ${lambda_function_name}]",
     "gridPos": { "h": 9, "w": 14, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "FunctionName": "${lambda_function_name}" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "Duration",
       "namespace": "AWS/Lambda",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "🟠Lambda🌼: Errors🚨 - [Filter by ${lambda_function_name}]",
     "type": "stat",
     "description": "Errors - [Filter by ${lambda_function_name}]",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "dimensions": { "FunctionName": "${lambda_function_name}" },
       "label": "${LABEL}",
       "metricName": "Errors",
       "namespace": "AWS/Lambda",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🟠Lambda🌼: Throttles🚨 - [Filter by ${lambda_function_name}]",
     "type": "stat",
     "description": "Throttles - [Filter by ${lambda_function_name}]",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "FunctionName": "${lambda_function_name}" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "Throttles",
       "namespace": "AWS/Lambda",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🟠Lambda🌝: Concurrent Executions (Max) - [Filter by ${lambda_function_name}]",
     "type": "bargauge",
     "description": "Concurrent Executions (Average and Maximum) - [Filter by ${lambda_function_name}]",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "Total ($account_ids):",
       "metricName": "ConcurrentExecutions",
       "namespace": "AWS/Lambda",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "FunctionName": "${lambda_function_name}" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "ConcurrentExecutions",
       "namespace": "AWS/Lambda",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "🟠Lambda🌼: Dead Letter Error🚨 - [Filter by ${lambda_function_name}]",
     "type": "stat",
     "description": "Throttles - [Filter by ${lambda_function_name}]",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "FunctionName": "${lambda_function_name}" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "DeadLetterErrors",
       "namespace": "AWS/Lambda",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    }
   ]
  },
  {
   "title": "❤️‍🩹Performance: 🔵DynamoDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "volkovlabs-image-panel",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "DynamoDB",
          "type": "string",
          "values": [
           "iVBORw0KGgoAAAANSUhEUgAAAFIAAABRCAYAAABBuPE1AAABYWlDQ1BrQ0dDb2xvclNwYWNlRGlzcGxheVAzAAAokWNgYFJJLCjIYWFgYMjNKykKcndSiIiMUmB/yMAOhLwMYgwKicnFBY4BAT5AJQwwGhV8u8bACKIv64LMOiU1tUm1XsDXYqbw1YuvRJsw1aMArpTU4mQg/QeIU5MLikoYGBhTgGzl8pICELsDyBYpAjoKyJ4DYqdD2BtA7CQI+whYTUiQM5B9A8hWSM5IBJrB+API1klCEk9HYkPtBQFul8zigpzESoUAYwKuJQOUpFaUgGjn/ILKosz0jBIFR2AopSp45iXr6SgYGRiaMzCAwhyi+nMgOCwZxc4gxJrvMzDY7v////9uhJjXfgaGjUCdXDsRYhoWDAyC3AwMJ3YWJBYlgoWYgZgpLY2B4dNyBgbeSAYG4QtAPdHFacZGYHlGHicGBtZ7//9/VmNgYJ/MwPB3wv//vxf9//93MVDzHQaGA3kAFSFl7jXH0fsAAAB4ZVhJZk1NACoAAAAIAAUBEgADAAAAAQABAAABGgAFAAAAAQAAAEoBGwAFAAAAAQAAAFIBKAADAAAAAQACAACHaQAEAAAAAQAAAFoAAAAAAAAASAAAAAEAAABIAAAAAQACoAIABAAAAAEAAABSoAMABAAAAAEAAABRAAAAAGROEIkAAAAJcEhZcwAACxMAAAsTAQCanBgAAAIEaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj4zMjg8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+MzI1PC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+CplSzXkAAC/SSURBVHgBrX0JgFxFtfbX+/T0TGbLbJnsCZCFQEiAQNgXUQQR3H8RUUCRB6K4oKhsKoq8p/JU5OmvD/lR5CcalB1BQTBAAgQSspGELJPJNskks09Pb/d936l7e3qGBAK8ytyuW9upc746tZ2q7oQ+evGW2gW/HbcHI9zcz78Ym5xqjKb7IqHSpLJU3kMbkErlvNJ49z4RfTVtln9kuSCvyvfm0oX2wa7CB8bMzd9wQ6gQpL0NP3TORWsqEmW1qXSurzoWiVV7Ia/ag1dDpmoiXlTv1Qh5ozzPqwwhVAEPKYT4eF4FEEoyf5LxCc9DPAQvyjjyzVIh5OllGEiTn16W6QTCHUzbHQqFtpHexkgksiYTCa++/z8bdzqevVDo3C+0/ZIE5wH5hfmctwSF0Mr7/3v8trch1LvOevJnNpbVFNKpUGVVRSFTqCmEcjWRUKQmFI7Uel5+NELhWg+FWvJZw8pqKFClAKJwlQQuGfJCCcYnQuFwJBQKE5MIYYkYX8zr8yefQHl5evSh9lM40Af5Lq8rEyYN9yhe+bxCgU8WhUI2w7R2NtSKUD5/0cJfT9weZT0TkxXNczLpjjmhSDbHAu3nXdYmtdrC962eV9hBf1fIw14K1OMVMBDycoMFhLNkOM+6mIU1RfMRLx+OhlGIhSKReMFDWSiUT4YRKWdyRdgrVHqh8CgyP4qCj/LCHt9DVeSeGkNNQZxaU0iFYqEENaqMUsQlSDgcN4ECIRmQ/AbCSCAEj0uUn5V2uawMhSgANcuDsGG8gSTgLMAkvutVftHplaqrD4v32DhUXs9LxgvZ/NhoLDV2YGDnTObaTpX2ItnBbgz2diESS0YjsfiYcDQ6hrUdLYJqwQIfr8CWBHKMyCEUzZMlYiU+xSCZAIeAiEdYI2QVkbAnlYiYhoT9lhXzjtsSZqURpiGqjC1uJJ2mqIUKuYwS/Dyqyxz7EgV06BhNo+iD4jSKqUVkhIOAUi6V81/tRfSULk9yON/FscldmPWZoEpU3ch4mVw+l0lQtknKEiVVjhkFpHt7s4VsZ5ggUtHC7CRRKpbeI+A7ldHUnBocZkD0VKlVIzrOBYAIYjp1Bw4ZfBH+BMnCDhSBY//4EfYBIS+uIMkaZdXBh46e81WvUq2YUiynKIkbFXfd0PKxPlduKN6qIjzKLx4C52Tx6YhPq07q6OiKkvK66hkXjrjRoRCaoHhqJJJOQERIN+zlqYG5vJcPZb0ca/VLu3pJxTHGWP0pLCrSNPMt5Me5d79+v5wa0wpabp8Ih+WCWslYtvyUQypgcEkmvotHFXVYWQa+OrZc3Uwityoj5z7t1cozUYR8T+WZVgyrrGiJt5JGkfQKGwou3dDj8CrF8kmMVy1RZi2TtrjYYsVGU1U5gRTPnEH9fmZVbuksbwAF8a5+FuFLEEc/EFOxomfJfnrgBQLLtxImiCNlAklHfAE1dAU648oJEJ9uETiJq/Lin+9F8AJhgkby/QBMo6M8vjAlvl5FUsMeuRyrgFQp7pgW8v4jqVSpOQk03O0rPBTn3oqf9sIP+/Njjbary1VRGs+YoG7jx4VdVAkdK+KHS/KroiAYvARymSB+4hC94XUrrxM4oDM8bGgwT0jjkRQQqNeH9JNrKWmkCDqiere3gKjC9i6iLp+Flask7L8OizOajpjFB4y68oqyRL/MG8Oi73KIB7HMD/tzfjGsRP4N8aO8dD591WOUinmCJJVTpLwS316H18kc9qf8brixCXj0R/9tZQXXF6GYUgsFm+ddZY6qiom6Ps0vht2Ln8RAMWysurDK6c9Pc3kCOi6NdXLqt7pZP6c8C3N68n0T3mgMCVRKrwiMVaTqrDK/0qCMq9OJoByleUr5c/EHAqaJpnGHkzS9ysFw5SguirhoEXFLZXUaSpRsL3zjmEIdtrFFeYphpfsDcTATurBoWGlJIP4NJHvR2MK0MH2uj7Q44jpRayXnM8k5vmji13gnP0+Q86y7UFAGx0tYY6XPQ+k4ZryLkPHsaBhdX4YAqHc9ZrJu1cW/8kgOtVpHanHnGFSS8ekyvTMwxbyjI7oRNlM8FkacG7GYpjY6LgyQzgL9aY9+Af1cKg4wnCdwDuQQksxfzqcswSfGvV0ijChXpgJAwGZIg4sLvpNLgqrFqxpSoB4wmIHcpOnkNmBUicmgBrB4n7abyIp5xEohEk2EC4X+ai1/lN3+fGo+kQMA08o5AYJK1EXFQIp7mjICkcsBXX0FrGorYP0O1jPAGjmiTGoKY0JtBI11EdRURlBRzs2RbevJHWn0EeTOPg8d3R42dhSwbA+RG2RZgjq9RmVDqEqFkWAdg1k2SGa4hhqYRaAEiABneYeYyejwsUgfPHlFoPysvnKVgkky1mj8CIcEYbRGn+ZY3H/hG2uUVtmASrD2q5mWopIOdA6zFE5aCGzYnsdLayh8VRinHBTFeSckMePgJCaMLUNjQxzV1TFUpKLUVGmrhuqAgSE2MtTWTKaAvv4COruy2LU7h81bM1i3KYNX1mXx9MY8tvflcFRDGGPZKDZikYeiZgbd36kVZdoPmAKpCLDEfwswJbFoaXxhh+Y4r64ttXKEfFqOqA+OQCxdqxXHSDUvCyisgSzKbltZEcKyDVms3ejhM+ck8ZWL6nD4zEq0jEmiuopzWomT1qUH8+jtzUGA5WhMUv1yIhnlrl1DQnl5GPWj42gi+NMOAk5wWdDTm8e2HYNY8doAlixLY+WGnA0dpGJCFsEMFGFITFOQIeBcpayy6Ex13gxM5nRTsxrGBhVqJC0LqkPOBmIhrYAR8kFk3P7A9Aiixj/1ygUPD+Kqiytxx82jMfuwapQnqZp0WXa9zVv6saUtjdataWzfmcWOXTns7SpYt++jwUrdUxotEDUBJTQucnio5jBQPSqMptFRNDfGMHZMHOPGlKG5KY5Dppbb0zi6G3cv2o1jJkbZKE7IkYt2KUtx0hS4viKoQpObfjFdCqL8+wNTABmvysAATXgyZXAn6G/xJLWvZcpyIGBq5hVQK3fk8eDvxuK0k+s5QbCbsfyKVV144eVuvLS8Hytfz6J1D7sqe3uCZTSZxKnFMWfaYNc2hpyArHqQY15nbwGbd7rJZTA/CJqcUE1wx9aFMbklhlmHJHD0nAq8sKwfM+oFPjVZE5IJJ2HoJLQfVh1Z1p/huE1B3wWYDmTXH/lZCHH5I4uOq5pK56vEAYKp1mR7YmuHhz/9bBKOmlsrDvHc4g786cFdeGJJGh2cMGrYPSvLQhjPCULgueUOazXwxJT/rsIKlPoOCdNWgdTdDzzPbvzIuhzSjwygrKIbE2iireHTNUDDlP4ZQSeVkeOH9CJH8eo5/CS5Esj5S6l3qpnSSNXgFM8TkF7WiDHaJhgNVKr9LcAUkTJqwEOrcvjT98cYiIOcGH75fzfi5rs6Uc8ZtYZMN4yKcOxy3VXdRZoqobQEksbrXfyILfdRGhYolsNoDHDWbuKkMm9W3JZOEiZLNYhyGDDASMD5PjGj60DU0ktLqXVteezt8VBRpqFdae9MM00KMS28aEGTiINmvWGkRYmHAwAzxAX1IMejY8ZFcML80SqFu/7Yiq98swOnnRGj4G4m1kI6lydxrvlKAZPANvMJKLUufcKgyvkEvoIOHJqcUV4Wxs3XjMGYpoSNo0wN2lyv+3WqS5OZGrF9dxZfu3kXl0uylhLGdwSm41IVmvJxtSeNHHQaydokEwWXGObEAcNupmaML7QmHs1VvQMFTB0fQ011nONkAX95pBNnnhmzGbwvTRs6Jw3XzRw4TjdE3Qlg4PkgCjBph5AZNugzuxbkz2zI41dfrcG4ljKOnwXs2Z2xnZHaXAyLqpwfdAE/VlvPihTXqny07uzickpjtEC0Em8bTL82R0B1pWjYFZCabISYY8M+7Z3R+wFTDKiFNW7lqW1lZRF88kO1OP/jW/GhC5Ko4Uzb08+dh2miAHW03UwoyfcNpug63WR+gcpQP7v0CVOiOOX4ajGNu+7diV/f14tJjWHr2pbPZBNdJ2QwXMXZCK1c0P/2xkYcMiWJZ1/oxfpdBcwdH8EgtVQ1FBVENfvyis5+Z3Pmc055tHpFOUeO0IB1baa4MdJlcYriF/CJl2pm0JoB3ir1kXPHIvcHDxd+m4drHB/POjRmy5ccx0PtPNQ9tQ0UOCYwwQy6twkkQXzB7I3Ey7hYf4wTyx+uqbe16Oa2Afz0ni40clm0k6sAcyPAc7TVyCHs5M7ojDlxHDQ5aZr80D/7MIWTnnixXuDzYGCKM9b5lmCyPsngmoA8eF65unbaNJKDnnSBYT7M4uohfYUVpTjmEBFGGRhK4xOsnrRD+fQnJ2Du7Crc/0g7frWwB5ufHUTj0REc2hJFVSX3y2w6ldZ+WRrtfMU5Jx7yGlPpc+eAPg4f758WxcnH6QCRk9tje2zNWVfFcxOO0RJarImm/vRhrNLXFnUjwT7n9ErbOb26uh+PrshiPtebGt9NEHXrAExfdusTRkSCOnDlDxtyrDLmlPyhUJmsPwPMooCBJ+EMbT+8P820OplXZjCtzwa5S7n/oa1433uaMXNGtT3nf6wPryzvxOKlPVi0NI2Fz3CE1367LoSK5jDGUKtquMcu52zKIyIu6n0+KJg0XuvCBzk23nddHapGxbBxcz9+sbAbM8dE3KwtLIrgka6Ec61swGlomcMufPhMHlLSPbmoB01JNZ6gUlY/fymYKq8w/72pZoqCytvGFAlqJPqNG8VJw4yEeUVwXX1KozOArRoX9qM1sdxxzy7c+0AHLjm/CUcfWYfx41L2nHMWsHdvhlu6AbRtHeDOZhBt27Lo2JvD7r15M0xod6MhIMzVQIWApd/DNehHDovhxOPc+vSBRztsoc7jEqIhXsSyBOa7Y9KPpG2Dkq3ZUcC3P13BRoiyvkEsfDqNFho8tIuywpRVSqAViIEXaOaBgCl1U2urfhrHo+xhXOIOaaSAlpO66z3Q1H2C6ed1JYDa6hBeXJPBx7/RivcfsRMnzR+Fww4dhcmTKtBQX4aamjhmTtdR9pDTDJzVkytYt9/O/fOl12xCLbX10ddzeOhz9dzDR7F+Yx9+/uduDhGcJJhf6DmNIptSAIJpYce0xaXiwHFH8R4B3dLlujThoZan6NrZCHzJpvcBdpRgEix28wMFkzSJjfYZ6DewSNTpmdBhLL03BVN5VMK0WKzy8IczZN+gxxkxij/+doBPHyYcsxvzpscxviWOqRPLMG5cEk2NCe6f4xjF7prkbB+lcSLBbWWM5dO8dKKdx97uAj51ZJxrVKeNf314txAzAMSb1S0wrIWV5MCUVDGuD9u42zp7XhmmTEqiuyeHG3/TiaXbCljMeDuiF/vc3RxZH8Y4bjndPt+ENrmHdXtWuK9uLh6MJ3UAwtcn7ni8SF6U4Jg0jo2ui3uDZio6EExF6DLcDJ96RAI/vmk62m7sx4OPtuOeR3pw7x39qJidQW1ZH/byVk0dt3OjOfE0VnPrSM2TcSPJLaSsPZpNE1yUPbIph79d0YgU58O163tx65+6MWeCjBLGIGtTY5s2DANTmqbuup379DNOctq4qyOLz38gRZtn2CY37YS0TZWdYOW6QSx6NWs7HVuJBJpI/63AJGrkw/iJRdkofQJBWBpjQl8RShdXAmwf3VyYa6iSlVoLXjHVtjOP886sxOi6MntmH1aLz392AOs39OJ3d28n01kcTMDUnTTg7+7KY+feApdEOTeDU5vMKs7Z9jPHJXD8MU4bF3LfniAPqkdbSzWquqJm9ZFgimHN5jOaIrRAOSCnTExCz77cmf15rLx6K016koE5TMNN6LfWTOUQTrxGEeXVkl5dFbElkCJFQ0k+eHxxcSPAFBBVXCsuWp5Be/sAu2wFvvz5Zpx3zkZs3ZbGmWc04FDO3g31SXt+e9d2I67ua5ZwR1Y1uXZVPXRJbgP/sjyH67/cjCQ1dd3rvbjv772YPy1mDZDiHlkAao8tK3rQ5Zz8Gp40YdF6xJ3VI4930MyWtE2B8mnpJTvmZILaWM8BlE5j5zZa3xtpgNZSjGo4XBNHhllDUKd49wGLRHnI3WddVK1rziHJ7G8JpmTv4DGClj2Xf+EQnPuBcfjLA6Dfin+/aS9OP68cZ59ehbraOLbsyHKvzDGQLa/KDT4REKP0ZWyWoNt25/HZ46mN8+ukbPjJ7W1Y8mAGS2ZTSh1TqBtwpzN5YgTTuQzS8osESHKom6uRy3k/7Ud38N5XqBPcvaKeQ8kTz+bwvSsrMWsGb+nQPfNcFy67pQNTOU4KRMOBnL1hwtkfmNZsJERhOBqFe00wrqqHxkgmirG3AFOgnDQjiisu24GDplbgjNNb8MGzx2Fzaw0eeHg7fvGHPfjy5TtILIx5742jvoZ7XWqkgKOsdiooX8sedXdev8Ly9gJu4S5G4+X2HWnMm53CSQsqLb/45sU909rV69J48Ok+VNPKtC8wyTotT24YqaMF6r7VOfzwqkp8+XPN3M6G8eySLlxxy26M53JITgZqlXHYHCCYVsCKI/TBS7e8P5Gseqi3Y1t+b+vWSJiWVjaAa2XlodBqcKvFvbhXEpEGdXOtd/DEOH5680w0NCTRT5tgeVLLU2prRxrLV3bixaVdeP7lPix8iYPXSvUfuilhjOZyqYFA6Jynkr6MrhU03C64YxaNC05Al/mNn5qJL7pqHbp6dUppw/twniUk/2qoic+ty+OS96dw1aVjDMTFL3Xj899vRwu7sx3QiSXJqWpUzOR05S22mKBkF+8yMr8agC4a5tmS7rDoUpA5xhuOpV1GxYWuJZCQXhmOUTteXJHDbbdMNRDXruvCt767FuecWYdTTmzEuLEp+k32DBDgne1pbN3OBTk1TevFXR06bshjN8coLcxlLd/DZc99929l103ZRBawJeFkiW/hMcOkCSl0dmbsgK2lNkwjLRkSECU8y1ZSTRD/sTqLS89M4Uu+Ji5ho36BIDbTqKKdkyZLlXVDg2hIPA03RIMD71t1cwcageTtyAHeQGVBDeGiwsdoDGdsZDfXkNrN8fHME+KYMc3tg//rNxvx58VpPPPqdkz6XTvex+XHvKOqMe3gUTxjKcfECRX2BJUHfuuWPpx38Ro0UEOSnAOu/Vk7G5oV8C/tz9J13EoufzyPJS9NNiBfeqULL7fnMYHjm4YGE98HU4YRGZUXrc3ikjNS+NplLTxEi2Dpsm782/d20uDB4YEgZgmiACv2QA1nRsMH0xh8CzB9Idg5o/0e7zwTRtLTysmXoEi0pMVKNJMwY4Bj5FSOMTJWaGkiDZvbwjOVpii2caz7zcIu3Pj7ThwxJorZh+iwKonxPI5tbk6ilrucUZUxLsrjnElzzhrjMzVhNAd/q5a1UFBtP2WI/ejFZWw0t6T515IeHMljWBlszYltKoJArCZQS3hG9KlTy3H15S287x7BshU9+MKN21HLBrHubCCyDIs7rWNxVVaUuySesu5XM13t1EhdZY7ouCFi6wEppGnmMKImlatkGJjqBG59J2G/euUkHHHCKnRNy2L2wTxCpeH8IBoOBPjiVwfxCLV1J81pUeZt4ZiomVTdTxNQA6051s3ImBbLNLCbExsaA9duz+GCc6ttgd7KE8lHSWsSgTStIk9SK1mNqrkFfHljFh8+PolrrhyHCm4vX11FEK/fhlGcye28Rq0kOYSiyVkC2jC5/XhxYirmVM31fx9c1U0XLeT6B8LRyizHSN7ZLm2RoJJA3UvCxgLD/LPH0eICuA6rl8zCz27fiNv/sxt1h0Zw9MEx1FW5U0XNzFnONxlqkbqjxrbOnrztRLQ0CuSyLRxBkTFB4mrL18pJZe5sp43LV3ZjFRf/U3lbQ+tJCVYwEDmXbc7izKOT+NZV46nxUaxcQxCv22pdOcXZOmgsiWqdL6hU4lifFL1SHMSW+JB7o2b6CbxCn0gOcIzP8Cqv2ZrcWkpEKYKpZynRITCthcQE82hLlqPRQYf90w6pxs9/PBuf+kQ7bYftuPP+HmxdyoUfu9TkWRGMq4+gkls1aZntTIw8GVSjBOz6cb3UZoHUO+DhXFqBDp7qgFy0pBuHN6lOK0RwOCZSE5dvzOGUOWW47mvjUcMLCWvW9uLy69rAlRS3gKXaK7ZFm1VS0w5UMw1z5TbAWZi+ESHS0WxvIhOvyKUJpJZ7POUWZQei0wdVaJINB1c8kBmt4aTJOlK4/vsrbEdz8onNmH9Moz1XXNqPjZt6TKhXV/Zh+Wtc/62kGq3lmiMwZ9WQPvffdhFbdcnoyvCps2jUoAFj2ZY8rrukCpUcU7ds7cfD/+pHCw0NbnvK2Zn79VfYnc86NolrvzoRdRx/V67uwRdv2KJNm90RMtAlBh8nvxpPvEsOH0xWK2D2p5kqWMTfcvofFD9ale7I5iqqBpyVnAkCmbkNRCtY2mKMZ82mqZbPz8/cGiNl8zvzvetx6Rd30sBbj7lH1HIJVGEztoCV6+7J0jY5iD18unifp7M7S03Om2nMjmhJN8bJSwwvfGiP+e3s1vPmOvPb8hVdWE5gJ3J8lF1RIKo7n3Fkkpo40SaxVa/14OJvbqbxI4RRWp9ScwWYoUheizIwchiYlkeCvRWYxKCIjRXKRRcsmJHl92rsuEFg2rc/SEiIWksVC7AC13zGiKozKeWbc+avY0+L4lc/7+bTg/eetw1zZpVjFu//HMRuOXZMOWpqyzBhfIU9Qcn9+Ytf7MaLqzI4d466Nb+WQ/fs4i7MGuNuoGkhv7o1hxNml+HGb0wyEGUp+tL1rbyRQWsSp087m6E4gSxvC0xTJ1ZaIjfhYDjAhhmEOod7bkGUtHVAC3J2UeXgn0svoh4UVDmfqJEgBeVVdnXvGNdmz72YxQ9uqeeOph/33NmDx+7jBnlyJ29ahDGLZ+AHcRc0YWyCN9ISdjkqxRPhcprKynj/McbBTLS0V9Z4q/OapbzV9unzqs12uY2L+UcX9aOJQ0GSM/D6thyOmZnATd+aTGtTHK/TynT5tzdhBxf3ldwhVfCmWNQ/ux4SnhWof1OAt9RMysRchlAgtysj+Ibk5kmigDSSdiQrjEwSRYqExo4AxMBnvBGlb+YzDuSGLcM72nO44eu1uObrh7ILZ3DJhbvw9KIOPPpkrxklPI6jS1em8eQLA+ji/NOlb/ypPLtgirskW/IwKsN6tUM8dgpbhkuno/1uvXJ1F5auyeFjpyWwhpp4+EEJ/PDaKWyQBM9z+nDltRu5RS1g/qEJu9i1eVuOQ4bWoT54gQz0DxjMN+3mwomMopAxIMm7f5LIN6kE/8yVVDwMVGbgxSGzsOzqyCPN7UdlZZw3IGLcBmZotOhh163Eaae02PPFy9K48Qer8OyLA3blpK5KIzCdtbiqtJDfQM7TjD5AQ/F7Do/ZzkjZFz3fSWt7hJakHKZPiOGWG6ZQs8vspts139+IVQT3xMMS+I/vTrXGvfKadVi/JWerBDNsqJ4Smd4dmGSIOKknsldmBaccz7apfWw6q9CQDAB1KqxSwjjwpY2ybj/2QBqrVrsv137r6ml48Ml+bgOfx3d/sAxPPb0NHXvSdn2ltS1DI4c/Zvmk1XGIl1l9ZFTVZQM9ei/j+PYau/Xpx1fwrCfBBhrAopf6xTSaecXvx9+bykksyauC/bjqO+vx//+ZpiUohKuvGGtnPDt2UvNpK9U4qqHCRNJHiQwWUJg0XbR9Wh1Kc/K6dCuqiCCSr2TdZjG+Oo0kc9RIdWNLGsrMoLVaSSuWaqZu0x4+L4Jbf7EBP/5RBaZMrsKzj8zFnXdtwHeu0Tdwd2D+6SkccWjS1nx1PFrQglyzs+x/2iILTHOqi05n5MYLe/X27QUcw7263Gtru/HEwjQ+/Oly/PSmqTRelNOAPGAg3rc0g+s/OwoXfrLF9uF7eGJ522/aaFlyxhmTnTKUHh28I82U9gk7n2UpnyTgv6Brh3kYKiAZz1qL+cTBm4CZzYbQRKPBPXd14+IL92JMcwXGtlTg2988DB8+by+e/OcOLHxwD267dS8JE6HJEcwZG7GLo5WcXHQ8IfqqQpULQNk4dSsjrWsqs6OYfohb9jz5zB5MPSGKn9x0kFmVtu8cwNevX4c/P5zG3+4Zj/ec2iQq5jTp3HpnHz54Km+tkZ4ax4aP/w0wya2tM8U18THl40huYyS8fMah6BIdkoa9iu0XzCTN/o89mcHPbxuL008bZ5PP84t3Ysb0Gu5w3HPB+Vls2NCNNa91YdWaXqzkVeVX12fx2hKqprqcg9GHIISJRxE8nkIu25THZR+t4kRShvZdA3jiuT787a4ZNHqkGE7jK99eiw1tWYybzGsp7byEyvH0xZf34Kg5tXbF8A+39uFz/74Lp3GLGtyq+F8FU5ppe1gbHdMOSBqSA61w2shPk1HjhFSXAWUYMViri9Zxv3vO2eMNiL/8dQM+/KF1+MgnK3He2Q2YN68BkybybHtWnT3KpBsZnZyydWGghzP73s6sGYM1TOhMU1aax2n5lvXouGOceW7tuh788odT2G0rsLtjEF+7dg1eWZvBZFqZyhMe/njfHvzjX92447Z+3Hl3Pz79f8bjvac14Nh795h2u55mAkh8ysJPX5aRMlmYud50aeTAUS5SIz0v5IBkkOox1LUtnz5KgVPYeHGMaCejO+CnHEUrT1PKrvX99//biuNPTfAwP4PzP7MZ4w5uw1mnpGz5cgi7qHY5dVyQNzaU22Poj/hobNyBG7+zF6eek7BrL0o+dGY1L1DFzZj79WtX41lakg7mXSJ9R0cHaVpvrlqfwVkfj+PXd3fg3LObuThP4BDO7FrQ19KIqwnHdUOnHO8KTONZ+PBF4wZv9PldOyQbCp3QFc5qMQWV2QFn2JeOmcyjvW6Cs6tm0ng8wqVONb7yJV7r+1gFRtNOqbs30q7/+n0P1/5bMX16FDOnxrg0SvBiPRfkPMlLlcdoL4zyggAX0DR56a4QKeKU+bqdoRPAgoHY1Z3B169dhad4h2jaOIKo2xbkVxdZdQG1mTbMe/4+iBsv4+Kde3Ld3JD5QPKInvI6uUwb+O7keseaKZrcK4uahna/a9NwZfrv6jX8lMHq54dlNzaMHfHg4lx+45VRl1w0zfbN1317B2YdleAOJoo6nstMbHFnzTrcf43aunjFINp5mj5IfCWgrWm1DuIm6Ni5YimEeUe62TrCEzHtz68miA8/N4BZvEkmEIOrzDow28mjikcWDOKbN1Tji5dOElGHn3tjIIjwwXR9nXlYJ4V8R2CSJEvzgzRpcnVAgl8RsUjV6f6p8tLtUFEzWbnY0Z8oGLxGkT9OURHHtd86Aicc14bf3dWKO3/LA0rmnnt8FA11Ua4jZUkHWvhMY42aa3SkYHOOckpAxs3n1enDeblArocgfue7q7Do5QEcOz3GXuAuSOlKy+M8GcQ24PyPJXHDE2Nx6slN1tVVzo1dxiJDYla06Zvg1r8s/p1qJgv7jnS5dzAg2SiqyTlVZiHn7w9My6wsBEXj5eBgDs8+tx0nnTgOJ580FsfNb8aVl3cwrh3/+Gcn7ruXKyxfoOTkMA7mTQh9j0Yzv64ji4YeTWAp+gK1ty+La65fgdv+0IsZB0Xw5ydJYyvJsPy5xybw07MqMX9eLS9q1diNYfH09KJ2hqt5Ay1uqwhrbMnjgxj4Go7ezZhpdEjWV6t+XyPFgnMORwei9tmSfd9gMr9lFpcOzOt4gjj7sDZceMFkalQ95hzRYM8lF+XQ9oNebNrcw6VQL1r5xaUNmwaxk1+J28Srd6/vJA1ebrILADxyQBfwicwrZsjYyOt/F3ywnHfH47iS98cnTUpx55TiejVVPPaVlr+6ci/+9NftuP2vvXjt0dnGk8ByzmmKG6pKNJPCWbem/7Y1k4SNKhucFJ1GeiH70okDRsms30YTdeP9gRkQYv7AjeeY+ItfdeH+x5bjrNMrcPKJo3H44aM5uYzC1CnV9uBUl1sT1WA6xzE1a0uiHCcVbTvlpJnSFt1Q0+GYvgClYaHUabm0YWMPlq/gwv+ZTtz9j36MomYfwTWoJCs6pxmSmgoh4JhC2k6jSsZM5ns7YKo8v7dBagZkoJGOSRPDkhyYVrsy7hNMMsS84jNw0ozZh0fwyuI8bl+zF7f/phuHHdaK2Yfy9G96yo4KxnIJVM/ZeBRPoipSMZ6Hx0yugMZIX9+WkElN1qTdu3kuzm3h+g20tK/qx7+WDWL9bo/2yTBm00SndhjSQlIycERRTAo8/o0Ek6AWu/nbAVNkzQkrr8/v2vplIDqhojrt4YdajgFblI8EM8gv33cyOLy2pYC/PT4dWkTf8B/bsXxJhg+XqZWcpnvajeb4mRFMofa2NPM4lgdUlfyasc6d7RyHdWp27+c5jS48yXq+Y1cerTzsWs1vI+iHtkbTHjmOX0/WV+kmNtjURw54isjkmM+zWJIYkkli2YfS+P6mYPryvulsbo1CuqQkgvz0gfT4pWOr0BL5aixY5VL3UpukYyTgUllYhtnVFdfwruEPv9GE95w+gQ/woXMn4uVlu7FkyR4sfrGHk0fBLD06rBJIL6/I2xU8+xI8sea62qxBSe5wkjRI6vxZ69RyrjHrOXY288u8tv41XAggxdBC23HrjL12Q02C0nGE8FcELs9Qt94PmKR0QGOmgcAKKLNpc1EjeefSahYiAkYBA0e+wiPBlGmKh04U7uXl2u6l0diYwoW8O37VjbxuMrkC845u5kUAntfwef/7JuLyK5/H35/pRXMDwaDw+jqbZmwxI0Xhp737GFjYjVnGikWbiY+NoECxsfmue0IVPJtZ+Ps0bv7JaH4XXJcOstiyPcPLpQSTvJrsw7o1o4aFJbW0m7WKIV/u/WmmCHKdwTIc272iRvIna0RCQMr5vuvSLmxCMY+JTAa07ElwR7GOW7CnntqCj398Gi6+aIbtm8/5wCuoGbeOtsEGnHhCE7ttDK+82m+H95okREtaHiw/hKSFVTdlsA+mFx3T/VLFclGa2aStOgreSsv83+7L43s/Go3LLp5sxZ57fhceeDHDu+wx228rUto2HDyKOhJM0jMto/9mYBoU6hMC3Cv0ujEy5HHrz3I2WjtZDFSj5TRGBSQwc/HVCT4gsz7v/nzis69jHC3i849twdVfm2Pg/e7OjbjmG23M30pLbRlOPjWGBA3BIqMf+dDCWvUFX6wUTVIWxFaHfBlXgm/S2tdHuK9Wd1XZPZ0FvLCWLz0hfO4zFbj1+83cCDQZi5rJr7l5C06hNV0mOce6T//tgunLO1Izxasq0ze/+DOIPpAIuR9RYqQyDNPMEWAG2mSCk0PtiY48LIzjTn0FC37fh3M+MBXHzBuDo48egy9esRvPP88F+VMduHshvzzRx8wCitdUDprEiwK0XpdzUa5bvGH2EmmoKQLzqDsKMP0Mg8a9DXu4D1tvGANTI/jE8WW46PwqHHN0HW8G19oVQ5V57ImtuPqmLajihQRtH806bgK7HiD53pZm+g0ruYeDSV7YIQr5rIzW/UzlDdvLttyXKKs+t+3VF3J9O/ZEw7zvVrxloQySjoTM88Pu3Yr7BtoQnl+UwcWXVOOCC/jd7SOb7XRQ2XV5YNs2Lci7be3X2tqPTa28B8Qu2cYvzLftLqBDtgrdnJDKcfyspzV9DK/s6UJWY30UE8aV8Ts75ZjE63661TamOWWnjqIvW+Qryztw78Jt+MmCHpzEa9IyGquDlfKsvG44MWn0IakUqaR9hF18UEb5lNXKsEMlRlXy8ni0kM+HZ1nO8y7b8lgsUXVG27LF+f5dXZFw3O/xRjyoRP5wMF2yS9ciOsZZduu2PDauK+BDH63AWWdyZzOnnuazStTVvfEyvGyT/f066cshx/WiumBA037Tggtxd1Tr5kKX6j73dg6yrj4so7Xo8Sf34s5H+zFdN+EaItRkdWM6suaA8kv6gAXABGkOGMtcUsbJFYAclCkJe8mqKh5zhdMFL0y7Fh0rTerXOguaihXyJTJ1VlcQR4qnF4w3/gs9ppNB7UqyPB5ooiAtvMa3hpbwhQs2sNwmzD0mTmtOivbFSkycqJsXKdTSLqmTxwS/fCbffUeR2X2nKyYZ/m7DAIHeRQu5DtF28nhhM7V5zdo+LH01jX/yaFbHtUfwm7OnHx41DdRlVGPX6JSMuyaC0jSuOZ6L3Vwy+iKqsCYgEzeIK8pNokxyOBAVrsU45GZiaX/WZlS5fmhTP3lYdFZABB3hYH1VysgbwCSDvPxroI7iOHjCSfolRa6h2fX++kgXfvkLnd3IhVHLMXJSM3/3h922ulrjpbaB4tyd+vXRltlJw/Eumsh28IuZm15nI8uYxAX4lLFhNPA+uiYTHdtqbLQbFZLQhHdADeOvJK1UBgOTaQG4VsYREbzM6jDQ+Di0ihGbTOXAzulyYDDUlQ7dcIMXXta+bQV/Im166wuLC9n+NH8TiAwyr3FlL47Bfai35RJjlrvUVxGGXXFOJhyzNG65LO4upK7k6TsxenSRVNquDJoktM7U+jD4BSuBLHrKYosLNrBzami9uVWdVeAn7ZPfYjH3EuTxObU6jK4YtSxDPBfDqi0SKVTUNfBXqAY3RHd3T48+tWlTvDYZT9lPwNrFROaSZrFUaWuYZrpYZTCBh7WihAy6jHz+U9gsR8yfJ2iadAxctTLTdUygL1/qV6jEtz4c7/ZpeZRTdAS6L5dxIR6sDNNdylBdhiwzB/zwxWhbWFREqDROvBvVIRks3fIyhS01hIVqdufx0kh+Da93wYKZmSjt0NpfVBQoacH99IhysrKRBBj5Nrp5UQhVW8KImBgKG0knmKo0pALfZ57xlmCNoqyGgsU5LMSXy6M6XQ7nK2uRj1LgDCBmLY07YDBddWxG6ogNXRpwuHyLxirIaFme6yECKT5Ug6vEhA7CQ77AMOaNcWUV43QjwhZvSQLPMrhyI+nuq1wxzxBdEXljXQFdx4N4c1Xx00Xto8xQms9YMY9fuhi2dNGxulUXHd/VRppsqMPdiuLeIVfJUJk00hOQdL5c/ouYt1iGh/ygwiDzGwW0zEym75cbSWdY2AVcfuNBhYK6LUKVG09vrMsSLE11Kd1VqYCVKtLli0UM8eVoGoUgzS80sh6VdeVIQwonC4rHr5bRhXOxaFU4ktCPFPNXsvM2ehkjPgOu4kAgRlq884vMBAz4/jBmWUkxHwu7LEN0hoVH0LFyxTJGSDyLoKPpvw95omsMWrr/5vPs8zGU2dFwmYaVsyz7A9Mv78Z6ja38fXa6cLiQq41EYshnM9w26pfZnTtgMEVKzJQIYBRGhItgGgjK4Zej77Lum85+wbRyqliknF+kYwyphhG0LevIMn69w+j49AI6Pn2rh++WyjHVdW0HJOfM0GgNmnmugB3TRpEfbibTBGOTgEprAmK8tYNBbpHKOuSCd1XEWM3aerGQ75MknU+XfhBWvuHEFDbIlYty+GVMMGV2Qlkxy+nn9dmSxFpcB+WCfEGyFSF/kjvgz8CyOHLCAkHewLcyys/1q2oveAXTSH471ms0ILMZm2wMTGPUcSYCjhoLUxAVNqKqxXcGVhAw30+jJwYFlIsZAk/ZbA2nNNHyH0c2CLs0pfMbVVaNPiyrEbDKimUt5AhosSx06ETL90s4KfJkAnIVQ6ncpsM/v1KdLChyDkSFSUqLcPVcGx95CSEEu9PIX7qP1MsUxP97wIvwtoRqFY6OHzHhHrWAXrm3JH2+kyAF1DfGLE+Yv49leRTPPJZuZSzMOJXnu/7zATmXTzQsXhwxUik+bQW1c3BRqsTKiwkrQ98HiSUszuBSusL6ME+vvjPQnCKYkIKGwkp5LNZ/9yNoR9b+X44+dwF64zYqRCsFNxiRQkG7Qf4olqjrP72YTOloiB0fqWoew8xqG7phYPpcmbD67xcIiP455OT7wtNXSw0T1HKKootnOaOvT/KligIh7N0SxbSYJ6P60XS+80MFNIgzggpEO7tF8p0IU0xaNnkcyg8pm21+VIVointz/CVX8iao9fVwagRNLW5DpOlXw5z2nHT2PylIUBazIk4uhowvslHQBT7+C8eiDkhSah/s39XBLU+MBkp+w1nOr9hxYjH6IEvajNM0gQwDvOpdGKRcg2ykQV7C4T100HLoKZ2mBB1ThZjOuIJLo3T6HbY0d8eDI98tr8cfifRYJhIdZLtn+b9E8ApPIef8fI7/10YunIvmyDxNRkQ5TIslHy9cls/Q4hIbKHgx/r8lvQlSp3ixBP9bG3SQnToaVDpDtJSggn62nBqxJ03TUiySG4xHvWiUm+J8LBSNxr1MPpGNpsv0P5gQmxTVbhT/Y4tRbKBqNiV/wwqj2aX4a5VeU85Lj4+EPFv+/A+MNv5tSrCQEQAAAABJRU5ErkJggg=="
          ]
         }
        ],
        "meta": {},
        "name": "icon"
       }
      }
     ]
    },
    {
     "title": "🔵DynamoDB🗽: Successful Request Latency⏬ (Peak usage) [Filter by ${dynamodb_operation_name}]",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "Operation": "$dynamodb_operation_name", "TableName": "${dynamodb_table_name}" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "SuccessfulRequestLatency",
       "namespace": "AWS/DynamoDB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "🔵DynamoDB💙: Consumed Capacity Units - Read (Peak usage)💎",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "TableName": "${dynamodb_table_name}" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "ConsumedReadCapacityUnits",
       "namespace": "AWS/DynamoDB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "🔵DynamoDB💙: Consumed Capacity Units - Write (Peak usage)💎",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "TableName": "${dynamodb_table_name}" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "ConsumedWriteCapacityUnits",
       "namespace": "AWS/DynamoDB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "🔵DynamoDB🎭: 400 SystemErrors🚨",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "TableName": "${dynamodb_table_name}" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "ConditionalCheckFailedRequests",
       "namespace": "AWS/DynamoDB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🔵DynamoDB👗: Throttle Events🚨 (Read)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "req" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "TableName": "${dynamodb_table_name}" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "ReadThrottleEvents",
       "namespace": "AWS/DynamoDB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🔵DynamoDB🎭: 500 SystemErrors🚨",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "TableName": "${dynamodb_table_name}" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "SystemErrors",
       "namespace": "AWS/DynamoDB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🔵DynamoDB👗: Throttle Events🚨 (Write)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "req" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "TableName": "${dynamodb_table_name}" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "WriteThrottleEvents",
       "namespace": "AWS/DynamoDB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    }
   ]
  },
  {
   "title": "❤️‍🩹Performance: 🔴EventBridge(Bus)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "type": "volkovlabs-image-panel",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "EventBridge",
          "type": "string",
          "values": [
           "iVBORw0KGgoAAAANSUhEUgAAAFEAAABSCAYAAAAsGziYAAABYWlDQ1BrQ0dDb2xvclNwYWNlRGlzcGxheVAzAAAokWNgYFJJLCjIYWFgYMjNKykKcndSiIiMUmB/yMAOhLwMYgwKicnFBY4BAT5AJQwwGhV8u8bACKIv64LMOiU1tUm1XsDXYqbw1YuvRJsw1aMArpTU4mQg/QeIU5MLikoYGBhTgGzl8pICELsDyBYpAjoKyJ4DYqdD2BtA7CQI+whYTUiQM5B9A8hWSM5IBJrB+API1klCEk9HYkPtBQFul8zigpzESoUAYwKuJQOUpFaUgGjn/ILKosz0jBIFR2AopSp45iXr6SgYGRiaMzCAwhyi+nMgOCwZxc4gxJrvMzDY7v////9uhJjXfgaGjUCdXDsRYhoWDAyC3AwMJ3YWJBYlgoWYgZgpLY2B4dNyBgbeSAYG4QtAPdHFacZGYHlGHicGBtZ7//9/VmNgYJ/MwPB3wv//vxf9//93MVDzHQaGA3kAFSFl7jXH0fsAAAB4ZVhJZk1NACoAAAAIAAUBEgADAAAAAQABAAABGgAFAAAAAQAAAEoBGwAFAAAAAQAAAFIBKAADAAAAAQACAACHaQAEAAAAAQAAAFoAAAAAAAAASAAAAAEAAABIAAAAAQACoAIABAAAAAEAAABRoAMABAAAAAEAAABSAAAAAHB0Md0AAAAJcEhZcwAACxMAAAsTAQCanBgAAAIEaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj4zMjI8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+MzI4PC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+Cq+waCUAAC5GSURBVHgBzX0JmJ1Fme77/2frfUnSnaSTkI1NApEtQRMgAQXRgIICOui4jorjHX3EZXAl6KiDg4yOu+NcdQY3EDcIm4ABwiaKCIQlJGRPJ+mk051ezz7v+1XVf04nAXHuc597K33+qv+rb6uvvtrrnET4fxSuu+ii1KK+BZnmLqTzQLaaR0M+LjUiFTVky5mGUlRpjKBPqgkxmqrVanNURRMQNQLVpghoRITGCmNLV9HA94ZqFTnGOcKyVTCuIsP3NIupT4qfmHBmM1RRjSKUmdKnyE+eeeMxMMJ4mLz2RzH6o2q0p1LFzkq1vA1RvDVKN2ydf/3lg8S3EG18/cqPVRHlYlT3lioYJYPRKKrkK5W4SAGlagoVlCg1rhCMOErHqWKlkklFcSZiXEacQ1zJpaqMWQgq1lBBlQWNGqOo2hgzZkGbnAGs4FZY4VEDfYjLwkZRhobKkC6T5gvF0J4RmCRb/WOOpRnzH8vPfy6QzqcZExjyHNzlCe5yPJGPjK+484+6mgyLmV8vr0wzlGnJ0XJBsvqI/ix5Pkh7rUoT0jynpfMze/LDkOKmgFckEac6rAuuSBLiCqSsmkCpyuB5KB0KqZgGtvcK0/qn2NKMZQGlqWa1UC4ZqRhVq6yCukC5YmVqUAUG95RCUinoQkpLm5ZeV9FJb8Fi8WE6MGdli4UUYa5EMNibPZisRnEcp1KIuljBXVNyLUu2jgwsilZiZfy212MdPWv+SH68UKmUUzF9WMFLc2k+jam9Ka03Fs7xt1xJFYSGMjU9ahJRsQReVxans7gJUyW0THmFAXxcSwe9QuzIPGsSeTLGTNmfyxM/n5uUzXISmkAbYocf5Hh9rMzjxUKhIYpzo6XC+43Hcxes/PKkhqbLNu7dXRoeGkmnUjIiGTkJSSECM6+ZU8gUE3pQLwiuFTrwMgzhB9wDY2NjQifyfgFdEp1MD0eb6FIHC3hJmSbIcvqbxg7Bl3miMamG6SWU8XyerlqNKuXqCeZydJ07i5UyGnPZKKYBI/q5FVSFFKHFYhjgARZi5dSlRWS4plaikCEJxGBeTdedEAvuGhHhzsUtX28O0cd1eB7foTtsIXl0UTp5gW/gM0GWvRheTYBePT+Xk7yyy6mw5UaMt6ADTzsjovj4SCk/nkml1ZcnnUGinxL252LjmSga1KwrWKK4U8TxkSGcUkls2aHA9Xyc1gZJRIq+nl+dPM/XiXUyhOzRGTtYIjfwIbsEdihdiCdasbfY1GKqUqlkIw30eGLuD1ZqNAe2DmZ66ZlbG9IZdrYx+YpEwTHwKb0aM5/JF48XYlFIomKP5F7r+IT8EBvygXzq8MXH/Tmuxr4uP/BJYiddz5p+NX2MmcvS07Ss6VxPE3QiTHiSy4eicqXCmQPnM8Cjyo2rK1fGZ6xeWYromrlUGmzOZkRlmr6Bgb0TYn8uFk5gnMQGSigDiqBOEUfi4QHPAe3NKzoB3wnVU4j2nJCfGNBjOEYOL/AjTCZwqBPx9PaiDCmO4sepTkXDZyV6QqB49WpOj5QXYausm4pT3ojGOlHc62mKCCiF9GchUdSgHuQyAyQoPzGWTgGPZAfxIbWXEeTpVbBAleT7RMLPEBxWja9UCzw9B4+nKKE1NK85+XqUhJZ9YWqszLl5qvqsUOPlfCiQwQ5NbTgPMmamaJ2AmnBL6SF1LPYMvDAv1PF0WS5HZRH0gJiQYADLDkoHPgG/Xp6Ta+wSfjU+XkAixynh+E2k8W8W+fwX0oV4zK5q3C1Wy8M01TbxNi90ukd9YmNGdFLds06AFcPJlep6TeKA7NCdQo6vIzAIB21poFF6okH1HvCMk1gbUoD6bJOntJMf5DB2iMYn0HoWYqSk8VPSvQUa/2ZRSAcMR6M36WcxG7JaLO24e2/n9L1iG6/Wk4HLur1aLXCmbVJMUa+Ziw6hsNfIcpxcU9SSJHIxQaq6Ri6ONBMf4nqkWEbUwNEtoxGOME+bGDLIlWKBTz1eIvd58gNN4BMUcdIk0ssMsp0CQncp5XuY10GR6UKStBtUek/+7nuLGlMST+QaeFBGjG1WSkyjqmNmgAAPwiWUGfbn4kSYEhzFkONScqSAwk07aMAyUvM6ETXlULxpN0rPDnCb4P+uIRNjeP0TXamegRSHPIOpRC4noSXcDGhxhT5BRwN26oG1x0Tp5V3HGEVUqgxVMm4x5niSlbU8N3GUbSWMmwoUock1YyKIn0GYlqdxx8OaK72eWwtplNYNILeoB7N+9xa0H3M4Mu0tqOQLGNmyE3033Yv9n78P6dMmA9z9CPy8IEY1fTh7IP/nk0uRh8oP9Ens9FfBgq4W0xZONnW2PFnHlzLQEiLTqVhqzPS+HcJa3fdkxK2F65Wmj8Zjmv9wIi5cspBi4nkAM8L+siGJk6MBnxlA6xuPx5EffzsybS1ii0qhaOmOYw+HPjsWzEPvO69F+hQaslC2wkhbGUU19Nca0mq1voK9EcjI81NkBaszJGEJjcuTDkwpSnQQj6AP29hulWc5P2lnQqZK5XyJrVu+JWIjUM0bz7/CkBKb4k7g/jyyJ07DEf/4NjPa4NMbseOntyO/YSfS7U2YfO4STH/VEvSctwyFq/Zhz2U3IXNaF3f0ShQtK/IvFJzFifx63krlHtLSldLejUCYzo4spSe3ghuQgPoW5byOMHmfWLGwwSOdDs6M5FzjwbS6PaLuYdJCfNGCBWYzZDIFumqNl7KJbJl8+JRj5rL0dPmKHReXz36u9OBeTL/0XGQ7WjHw5AY89ZIrsf9/P4zixn6M/34zNr36X7D5P2+SFEx/3RlIn9yJ6hgHHWsIjp9jyXSxgsreMZT3jaHSz4/i5DOOygDf9dmX54fv/Eg32XaCXhLmAS6ygtWVQggBpZanUkoXeaG42tjBzVrhruYn2SlMFQulaibDnVctCsVA/QYpRPjXeCQ7i8pYEamTJqNj4ZGSg23fp7EOzyD9kkmojhYRNWeQO+8o7Hr7LzF52UlomdOD5rOOxeC370f6mA5UC/IYqU0d2FfG7Y2k7aEutuNnxlHv6O3Nd725YCnqUHpqF7d3VQB5mcuXEQzXxy4KZfUeSbnCnpgnkU4fZWhPtByBoyKbM8eUxIgVpMsqP8VquCRaYEoGJHzRhtTwP5hHbsFU5DrbUBwawfijW5Ca2YzKcEGsufjkbjy9tcod+ZEt282IudndqG7iQcGxMgflsQajbIzSY4OY9OnFmPP3F9tyyyYPxuTQD+uzOKXad9+j6H3LfyB90iTuW7Gv1TRLJM5mViYzsNn1xRnSJJJNmZVZKWI4aFAzova/M/xYzcnyL2RIn0/j1vcxvg6ZyXpjE9QaU9vH9pH2CtKXkWrWYu4TG7jEglqC+Uy4/okAnqaUx/OsjFEblMyIZg0jO/hB4uykdnQuPR6D7zwBY795AqlZHNSkj0olT6trZaarl+daX8j3panPk4YEa9uQ3f6ohF/Pf4kRMzQgRagFM8gTVBBX1HqhziO9ZwrzQEPSyaL2DPK/34Xxvn40z5yK5tOPxr5PrUbu/JmocM4YcZJd5QASH96M1sNnm8Sx9dsRHcUjmrKarDRgKBBnXiuGb30cT926VhCV2R5OT6djgGtGUH5kH6b++5vRdfbLMOVNr8SWn/7ZeLneQVwPLtOLNqSdcXG+wtbM9qqOFxpT2IJrwRSvvZqB9Go+w0zLJ4cJsfJlcYvtaSuR8sZB7Pn94wY/7O3nIXPWNIz/aiMqG4dQum8P8r/dgplffysap07GyLZdGPrFY0jNbmEfKI90wjxX41+tatTWFIifSl06wBRz+hQd0Yg931iFYv9+tBxxGNo+sAzlp/cBbTk3sdfknsa2kjsxKoDp6SMraE2HujwiqBKZV+LuNfseFxJPDADFxozIqu3E00j6Yj0S4yVOoLvQ+88cOE5egJbDpuPYH30CO2+7D6P0uExHC7rOXIxODjwy2rZrV6G6n/3ljCYbSCa0AOpgg0xtcSWA1KyL3av0jttzrKQ+7L55DWa85TXoOn8Z9n9rDYo/20bP5+Finp4+zP3AE9rYYmhYzU3JL5lOmaHMUoSHMjMOHiyxiEo8rLIO/kq+J0aMyiUe8WaMl2rBDGik/wNDsi+MWOOadjz9sW/iqC9eita5MzD3Lee50tY9+x56DHs+vgoNrz0cFa6rrc/z+U4PNT8GLSGllf4IqJ85GIIZliPnWAmpxZMw8LU7MIkjf+OsqZj6lUtQYb/aSB0q+SLyW3qx/ze/R/G+rUi9pNMMqYp5MYaUMSs8WcmXSjqnxhUrr6iNzsUUYh36Ur3wZx7g6uB/YEj1ed2NKHCq8cSKz6L7Y6/GJHqlOv3SyCjyu/vRvfRETDr+aDS/9aUoPL3bvKhalnxK9d5mhgwDgbMWn8wPMLkfcZMWI1oOVpX+PHZdfwfmXPZmTF5+sspbCwuPwKRXvgy7fnob9l91B1ILOEelR/5FQ0qu9GJdsSp04G8h8UQeOat/1O0Ar5Bi2p3VTlJZt6boAYUIzcHiOrwKm3U0mWfz9Mzed/wMvRSRms1LDAXeB+jdjtQfr8HkE49Bz3vPw/qlVyO7YgavDhSteVGYU1j86uQFeD3sQA+yWQEL27roJaSmePaV+x58DKNPbkLckEXb4gVoPWYeethXV8cLGPrmvUgfqfnpXzCkWcGxbKjmDmFE8JBKJqPyMqQebprxf2ZI2/biNCfNgUUVAXpaxJ2daGYOW7/za3R+7Uh0LzkBfZ9YgqHrHkV6fnvSTwWDOXVI573P6TbRuMGQyMQobxhE67tPweTTTjQDbvrn/8TwFWvYdDnV4UWRfc/diO4b34Luc09H9xvPxshtj7O5s8JtaWlFP3TTliIuVEtcHIWXZHTmzCJN86WcAe2pMjAQGmJPlYzGKo37Y+yNL/wD8bSepJJSVEatDBUR00NHvssJ8V0PGvbMt64Aelm50ojVaXNLxrRbLa08NSfGBuerSavTQXSVZ/LoPPMk5nKXYNW9GLriHmTeNAcxvS11/CSkL5iGvjf9FCMbtiHT2YqWFcej/Ox+zircrr7orAyu4CxaKJGzGzWoljOjAYj4+rVrpSZbXCGtDRwRcG1ojdiYOW4vbMggVATyZ+0hKs0QFEhiAcVdA8DSLuy4+pfI79uP9qPmYMrVr0bhlq1urcxVT2WwYIONNjMqHL21oatVj+BqerZLTkGJIVU69cWLWtHA+anC0BpOtpdORpV0Vc47NfBYRdEph/68znByc6YD/YT7MEHXgwxpvVNAtTjpE1OVLNuzqthY2JBY2wb7C02bgmxaogrYwg2ATSNIv4zLLV0EoBhxDPkWSzRdP2rJonBbL7b98k7Mf+cFmPmGV2L4wadQKfmm5WvCd+bmhCK1gWMPVzC7hxF3cNqiwYgVY81dhVZ3kXZbANq7lHeaDiKWyelQVc5uqhyxFXiFivnKYTiErqGrMMsQRYswgFt3PqQv8olKqsybXhkxohSZz/Ris6Fy/Cchf6mPxGAZC1d9EoPrN2PLx3+CaFLWFBOzgwwpRTiIpM/sQt9Vt9qWWGPXJCz83idZSK0+zfxeuwMjLgVHx7H+n76PsTueRjydbmWbutQ1m2ZzHrDJdm5yB7KH92D8xvXILG7mDjsn4+KrdfuWAho45VEo7OZkXKtPFdJHQkt0JswZ0rL1FqWKY1LQAl3PmTEVpTI67eMNiYSTJWQAM0WQIRuL1kOVbkqj+MAuTP/oCnQeMx9dJx9LA7G61YcZvfBFb4RK2TsaSHdXPzredxpkQOVXuTnx/AZUyUjKSDvkM951LiqP05tcA3J6MV3ZXMDgn58xGd3nL0fUmkXpae1cSfcKJ96b0HT5SehYtMDW9yMPPInoSDfRT8rmVQw626uHkU+U5oVCV4i6yXa5UmrQ9ULtlRmh7Kw0q8Q86Xk8Uk22MjCO3JmHYfb5ZxrfjT+6GaVN+5Gdx9pX0xQr8TGWzgrm1VytxEc1YtZFZxvdll/cgV3fXIXMbM7buGEgfAtyCwbdEdLAlKYBj/rC+9B29Fx0fPlMDPzT77gzzu6DU7cqP6lXdmLvv9/J0fkk3hvswdxfXIadP7gZhce4PueSr+O752H6G19lTX7vPY9g7MdPIb2ky2idB1JXltdN8WQG3x2pEqgHP/F4lHc7J3xP64xACnLAbnAMiCLMEF7IkNyyiFrkhVsx/5bLketoQz83YHd/7DZklk+1fUXjSXOoOdQbMmrKonj7dsy89q1ontFt6+ftH74O8ZQ0Co9z512Ky4zSzjR0asYtGYz/eB12nrYGh/3Nq9Fz4Ssw+IMHzOimsq2WuBGxYxibvnQt5n/mnWg9cg5av/D3KHAAi7Pc12zWvVJg/xPrsfNTP+HepybbquxDdFs2V/aGNCoah0csmSo7Xh8Sl0zF6QYNA+aJsqIZ0ltTBhCBwExbUhGnBKXnOCd752LMfMXLDb7xBzcCHXVTBeEl9J6PpiGD48i+6jDMXLHM6LZefzub4TjiLk7GWTFRWxbgbpBi93FpeX7m7BnYffXNGN2+G00zpmLKR85hhfTxGFYDBGVohJ7RgrHfPoN17/9X7OHeYnH/MLLc35QRS9xWUyjsGUD5Xu6t6jhX0zBXSqnLwLcJsRXfwXiynGWDENaVK6/UQZULXA/yerDVhC+yYyK3NlcQlPnyBwnTSKhLyqWN+zD3ZxewatLoXfMI9v7LnWh4xRxOKbi0JLLxFIdAL0/hznbh3h2Yfctldnywj97bdxm996wut1UmPfjPMZBHKhkksy010hDPDmPHDXfg8A9cgukrTkf/uWs4HRq3gUUl1bw0ntWK4pZ+bDn1a8icNw3ZuVNQ7h9BpqcTh3/+UkzhcnDg4w9j/I5nEE9rtlHeykaJZFHXpAlVeamG0wupUrrIVTLXzvzEy/lQoIfqAjmRdXQpZBeUTt6knHIE4+F74Xd7MOWTZ2PaooUojeXx3Ddu4Db+ZDep9hwSzzU2JJT3btmP5nediJ4zTxEUW3jWEs1ifZo3SAcvQ9KSpIS6oEm75n57P3wHdACmc5xp/+tclO7e6+aomhOzMNZEm9h8z+tGZTSP8Qc3obxrEMNf+gP23PNHY9b95rNR2Z7ntEmGczK8oUy2CuvAgoY0UpUSd2B9SJoz35vkNbrcHTQXkUJg4l5q79qbnP+3bmdmy2/XYOinjyLu4Z4gO39HF+hDTKiWZU8PYvZ7XmdNa9f9f8LAVfcidUwnd1jqJrymsnEJ6gTBLpah5qax/b9uERKmnrEYTZcei9JO7trzbMXbg6M9S0Gj25xV63hOgVJnTsbu79xsRxdtC+aj7SOn8UyG0xxNfV7QkBTNfzQTb3KmDjYiW62+1sAdJ3qiapH/FJLYXh0s4pQmv2YHev7tAnQeNRdjewew+YvXI3PydJuLmd8btcobDEjh7IuLa/Zg0hVnoXvxcdz2L2DzN3+FeCE7dhXUQpDIF9F6ubWk50eDp45ox/4v3I++B/5sFTL9XStQ+cMIh0v6BgmcaB/rXRu+XOloylO4bhv6brvfJHZfeCZAWLKr7ggPKjvL4qeLusRZ5nSdxwNc8SWeyOxmqad7d95+NQN4gPGWgUcL3CiYjPkXvsqU2PjrO9lUuOnJFYgUEV6dKSbw0RRk9iXnGN222+/DyI+4o83+SFMaowpGMwzPJ8CMr9CYsObKKdKiduz4zo0oc2WiDeC2z7zMeZUNngcY0kmwCkudMxl7vnIrxnftRdOsaej84Fko3dlnqx2JTiq/ruxSg15YSduBqDOiZtnxaj4UOFA0i7Ci5iwTmMUOZqaLSYU/7sDcL74JzdO7sI+rk63vuh7ZU7nhyRWBqC0wUW9ILcWKd/eh++rXoINTjtGde7D18z9Heul09lfa/pIsR+NE16gtZYyll3AY9KDhNZqP/vAZ7OBGg8K0i1/B00ZHa3jSwhO4mKQa3Oit5e0j2Hndb41u6rmnIfOaHlub25qc0MQGTqKTSWCKu+zVVMo8UYuVxBM5CnN4cp4omfZxWkxgViuEzxQRg4M7mIpgKT58yhAmUvi8wJBxoAn86qiNj1AFc396MUBdrHwF4bi88Ay0HuwoheYIvP61lxo84WB2kGFlNHV/HhtxuNBE1BYhqE+sBRbMcwu1Uhkv8nrIdGy8nFtJvX3o5GndzO9diPx9/MYWR0LDM5qaUZRSM86cPgW7PnITBtZx2TVtCmZ98kIU7t9hy0aTw4dIgywn2/MxpXy+sPQnb9o1gsa3HYUeTnMUeq+7A9VWTZHq+FgOaQVkjuVx8It7mjD94rMsd/eqe1D4BVc0nH7ZytfrYhSO0PBEqwGYDceMqMVK4onMadbJrGvOTpTJlFCXcIXTpiqNVdjYh/XX32qM553/SuQWszkPaR2rAjgaGcNI+TAYsTlPxaYfuRF11tlL0XzJQltdaNS24GkOZUjHyymjfB29lv+4DzPe+1qkchnsffgJDHyWtyhewl1qP9InfBxzK4sm5cXb+jD5Q+eggaeNo7yhtvea25E+Z4pNz4QUZDlp1NtgBudBITtGOp1TmEXGgicNj+7ZrNVKucILEgpMu6Lbi3v1EPV92aUzsP2DN6D/mY1o5G7J3E+8EflHOLhwa0pGjrg8U62CtxgSRTgCZ86Ygr7P3opdv+eA0pDD7Pe/HqW1nN8Jr055k2o6eFUSLq5A1sc+1Y+2jy9F18tfajvY2753I+LjedOCOzpOa4uMb/LOSi5rtfSGWZh6zlJD6P35HXaPxzaDqazpW6dLor/y+LEFROSMuJwcYqxc6XAiNKkp2xSHbITsyuBrxcOcMsyknvQFPPvDX5sis88+Fa0XnYix2zcgf/dmjP9uA8ZXP4fSQ1xWcWKuzlqCqkVOTXgEsPHbv7SCT+fRQOdHl6H4qJuneaGMnNzEk0zLoAsZaSDaXMLMt77G5Pfe9RB3ylkxnKfaMaignodLqkBMUZfyPf2Y+r4VyLQ2Y5Dr58FP3o3UsZxmscsJEpw4/5bw4TvT2rxmu6l5onSRELXxMhHYnFlaOaOBfZlqrIliocpLS5nTu7D7i6vQ+/BjSDfmcPgHL0bHpUtw9KqP4bi7P4ejfv1RdHzoFBTu6eVONvfy2GQrvBcTz2nD/u8/jK13PmC85vDAqLKHXYFWDYlkJZzcCYaUAmqOv92NKV85Gx1Hz0N+YD92fPU3XMVMsR1zFSbQJrEkpemF24fQ9A8L0b2MJ4Bk1avJ+pF+apaU2RXSnl4HbwhiuDyKqBlRvNdetJKrfXoi54huYJHFJcMzc9zCm8sjF23xp2dPwbqv/gzFkTHM4BHo0m99CvNesxyzTl+M+a99BRZf9SEc//DnuDmQQ5lbZjqP1uZomncXN3/5BhpgCJN4g7b7yytQuIs3uZqpCquZt8vNqLaNLOOqyxSMg4n2HONjWjDzQjcobL+Jg8KtWxGHCbNTm0x8CXzMy9a8ZjKEnnessG2wvvsewRCXgKnZrZyE+y7A0yYVJwMFellAf3qvok1Zq/lxvXkfqHnUrJuyNCI19cFoHFcSMSRmNYPafKsji/yTu1Dg7S+F4vAotqx+COuuuxnb1vwBJW7BTzv5OJzww3/kRi17ARrAmkRHDuN3PofNN/3O6OZefI71p+XeYXe2wnNju284EGKerfDeoZaU+bs2YdonX8sttKkY2b4LO6/8DdJnaH3sNj1MS6d2YgBbs68dwKRrzkbnCUejxJ3x3m/fhNSSDi43uUzloJCU0dNOMKS0JNwMqHTkjKik7eKkea5DYENJSz6tWORl4qihXIR8aFB3IKnIN01YOXDk12zAS+/8PJo5Zdm/tRePfODLGP7VH4nRSLwxdLz9dJx41QfQyQn23C+/Gete/1U0LD+Mk1p2B0t7sPXyG9Cz/BS08GDpsO9cgm1f/w2yc3iwxL7TJhLUxdUq39ivgkbUcWjYQtv841t4rjOG1BxOc/09HrdzRP3ULYnYFGe8tYRJPEZV0JWW8R/x2ODc6axcnkKqrGbI+tjZwfg5CzvnYZpmMU9M7ifSklw3R1nniTIeiSko2b46hCHVrMp9o2g8i4fvpxxvBI/90/dowKfQQJju48QcpQe4Ybp25hQs+tw/oOfUk7HpeK5QdDNMd2t4mFTePoyN192K4y57G+bTG+ec/4pgNSts/SPYw74Jy1sOhcFhDK1ei/ikNvNQ4TocX+mqfG9IDRrxqW1c4/8Iwxeein2/vJ/vWrPLCwMd4xcwpFUGv4tmJuRup+Tpap015ziriSOP9P3orExZRYYUoYsTiPGy5vHMEG8Z8BsB3CnuX78JA999CNllM1HWSRz7PRm54dQ56P/SAxjmxLyxqxNNS+ahvJntmpurujWbOb0bOz+8CrsefpyTXPVLJk2SDwrKkVdU6HG61ZDlMcGsD78BJZ7vaGOVDJxuxDOtSRBiy6DM0s4h9F7yU5T6hu2owMn0eKLzhZ0YC+7soFgDMO1uA8tF119XseZcLpebs5lczIGF/+jYZERdvSr0UTE4sGlbLqcrjTyyZFCfWNWPReh+IWmdSCWYKhSsrxReiqN4hWe8NgEQQLsxJ7dj7d9eg2dPmGb4JlrylG/BpwmQF5YHx9By8pFY+Kn3YPqyxdj5/kU89VuHFHez7TInmUt/6SBPtO7IBPKdU5z0q7vdeYwzhhko6QIoleBDeqRUUS+m+TTZy4hmFTMiB5PmDC/j0BNVZNPYMRKZqXKwIcWN41F+D+d3DM3TuujW3I1Rya0E1ISjoe5cpxa0oambp3k0cJ7Hk9FMjmPe69g6bEMUPF7NP9pLUjGwenAq+rcEzuy4NYM9V9yIHcu4sbtsEWb/3euw9hsr/SgrMuqsYhD3IENSb023lClJyW69DEOYL+3zG5J4msUQu/XZV/9b9ohbPpB3ozNSrfq2OFcr9FbzZ2PmkxLFf4oUM6U/7svpjt/AdY9hZNcetPZ0Y8bXLsDwvZz78QdV7GtoPMoZfehBzPrEBci1t2Jw03aM/NdTtmaVcR1/cmTB5MFRJ3/QpDOL2GKmOfIHmEvznTBd0syc1IMtX7nBPHwyb5ZNvupVKNg5C6dQ0lWauoRSTmef47INSriPReEJAiTRz/gQKlzWjro9VkBL3LLdmqEZkS2kTbNwZXpEJ6dOEVNKUKePFdzWoOzrNvhpynHvvhhHfPvTKG8aR+G+3ajuLuKoa/8ZR1/idr83/oKHUWzydvQpw4ldoiBftBfJHyGxPUndatCutJZwitVNWB7THLSiSY0Y+9U6bL35buMzmyd/8RE8O+ZcUmc/Wm5GjaxFzksVSOV094ZyQIOaEk4bJV3K50zUT3yYrz6RVmwojaWtX7TmTFibFjJqzZ6HCZXDO+FMyfcD1Jiwg9ca+pRZeO7vvo/2+Tx35lRl4XvfiMPfcBbyQ8NoaG9D46QO03fDb+7Ejo/9ErlTe9yqwitkTUg6JU2QEq0pSrI0cIonTY151mVown7adGz/1A2Yeiq/xsGN1Z6VF2Djmz+LhsOP5c1bDj67R5FqziH9cl750MV36m1lUuwKJOauSYf4QHmyQZ1+7NesOfNXexqyuUyrCmdG5NdzW50nurWjMxz5k+D5DCnOVjBOETInTsGjZ+jLPu/CvBXL0dw9GU1TeJjuw37eTH3ydV9Cbinnh5yTOf2tVlzBCJCiUlAWmmBQga0gXp5MK0PyX8xdnOKzI9j0k1uw4MNvw8xzl6Hxnq/zKx0zTLcxtpK+ux5G/+V30eD8YqZmBOrLTZ6LTcVgwBATaAYXnuSZ/FDRGlgq1Ry3kPKVQs2IxLOJY0nfL/GhVibPhEiugEJwrM2QAlNI+pSpWP/Ob2HLYTeg/cLjketuR35bP0684lK08c72Yf/2t9j6gR8jd9pMLvtkSJNg0oLCTkSQQxlm0CBNhnYFDwXTDa/08sno+8itGL74VeaN00+r3YptmTkNXYuOw67TTsCGd32Lu+DsZ7UrHfj42Cvxlz3SFV0KVbL8jaFyKW12c82ZSxgxLqvfYWBSTzOOc44XMKSwVG4WKLfkMIv7r7mP9BG/6vMcNiycD/WVOo/p/dfbbL/OHU8KIwQaiC+q8QA0iXyVLvJcqcRoggE0mS/c1Yt5v7jUDKh+c8fq36P/gcfocRV0nHg0Zpy1BFO5U1T97nux/vRreLZdN735az3StwCNzrq3VI7K1tzcZJtLGJlMA4uzoLxABRTUopCy2OXV8lUBClrKiSDNi+cZ9kNNSxdj83t+goFN29DC85i5X3gTxh/ewIkxR1CtoTWQmUwNHlq3E8Y4wC1PEut1oRyTxxVTadswWt6xELPPO8PkP/WNn+CpV34a/dfci4FvPoD1512FtVd+l4dYRUzjvZyOlaej9DinZOwGFILeIfZAFUGZLq7HE4R/UlvdH72at+b9BgQNbJ5ohWB9J0rXK2/0BiCfUDCxcMKCIupztKtsmwGUVuYvf627lldLGOayv2y/8GWobByld7ERlDiC8gN+cSHil+JivevLcQan31XU9EQZ5DlZfLXRt7RuL7rOfRliLh933v8odnzwv9C44jikj+eN2GPa0fjaY7H3izdjO08VFbrOXITKTq2WQhllK18mHxsi006sjwlM8Jij2bSMyKmGeaI1Z+K0adgucVfb9VVkIS5spxNGSoEJs45WCL7PErKgKrHrtNUEKYx9X/bUadjx6Ruwi94y9aVHY8l/fAZlrmD4YxOGb0pLlE9IrPikclkMbtyGP51wBUdXLlNtdKVk6SQvMMQIzbO4gcDQ/8iTnF+020Ra62Tx0ywqNbMb+x56AoedtxxNTEedukKnvj+UTeKC3i4WP+ng5PjYgO5RM2idESmQRwNsThpYZGEG6WiKSmkzFmOZjxl/jSGr/PJNqq0dT3/jZ+i8+iPItup8R59gNiYPCNpJ0gCQ4/WQqpq48vkwAya6GNRGXGVXuOsjniRNDGAvqiszGnNVcbodIQIGpZLB60UY0gxLOhlR3kgG9Z7IvURKd32iQ5KQYLRDeaS3sNQgojzEUYhGwoJHam0cH9mKoVVrcff2TyA7zX3Vwba1SGJk8iyRM7iYT2576f5MzFWR3VpgjumdVKpaUxmjnMYotPM6yA7sQ7aF81Bul4lRzK+iFbZsQeux8w1njAf1Zc0dU/Js7xR/hSGtkN6Ajrpqd47TfzjpPRl6FjdkbXSm6FBPkusFCZQo72BCc03f6nOCIVWCpImIVFc3eDyZX78b4w/wWJLeYFtUdIxgtJpRVXoS0aO04ogncWWleuK/UDHmkdyJTk1uQ9/qRzCHfa3W0Lt4i6H/q7cj99LZxriwZjuaL1jA+ePpZAjsuf/PfHJQUb9t+htract35wgJnAnJs8C0mrYREaCNa52KEsMGlnRPT0+mUI2a9E3dCkdGSbc2n3iHIXvHC8KogeHxqfbt1KAQr4hBJNMXXO/0jqiFd3T5fbrgd0lsuiZv5OkZSB0t+fiu3ISfRPJSZuq4Duy7+h7seN0y7lWehIWfex+eO3Yu9v3uT1bgKW9fhnl/8xp3+XTteuy+nMeinFfq4tQEfiauVraaQScaUopJtCyilku1bJ4YPbbi8s62hsYN7A87//jMk5x5VNh1yBUYEkPai4hUGnuooEmxaxkGMyMkuWJjCM44ggceYsWQ5DPP/U3Ed0j18ny+zlw0enBr7diffRTd/HaWgvYb5TW6M6kwuH4Lnnj/V1DpG+IOUM4qRvBEbtBPwHr9nJgET7opn9dIKtM6O2P+LOyGkVT1mDibatDlzqyOBuSiKqF5ovDlxoot+LQB+LA/l0s0Bp9mHN4dRGwm4j1vvmMqDk6iRZ4LowQe8rVJwaUc2lN47KTP4qnv/RyDz2210V9f4xjicnMDd80fXXElvwa3nzduc+wvOckz7vV6OUh4Jvp5xKC/ETKTg7Dt5JBDe5ZbBOmUflG4ms1oUNFJn41gMgmRraYYhz03Vwx6EplbE7OYePwnwQc3bRXb+Wvg5/DE3+EflC8KMk9mAHV8VQiD1+dzl0dHsalTO7D13ddiO36O3LlcO9NLC6t20SuHkF0y3a2bdSDFASvZZK4rZ6IfYWq0yYyEsuSoIV/2V9qacxw35jLVFv6QcLqR8KxNcXjmzF/+m1BwcagXShY+38ehYAcY0vBMgYBfUyQo9D83JAtaL1ceyalQZpl+bIO/LLF1gLsEdNKXtyKd4WxA36KiB1LFWlmIF5yjpg8rUC3xeQzpa966EDldJo4bxlOl9jgq0x3ZB9KI7Cr9wGKGks0ZVFIf+5SAHiwD2WtCkaALfiCeIB6hFns8RQwJXJztz0l1ZC4t4ZY6IF871rocoEuoEXe/NTXSoZjDN2RPF+h9XCfXhOpdyvAZ5Co2mJPN0bnC+1SpVLqabmU7KDboaCDsJRpbh+0ZkdhxUiKBTRAgqP0ZYYLv32qKmGI1foGvY1/jnYg7iK8rmLEJukyQ6/LtirHW4AfK8xCDJ/T1cpl2mU6EfwaYYmVLb/7TTg5du9LOxWkqZ3uJkqyBRUj655k5SK3gPsPwDNMjeHSjNR6OAd9fmN+hDRnkO1oxkU6Orz0tLV0Oluvyn0//RJ5n5ugD94m61iQFfZwOEqpB2NbP1bgzZoXxm1RcHRBo/3zhvQxGdQK80kER4Vi+L4mPEop6PMfb4xsdKb2sWlyfT4pEZybszwEcPGR6/Q6RH/A85sHyTFygD7HXwYgcZXiKn3TVR4cAumLHn0zsjDlYZTX90VrQIQtROutNBJ6pIgUHMEYOYMCJeAm90I2BRz2YX8ivxZ6fUdTR2qSeQA0OUlgFSNIerw7dyPUwWF3ZHOAAvQK2YxBUDmUPuS52A0/NE9HBvjHmQZ8N6l5BaegnHqasSB2sNh1xBVHBbRpk3GUgFUwKy7fFxaUSvDp+iSGMViIchWQ55dWnEcZR0Ml3iMbCUIMR9cKP/fmYvOglHHxpFGXX60UQXx2YgjhBIrZGbqezZ2T5SkstfVya7yRWeTQdtBDF7fwSnPNClbjAr0QwNiSxdu5KQs2tjCGfiTAxdwwVu+AMKSYyhKCa14nnhKA8o1FGHW/KYY1WtWKK4jTvlvM9xf8agvA03wXXpXMd4FvM3WX740P9E/P5JGc9LHZ6GYCSDlKDShrMNQM+FbitISCzrHUKhzBmWJk00bblMS2v7UMitaf5w+88ZYwwuaU1OnnhceVCscgvIpVQKBZ4P6iMYqkY6dhAy0HuNOuQxmlGQeThDEWJMoX9WcQ3Fly/2c2ChcJXVXh+iYa373kLgR9+o8bFVIBwpa1hKI/vvOBPY9FAiu1Hg2Ua/aMMyZavWuEYa0zUJK1kRuBkTQgEEZVZVpMGIMxrWNWPhsg9ODfmhwpLljmOx7AqEbrxl9dKjjsByFdK1JDUcdSR5uR097786Fg6nUnP6mjOaLojhUUoS2tSyc1azlXLSVqz9VAzRDRc8yjJ84WUQvQWpxyNoO9+yHtMMIVLQQUpZYqRZ75ckhF4xoAxlnyEMvlDBeUh/jgT12z2K3EDlDvIgg7STENRFA8RbziuVEbYyrhdHudprgIvIRS5WV7iwoE/ApQuc+LB3zC1/1WDMxKuLzLFKC6kU6VsOZXib18wJ1st8xtS1UqOG+72357QwPxqGI+SeRLKwrbT1p3kzSNDfvgVUJazpT8/Oo94NqZEG89f2c5f05/Kr1P3cMiZGUfVGZzvT6Mpu6lcF4s7iU2CV6h4jMBfSuE7ryFYlSqaEEJ100cKrCde0KnyP4iJhlgp+2mv/UTmcqK6j/3nPrpCfzmq7KNJ9/JsZR9nr4MRDVYt5gdHy8XRhe2bx6Prr2eH8/9f0MVYbuG0cEMo/d9w8ObyCo8yyQAAAABJRU5ErkJggg=="
          ]
         }
        ],
        "meta": {},
        "name": "icon"
       }
      }
     ]
    },
    {
     "title": "🔴EventBridge(Bus)🤍: Requests(RPM) - [Filter by ${eventbus_name}]",
     "type": "stat",
     "description": "Invocations - [Filter by ${eventbus_name}]",
     "gridPos": { "h": 5, "w": 15, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "req" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "EventBusName": "$eventbus_name" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "Invocations",
       "namespace": "AWS/Events",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🔴EventBridge(Bus)🍃: Failed Invocations🚨 - [Filter by ${eventbus_name}]",
     "type": "stat",
     "description": "Failed Invocations - [Filter by ${eventbus_name}]",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "EventBusName": "$eventbus_name", "RuleName": "$rule_name" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "FailedInvocations",
       "namespace": "AWS/Events",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🔴EventBridge(Bus)🪩: Invocations Latency - [Filter by ${rule_name}]",
     "type": "bargauge",
     "description": "Ingestion To Invocation Complete Latency - [Filter by ${rule_name}]",
     "gridPos": { "h": 10, "w": 15, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "EventBusName": "$eventbus_name", "RuleName": "$rule_name" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "IngestionToInvocationCompleteLatency",
       "namespace": "AWS/Events",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "🔴EventBridge(Bus)☘️: Dead Letter Invocations🚨 - [Filter by ${eventbus_name}]",
     "type": "stat",
     "description": "Dead Letter Invocations - [Filter by ${eventbus_name}]",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "EventBusName": "$eventbus_name", "RuleName": "$rule_name" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "DeadLetterInvocations",
       "namespace": "AWS/Events",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🔴EventBridge(Bus)🌿: Throttled Rules🚨 - [Filter by ${eventbus_name}]",
     "type": "stat",
     "description": "Throttled Rules - [Filter by ${eventbus_name}]",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "EventBusName": "$eventbus_name", "RuleName": "$rule_name" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "ThrottledRules",
       "namespace": "AWS/Events",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    }
   ]
  },
  {
   "title": "❤️‍🩹Performance: 🔴Cognito",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "type": "volkovlabs-image-panel",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "Cognito",
          "type": "string",
          "values": [
           "iVBORw0KGgoAAAANSUhEUgAAAFIAAABOCAYAAACzOEF7AAABYWlDQ1BrQ0dDb2xvclNwYWNlRGlzcGxheVAzAAAokWNgYFJJLCjIYWFgYMjNKykKcndSiIiMUmB/yMAOhLwMYgwKicnFBY4BAT5AJQwwGhV8u8bACKIv64LMOiU1tUm1XsDXYqbw1YuvRJsw1aMArpTU4mQg/QeIU5MLikoYGBhTgGzl8pICELsDyBYpAjoKyJ4DYqdD2BtA7CQI+whYTUiQM5B9A8hWSM5IBJrB+API1klCEk9HYkPtBQFul8zigpzESoUAYwKuJQOUpFaUgGjn/ILKosz0jBIFR2AopSp45iXr6SgYGRiaMzCAwhyi+nMgOCwZxc4gxJrvMzDY7v////9uhJjXfgaGjUCdXDsRYhoWDAyC3AwMJ3YWJBYlgoWYgZgpLY2B4dNyBgbeSAYG4QtAPdHFacZGYHlGHicGBtZ7//9/VmNgYJ/MwPB3wv//vxf9//93MVDzHQaGA3kAFSFl7jXH0fsAAAB4ZVhJZk1NACoAAAAIAAUBEgADAAAAAQABAAABGgAFAAAAAQAAAEoBGwAFAAAAAQAAAFIBKAADAAAAAQACAACHaQAEAAAAAQAAAFoAAAAAAAAASAAAAAEAAABIAAAAAQACoAIABAAAAAEAAABSoAMABAAAAAEAAABOAAAAAIb+ENoAAAAJcEhZcwAACxMAAAsTAQCanBgAAAIEaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj4zMjg8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+MzEyPC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+CmzZZtIAACq8SURBVHgB5X0JlF1Vlfa+9773ak4llXkeSAIkUaYoMoUCREaZg3a7XNA00Ij8utAWHH5NAWL/YCO2qLTYq8Ve6C+kVUDmyTCJzRiRyBQSyFiZa656w733/769z7nvVaVA1tL+1/rXf1Lv3nP32Wfvfb6zz3jPewlkRHjlxC//IAiCBRKkXZImpVSCgVCkXyTojdOkF2ldgaR7RJLdQRJ0VeJKl9TV7Yka6/sXr+wojRA36mNHR0e4Ys2iYNWOPwXt4FjluNonrkll8eL0qg6RFdKRkhyI6N2x/EU3CII4kaukI1jRgciaNbBhsdLa8bgKn/Z2SYKOjgTRUcPzH+9obIqLM9IgWQDOJcDng8DjAyoklTQIgNybJ3WMKcrQ1rZCY2M5SSQElboBnlrAEqVpKon7FJMK4kkR+QeQtgcCd4FjJ9i24r41TdKtYRhsrqTJtiiNd8S5oV27+if3HrOqozKqle9CTAH8ShR6uSxXDlbAu7Bm5PaJi7QCVspKWY7KeS9wskwu8vwhF+frpje0RcXCdMlHsyVOFgKwfYHFAnzmomqnNER1UQRc6nOh7Cz2bzIgYSgVrTnhysVBFP4hjgfSSvktiM0DRPij4BNEiOfwyfMZ2CIueeCUC8IwJxHoEXj4CfUTAGQReLGUAXgpqZQhpJdAB2m6Mw1kW5omWyGkE5I7UTnbwijYmSSVrqgSdUmD9MZ164uLV658X17uMHjP25rlHYXevl31Y/MNzUmctEkatcExJsGuqXCV6bB3FgCZgUJOhemTUZKW+qggOQAGZ0FZYomlBEcsSS5XimF7OS2Nqx+Ky3fnqHnVKiIlCZxyn8aoPuqu7IjjeHMUBg3Ibl5Or6QwZMYfgWXOEKCFIAKKMI97Dr4K8KUAFyfgdQQfWQvInc9HQa4NgLdFYX4hIEdaCF4ATi3IWU5oZpTEuXRQyjKQluf3rDnpK73Q2w++PphIzx+EsEE0IlRMWoYZMS2kWRCBWpUcxEF5UIf0JiThEzQgrSXtG2ppkeaWSok0dEZRXnIhK55WsHwJ/gGstCIxxQelNIkqSRyW0ygqS11UhtPEQRjEQYTaHhwam6blSVIMSm8pkO3QxgCD9s2FIbrGIdhbgOCCimcaCKqMccb8FQbSBmQu4V5EhJwoOlwuCOwOlEELYF4OBgLwJAcmAk+w+SkgOYKUPD0dFkRN8PQm3CeiolhZUKEyVBkrtTbwiVo1IGJxVjtjvAIgtAz+g19lnyTsTcpBjEqP0zCsSBSW8YGFYQUqEvdJ0YK9PrMBnZ4ESSSVChzFVLxpHulsQI4FQECSZEANILQ0Q8UAmBS5guwOE7UmmZm1CeCQZqCZQAMTfFAGY5BIaUXgC8ADNABjQ5rJYASwgR2ViU8S0MPDtJKyABE+8H7wpPrMTKxDJwU3jZEFuflAXzdAIAW2RwAHZYIlTE/hWVACXgPKSbJKV9nUY+XiI9OJmili5cRxDqSYstaaR7aDukoLPL8Cv0nTIaiiDrXbZYeQDETkpzyk2zBFBUyGMtR8FWCkgxFk3J3BKoN8kcmged4+pKGoZIdwNtgSi+wIJDJuujzRMSOBf7zolTEDwRiUrkxMofG4J2qb6SebglYDFlJItGz+7mkoQZzko3JcilHFG7RuKIMjVf2kttfqApnX3fdfKEUR/ktPoA1UbPL0ikcz2tGc8Wq9pSDBCqQZSTMRmaws3cuifOVRQo18EjWhmp7xViPeRrIOs63KonIyO4wRNOr18v1dqarWUaq6VT4AQ/Ps650bFMvB9rqgf0HIORWzhW1jJ8KAyaWkCKYiAHaegjR6E0N2RYSNNKsceqZnyOJG83mciEwWIhanGJfIW1WuPtgzGoymKF9tnDz+2e4ql/yUr1ZRD3ObgZkuUoxYo58E49fEjGU4zXhySZRyViObF9x/U0+4aPkaBbIQxdNzYa4pjouY/lWAIsleAGJaCBWvdLPDNKk9arhLd3EtAWWwDKPIUqqX6+7D5VJ+Nb/xm6xqHLH3lOH4TRQfaspCopKqNH325bZ0YzGaWYNhCwMmZiGU9g4lhBPdzD4IotkNmA4kaRG9J0c2ADlMaK0BzOqV+DtJXqXFXXbl9SkZXj6irC7V0/CoButds6spVgivxudBOoPX/W4yrDDGq+wuvyuHiaiVacDRkiqLxUnAQINRRLu+tcwbtuPCgLY8lzP1JMEUjTndVaOMm45qzWkur4R34xnmuaSRz130NoosZXEKfH7m0dzZPcttmvXR0eymNtTKGi5DU7QcVXaX3xid3FqZrkwunSn6ga2VBNNDPMDd1jFjbhWvCBhp55IpSYZw5XilPqkZOSIR6ZEjcJpDreQ494U4/cOFwceNrATXn1ucPAi+kzd+pbhOXRNJHlWW8rPrqZGfxX2mLK/J4qMJ5A1MRAGLLVYc7dDyOpkZjUCx8Ep3dycnxdSngqkPVkMG5A5uFFiYE2Mph6kPMsJlqUvBpBI8uovWAlGpq5NkW6dUVr+iudV+8pmsUWnvJ20YDx9oCqeQ+GiXBJpOJvhMLbCFE0LhSkrjpCETlq1kQJeFOIWQzzLR/GDMBAlnzUO2PNZHZaRxzghQtZwoswdY0VEiBBN0XDFix0kuGopLnFpvohm5c1euRJ+IxCCYVuEmRMI5JJQqYqOByVx5KT/4iDRecrG0funLEmHhBelIgJbsqlElGdU9V8nvEUOSy/TueaspGqs++qzDFWbazPsqW7fK4P33SLJjOwaKyQCz5MCEavOWDExmrQKLcsJDQ4zYCF2Y62KDBpDwsqb90mYkTsYKHG0bKw+4AWuHGbQGWBP4p1AV6qTy6GMybeVKmXHmmfAW1PL/o6F0+hmy43vfldLvngCYkyStVFBe3wJRWsadZ7KIFgdEaR5tNg9Iks5FD9yILUUHZFg/ZgI8clwlxs5GWoIs4KuoAc5aMOvqpfLIYzLh+9+XmeecQ8my/YknpIhaDSLmYaZqYCX4UBMFyZ6G0xw1IzJiFehl+LuyOL6MfRQ/zNKyCLEBOHEsTYuXSMP8+TLp8i/K5rVvSDo0iK4D+x0OOC2Jj7u76ee6PdKpTxCUNkN0esfy5Sw9nDOpTG6MGuoGkzI2YSroUDjRhKgRYCpQyDH55JNV5oY77pCNn/ykubVpyYrjbfd3Jvv4u93fk4eOD91aObzDSu03KYxx9JOBMrgF2V59prWcIIdNocqQdI2fJtP/8zfSMGeuNJ+1XHquRhe1ZKlImQsS9oVmpY/rnSUALhho4JGQl6YboFk4hVQgsfSeUgCmvdz14UqBzBBGq4mnIoqOOunukvzpZ0rDlCmSoIPe9cv/lMIRh0rYOg5ezq6WivSPmRA1Y8ym2jSkWJJxubjufaLz1z5KJUCGYxyVv0aZ6jIVw2RSTJaX6BMkeF7l96uk79lnFcjCrNmSFrFLh/yu2FZ+lkBpBqz5FfclsfeqtSfvUH47Pgok9kVmRFDCNwuA0MCDAEpFk1c4KEQ75Pp6CfNoAhVM2jkaFkvYH+9HXu60MBP4vAGIM7caoEmI466inVxaqunwqISy3noVI2qbBOivtBTko1z+6V0jKreWxiRlUs/kg4GgND7l4EGY7gT1DRJOn4lZB/ZaS27PmCN2VAc7tJQots+raFCNAqtlgWclCRcu4A0C9chVSDcgQ5mmzHxroNk0JxmHgQkqAAML9Wkadno0B3M7ZVqiGgPArAaQj+4NIxVMX0kUwIKgUNHEiTLj+zdLYfx46OEGtMlV4f7yvkhkgtza/KxoeOKeBx+Qvp/8GFugBM4HxJBOguWC/R5M2klLIFJj5EEPyTlkEFQ2UQJfayiQ8KupRDjGiM0EZmDw0wBFiwQjM4bguXAnHR/DHWotUuPNfwZMjPzJ5k5pWHaMtC5ZotL/uy7NSz8kvTdcK9LAzfNqwGsPKx7L4lHwYLKsLk4/gkdGpZibwNE2lbD4TwYkSgwgOUvHrg+6Ub/npzKJEoBhn6mAed1MxIdwZvzGqrwZmLSL+cmHfyaOGaueiSQNadneiQ11dsr6r34Fb0wwP6UnWbJe8U5J53vJwAC6lAGt7CBfUF5OrrFtDT7TxQz0wnjHDmk55RSZdO4n0H1gUzmHHXnt01WkXYCQDSjITXugVK0eBibLEgIhjCoifRi/d2jmjhUGJPrBCXyxgxeCKiErrIpCZhK0sITDBXodCiUoBN4EgQlNwxcZSWoL1ZlFLk2pw9Jgp/ZfaaFeR17m4PSk+JNbJTziw5hS4N0JAnuFoKlJkrffxH7LNqn/9Kekbv9FeDNTJ/HOHVJ89GGJn31RovYjYAqY2TVwcGlokOShx6RyxBEmB31oCiB1/ssyMNAsNm1GrfCqT21DovdGMCEeKZCQsqe7qdKtmVDGHN+sSV+xjasaDDYsFsVprZinsV5IxVUB5RMC4vGePRK/8pykM+djw8i8yfo19imWywYIZgANhaAYz0NV6q0YwBIsNZNjjycjiRIcuETCcegrASorMsAcNn7jVWk465My+YILpWX//YctBkq7r5Ddv/2t7Pn2tySYgBeDqFzu1gfsCxfvo55J0VjbSfrcakkbEPeDDem+fMqEJ9qGy15gpuqRoCe7Dl954yDZWapcPDDUhF2fcZUEI6a+lEPHT8PZHFloBwgzKEEjuGCAaDx4qcRzYWSBUxYzxkBS4cZJgzTmrnYbToNnJwd/SOrmzLE8LFZpSBKuNNhU4XWVNaul5e8vlTlf+IKEhYJUenulb+1avFcckLpp06Rp7lyZcvbZmGTvI1suvRgb1agE1iUqIh1CN8A4QggPLVz6D4jBi8ZPUJoak/WRVnbFFYWqgsni08HsdTPmGHiHL8LJOJfZuXwsrWkYNOqGRYJmFAIUMIwEk3ZArALIqU6Ewi351rco668etNA644ZODEQp56+HHimzLrtMQdz19FPSefVVEj/2iNoqk8dJ86VflBmfvUxaDzhQSiu+KdvPPUFyx55GPBDgmeyGEJoXLZLmH/yrxrMLddX0mb7se4NpqxruRGISpP2jHVpYKbkkjsdi9KnDS3zMbPDOFpNNurl5JO8ElX5mUFIJibx3v/aaNT0yvUcYnjr8yZBAZlYOmngzlm0MNs2Cfgwg5ad+L1NWXCO55mbpfvll2XjkUQCpXXKnfJzGKUi9X/ufshGLhHkrOmT80UdL1/ILpIKlXwiv4xpD7YbccleXFDdvpgrJtbZK/YwZKoNvJ9iF1JZPuyUU1789pa30SO5FIKpA+lMffPEwthE743gbD1F8IWaBAmubNx4VYFpFeozR7zV0+OUXXoLY4cFDxXtt3HONpAXN0IyFRctnLpFFP7xZKwrtmtWpo3C4/3xpRp/IsOPuuyTYd44EzRh4sBBQG0HPn32m9HdcJb0Ymdl/Nhz6Eel+8E4JJx0Dw9G89RiByMDaN2XThz6sdo275RaZetFFCp6Wj77CwAfnLLVgKgIEko4TBLvJ2s4LAobbFKcf0EehWRM8J0MTh4FJioKpSSost2AhJrYYAZuABKcpwxCCF/tnmF0T1bhSlIgYVkrB5k3o19pMOFWxl+cdXhZOniY5eCu7lMqmjTqYpFgFabqVWfkwnEoJUx0BkNGYMZL2sqxoPRzFnQHcXIk+dKANRg2YKWSBFYfg5HkgPAY+McVER1usHiTLMmNClIZtPLKRpjEwrE4BFHXKBVVrnSBTmmrTBF1vp/1wJW6loZBM8vnMcFjvCuAjfCRG9LYMaG7b92EmgYEhC9RH3ZwHbn4b+wxDUsAAl5s5W4ZWPYwmO1HSQezYQBLYbFQGkAWsjhji7h6RxlaksV2D4OzW6EAv+NGFMaML9Fi1jawgq20ukmGgQrB4IE+S6NRnlcsfcvuM3pFg1GZhFSwy1irx8apel93bBwn1DRI0Nuq8LWhoxGkbFyfdxzFicl6n6RisvA7etYCZVBpAAEBFgZPX1krf669r6oRTT5X49bcl6euDHMiDp1Jv6Vd3StOVX9VmzYl9/389I8H8xega0KzRtKsBMt3k24OraSBbMWmJj1cjaiuTABjjOPCFmqqGHE54tLImFEiToWASXM2MxCzuCpxlp2Z6MzYDyk89nZEpj8Hfa+Oexnvu6CNVh9Lg0bWBohXeUlGi49ql81++I2M+8AEZe8ABMvvJJ2XrN6+W8t33qo5gyhgZgxnEzM98RkV0/uZuKd39C8ktOwHTKMxEvCyngF6qiwz/rHfwUaMWCRctvxYPZCXqjSdQ1K4kRVNEH+mOD2IkD1uZwE0CZid4LJiOVIyBaHFLUwIlIOD0DDyjRwrz5stcbPBG6C99f6TgGFt2VbmQx92j4vYdsuXqFfAo7A+6QHstIILBhu9YOCGPH10l9eefJ6Xdu6UeTXfCkUfK2JW/lF7OI9G866dO1Xkk8yaYZMc9cJaJMyR+e71E8/ZB/6nz5ky0lqmqTOm026s33PhEZ6oFkxiEWMOBN9C3hOBZqfnRcyat3LBQ9/cdPEVAQC2Yyo3LMP3EuWuXhGPHypSjjvIs7+teRmE3DQ5hgmwdvnp/bc76RvTBWCSsXyfT771Hpp54ks5hY0zAi7t2ScP06TLuoIOyHASZINZjr3TG+edL27HHyuYf3CRD994twcTZsNvDBJvxzy8gMgFuHqlpGYB7g8mpD898YoKro53BiNaFam/mIIPTiQa95nXiasCkIfxXDagtNMdg4jQpb9woa9C0OPoSaXYFtcGecNUI0jE4xT3o8FuabFqCQcJqyMtHn93fI1H/GNnnrntlLJo0PXP7Qw/Jjtt/IeWnH5f640+Sun3mq3dXsFQdQp+Y7N4lLef+rUzGu6TGWbNk/rX/JBtmzJLdn/tctkTUUYTLRJ4srAnEWcHmnSsa/CPNr+wsbsUjWljt2prYyeBY3sI+AydltaQKIXVAmIrLBINGehaYgA8Hg75e2f21r2mKgWZMtXGfTffkYUIwcxKa3UJsMLBvhC5WcsYEIDdsk/l3PaAgFuFt66+/Xnquuw4rnKUSzJ4nQ089LoP/+8doy9isHTdNotlYqraMke5vf0N6bv6eTL/532TCMcfIbKyGKrt2Yp6qXZpWiJ9leHWqORuPWC6AuBeYIGuLhW0oN44IZDkoBx4pTTyEiXc1ysgaUAg1E2KEl4LBbCnD1IMIBDAtCT+CSa6bz9jNYNQr0gP0nyoEzVU9EwCmmNJwHpoFh2QFE+2pt90m4w7Ecg8rkdc//zkp3v0zKXz8FN06E746xSvUcOo0ZIXvsEIx4NFro4OO0GnURjTt+P77ZDK6hIlnnS0bP3+ZvIVXsNxSC+bvJ8mLT6kfeN0c2KvNHy7EMteASZv9LgRxCIO8eiTPpwveqBLIRs4gU/VICoNpyERmbaJ4VoEsJBMVDa+eJPAhA/tJAxKZ7Q9MkIA454dJN6ZdaNJR61hN1wRsSKTYfDCpuAJwhrpxbTL1tNM0/vaPb5HB2wjiyZL0dCMbR02IIHDc0KB8BihiVOeWmHvmjj9Gtn/7Oim+s0F677tHu6GBh+/XqVfEDY0ivqjhAwX6hqrCWcrhYFIpz24yC1nQEQ4L3KFspEeqZ7mkUcGkaEhQLMFHYSx4sn2LFA46RA76wQ91rcx+09RBMphDrJUHt22Tl9uPkvrjPiZL/vmf0V9hBwVdwsCmTbLmtFOxcsELeprIbTbkr3MrnK41a2TPFVdK/uQTAWIPsGLLsAo2G2kQPQcqQcjeLxFgtgIAuvubX5Vo4RIFMOQKjK2PKx2exLBSqDOofi2fcyCaT10qn7SMXePYQh4WeLa4gZ0n2r2bWiEThUCo3lWZqwqNW/6qYNWuqxwOIjoAORXWecMcLPP0RRlA4sgaJpwsgE6PVF00GJn4IVhQTtB2PfUkpjHc8OWShV0AmFUxb+CDXEK7F5iwg7vmrJjcUjR1v+8IOtBFy4D+XvgU7gy6s44ZkoKJZw8gdfk409i0yU7dKAmEYfKDr63wDo8M6jj10aUUczIr2LX2NRviaqwmMY8GJukLKo7a69fJC6djJ4bIIyjsiOqT0gAMdmGG1vxRVp9xuiWQTsAwQBB8P49VGoDjpkj3gw9KumNIKi+/ADDQn1Imt7zwYVHCOfsCYM5DXUW43fpke6ckz69WW8IZ4yVoxRp+EG86121RWnQY+vN998cyslsq8PQSWozMmWIDkcpiiSFTuRFnX4kCJ3RPGMgvx6QVA1JZcOEkoM7W2DYhVxAoxnkFoq6mKJom82pY2DNFg8p3IarZJFi9GSMp+joUfElxSNlUCjwmQBPjF0y0SwA7PZVYxRiIGg85ROo/+EE8g0B7mNNKh3sgQ6tf0oNc3AUXzEfjDe9I8spr0vgPF0vL5f8oTdhUKYxvQ/eChQK8v4x9zcF166Tv97+Xwdtvk67rVkjvL25Tzwz3wxQLZVAHqhlkdPoD/AghwURMgaxE2DKrCRhs8NUBeoQDSJujs7cWTMuD/s8FBYJxgoibNg/eM6/UB1wsmCzEMdd0kPgEp9uBxffPCAXsFe6HPcb3Cm9gOtT9vf8l+YMPl/I990nz5ZfLlP/4uYwl+GzGo4SxB2ISj1G898KLZMevfiV93+mQaGk7EcKAw64G1cWKHRVMlhQHVlDT+AKJTjfsu2jatLG5SzBSfnWCQaVYDfCJngDhuFU/oDtmIxIKVAZpVKX8uJNAL8poiNi80dHIg6BbZTPnyMDzz0rn409I/WQcaNJ3QKYl02XseqWOMs8cTZ0llSfuk2m//KVMO+MM9d4K5ox7XnpJ+l7+gxTXr5cUzTfEi7P87NnSjNe9rQcdLC0LF0rLl78su444XLZ+4fMiY1p140WnURyoWN4aMEnQAY1dCkuV4LtpGgglpz9Y66hPESlYrIXm1bsz2Lw32WgHIeAz3wQgbJ7MxMoAXYFz4KsYXKwieCcb82daqFJHak6NODK/1X40KRo0rSY+8jm37AhJXnhZ5uCl16T2duXsfOAB2YalIT00aMIAMXdfHbE59xzYtlG6tvbItmWHS9tnLpOpZ5wl449aJoWf/kzeueA8NHEMUhjpOXMY6ZkGDOzGqM/yxGGCKYBItkOOoqt9LBqZtbCMEwDmIzTgUI/DdljS1Y2BAN/Fw/aVTleY3tyizcJQMTApwSRb8S1OmnuuMvhsmIjBa049pfoMVlZMRkABhf0YZWMLrXz3PTLrvvsUxEp/v6y78Ubp+vrXJXfk4XgNcaIEXAqypXB6By8Lp86QYClmFpCx/W/+Vvouw8u0r6+QFrzHmXHzLbLxrFMkXHygtRo6BvXgH2PeGYAE3/zTI1HoakCHRQdmcFf1Jj5bgUlXL8KkOsD8buihh6UP7zzGoWlMO+98ef300yX36hua2+fwuf/cs+ervTPOMDIvaehFsfWGzRF4TeV3j0rrNVfL1JNOUrDe+s4N0vWNFVI47RS8uu/DRjFGabYW/NOWAvvTAH0gTuVwlZU/50wZfOgeWYdNkAXf/Z6MxQZI/zevl10Xf1pyH4WMIRs8q10bwSQafF+OOUMorbTJB65s2DlGwA/BI4+CAF484Z/RFUx6BMLbt98u41Dzc7H6aFm9Wga3o69ik2AlIN1qUllrLk7WCAaTX8NWG4XB1i8BREzsh7DE67xmhURTp8MzKzIdXsWw5d57ZQ9ArAOIKVdQzOf02NTFgUnvxEZz0rlFkrVdEs6YI0M/uVU2L/2wzMZe5sRTTpWuY0/GV0ix6sGCgb7IUAUTD/iyJys0TAIs0UTaeUHghBzo4KC1KraMeCYme4HJvb/84R+RHd/4hqzBQaeFn/60TMBG6/+twO2zrf/jIqlgTjnm8q9Iyz776Fq888YbsImL/hI7SgzVukIhtK9HBdMHcASm9Jt7pe27N2KH6CzZdNO/CM+WdH37Ghl/wgnSPG+ejFl+ruz++/MlfxIqhVM1rREPJpi5J0GA8WYBT7KKFwR+FZlfBcVXVbMqBJP54t5gwn37ByR/2KGy+bOflV133SljP3q85NC3QYMKZDEoyS5G0ucs1UUcw0heptbyZ9zw+DKADPf7oJQff1JaDztMk3a/tFpKv31cCid+TI8XhjiRwR17zg5syWhgCkbtMkAcd8MNMhfvv9mCxixrl22/vgOADUrXM88YkBjRd1eqpfHeSGXEAx0vPE8jE0ir7pCnUkI33ICXN3z9ZRVA3fjHBwWTT66t8JYM0DMPwz7kBum84grK0+ABGHln4kganz3t3dJJ90H5m7HkO+xYzdc0Z44m9a55Re88r6lfEnjuMYkW48wQ3xNhCYlC6NSnfO/9MvGWH8mciy5W/q3YLN564d9I7sPLJNm0QfpfelHkU5/CbvsUCY86XL2RjNRLMBkzCMrobQhlqkDyFwoY0LHhK6jg4LsIXNgSkMUy+trQJ3NPSwEPj4rwUBObui3bVJ4qVqV8pBV6U6H+EXTntUxT65Qti1u2EZ5NPq7Pub6e0iZ5nlRDKG7dIsGMiei0MCV5/hlpW3GD9D31lFRe/SOOz87WKU0RIE659VaZfd55mmcL3o1vwUH8/AkfBWDY1gPoFfTzPIWcwwwknDET4G7Ul2q60lKDoBvghBiweOAMlmPdKbJ85R3sGtFH4tv4/DY/ZrLAC+MOXoC/LzABqXpBzG+KUa4VnHGW2ToHPlTjJletcjpclTkwLa+nVfNRvAqFMJ4z0vHb5dH91XHjpfLs4zL5xltk7vnnS++pp8kbmBcmu7GhizX3NOyqz8TBAYaNOPfe+YlPSAE7StwP9Qe7UBpN1wtk27KZ5huANvelTRV8TR4jN7aT+Y3i4IWgjJxc1coAvzrHqAkD2f6QZMLNtd2TunmWYv0GtYNu3BrVvPrsLj6ecYHg416+iVFOJ9dzmHzVivlg0rlTKmgRDPkp2IJb+5qEiw6W3hdflEGcrWzBQap9b/s55ppNMh3LQA/iOz/9qWwFiLoth4GTk2u+wOMhqwh7oJwZcD4a80gLjkZrumqBHWoWYMVBM/5UAwBrK0xp00k57eLOUL/93AH3L7zhGlVgMkotgLVx5rGyI7vn1iiUuWem+zSnRbO4OG1932DizSIH4IENG5hNmvbFbjcw4emz/ltvkj9ddKH0I60Z72yW/Pou/S4Q+db96EfSCW/NY6LOoy5qD/Rz0ElWr5EGrM8ZithBj59+Us9dsivJyqDlZPPigVxsC0ragi8gaPOWjqtYHWkPDlGh5dg8kMKy7Izos0V8YfXpvcD0acbo4TTjKT2jq/AMRJOviTW0qgWago0Fdg5dzz/PBBmPHaJo0UJJsNOe+8hxGADXy5/OPVt63nxT6ngWHRPxN7CZvP2SSwxETNYZtIpZudqMRcYddrjSe/7wB74JRrAuxoriHELzxRhs8JVO7ExjVorO2fYk2bR79Mc38Cspta9kyWDKGHNx3j1ISnSFZpzc9mhPns/RMlPwXJWbUaty31WGJaQ4MMAlYNe//5sMYILegN31SVd8VUqYEnHFE42fhCXsoLx+4QWy9ZFH5PXrr5PdX/oS5oU4LACwzVKaC3kYLCuPPiBjrrlGWrFMZHex585fS3T4oboB7QtkRfG2Yks3LaV12P5DhU6hPH7PhiPMHmva2LPD8kdDbWFA5R+DF/XfDyYVmtJMlz7CApYK+4vx6zhVhv6PYda550rzxRdL6f4H0bfV2UlfvKdef/zx0v2jH+L9zXFYMtq7Ic0AGQGOCMZbNkm07DiZhbwM2wF88Re3YxjBXBu7T6bS20EOIsBn/FwJGjMm4VhiWaBH7tZFON9hQIFfeZsUY9LMJs8JIisJJjarOWUHzfHycTgQlkOTcanKdXL24jdBw2WAF193yx3bLtvxqnU7JtI5bGDsd+210vh350uRYHJMxTQmf8pJEi7cF1McrF/QfelZd54Vwqd07wP4OspkWfCvt0j9pEl6aqPzyn/EOvsYvEAbsuITD0jzBXJFxiMONrC75I8tIbTjw5dfeD8Z4Fw9DzXBIzFHsaEfxlAKOyQEitSddsZHWflQGQd/m/aAG3L4zEAg/OSe8qhB+SDfr4WpzPIO58+23Gpk6D4AwImwwnrr786THI6vtOEQwQdu+r5swCHU7ddeLfG6d/AqYhq+rDkZC2DszXClgx3y9PW3MIVC34oVzgwscXkEZgAHHNZd+SVdQtIGO8gPK2kr9OoKCXcWyGwsutMWMovlW4UPGnqynRu7UYSllf4Eg4pCEgtGQVpyxIwCeBjZC0yFR3V5QHB3eZEjA9PyKjeiVll/DkwqtIrwd+Tnxi+auOAc5GtHHSrz7rxPprS3y7wLLpApHztBdvzuael57jkp4WBpAg/m64bCoYdJ81eWygR8w6Fl/nwt0x6cAF6Pd95JT5dEPMRP7+UYTJ2wfy8w6Qb44iu/TgNG88h2TMBf/tgXT2qtH3Pf1u718fbOh/AmAv0DJ5zenVhYqtSL6vYUpblUVlbG5OOWBVf708xVuSC7PO5mcmtplJjZUY17Gv1DwYQjxE/9TsbjNMZMzBM59fGB36vRQ/3YtOXRah+GMM3Zes89suOSCyRciu9TYuDRt43QpyY4o/UJBDOLT1zINCRNdYeExSR5c/tg/SL+aB5WNuE2/EgafpSuHl0luky6MIJvjvQGUv4Sz2S1OueskWuqsu06KHkvz1Sb6CX4523TJ66nMUnPHXuM7MK6f88/XSWtl1+h05nmuXNx2GCcfnGAL9P4fr0fzbj7+eek++c/k/i5F9AnYu3OvUr1RANRy8tSq90jPRMwwSPLep40P2laSy+303bm6pKgE6er+vNRHX6PrB422rsbOoI3OCuERwME34BNny8gvcaZgVsGUmYUaMyLyvJexXrL+NR2MxzWIpcrmOf36aB7GSCBFf0fXrfmjjlaT3Vwg3c36HALvNc+BK+C8cN8mD8mL+GgFRZESl92JEbzj6Ip2xK3ao/ZpnIzu80mLT5twDmLGD8SgPdfrXEx4BRoZy7KDe6K0+adhVx9UxA14vXyAGRy45wFHFFoFo3SGJjGZ8Z9zTHqtJnnVEEiNzFmjr3kqi4HHHnAaHpAgwKTBZpmpAyLG5h4NibsamOJA5hy7ctshHaeluIQFk/KhR85GgM31uoceDAfNX4tispUTSyXqziYAt1qUGYTVaG2MAYV4yb88GB/GnMK9EqIX1HiS5ANdfidxCjXjM0OndYjDeZSEmOIuKhTSKIm+Zs+GwlX/XNPerO4zzGqXMfn2amxNs68tMMHHzcS6PZHLv2+IXe59ZAWwcfcUqc/2Onh8lDpWiaTp1d38Soy+arQhKtFjDIvvpKdw3444nPJQi/HTD1ZW8D77nxuDOj4Bj2Uq1xcvWBGjEZTXSy7MYKP/VGkixuDychyaWKtXOUnVdkd34i4z+0LyDw+7vOZfqfTC4X3qQfyzoBklWVsFjeypmmqT3NGZhJdXm1Z+IlLziWxpKkCieXNK9xTLBR4fAQeqTkz098nmJmVzjjVWjV0mEzj9WB6QJRayzcinlnkMxIAX1jHS9szPgpkyHiUScv3l4HJPnpI55L4OZwqkEmS/hG/ayF1hRbtwLxNtSZltiPizMkM9gSj42p/LEHV6Kw81fwq3zJlgFTL7fg0vRr3uT2Axm9CzMYROsnA8NcEEw2ZPw3JL8LCJ2dTvDXtSF4dqJQG6vMtURS2wFa/ziRLZrq3RY3ywPrUPwtmVhCKtFyu+JlcgmM0X273rMRq3HMZv5NSI19BBtnA9tymV0vkeK2eke6Uek6nzsqeyXV6FA+0aTcFQjOf/jx+CZpABgfcf/0mLA/faKprxnfCJyb2nRvwZrqrKrxSpvq4T9UMqh4XPthfleKN0mRvmPF6WRRqKciuEfc8Ip5xge7jBhzlMa9JGSbDEoalmzIVYnSn3akbxutl6liOHwmo8CcisZWWL/ZNDn/b3oHVvPbHz+AnofH9n4lYlnL3mRiPZgzMNrKm+7gvjMvic6oIJwX8NQW0B6O5q5f1VwPTW+FQqZrtLPIK8Uj7q48uXW1U42oqhmlY3+CnIfGLC0ldlCtgF2iGNm1lDeKHebCvsQG/x6liWehaSRb3KrxS5TWiywW+7Nnlx7PPpxSXWWm1cUpweRmpiapQ4zeZPp5xgeDjmeeQ5uW7DHozI3jN0k1ZVX8mS5mUNeM1kZhmJQASu2aY5cwL21et0E3I4lD6ZE95sKulYXyUy02Gfnak2vJx53SI+OLj44jpRJh0xvXup00jee3ZeMhd5aulkc6QyVVwSOMo6dLIMyJu4FTpxk9JLi+jI2WoHE+3u5droHobXdl82V1NEEz+RCS/xwnZ83liN02X3xEFK8/d+cqJVz4ytq7lnObmOfHuXQ9gETAT0yHgDF6ya6GRUeP+7gpFeUzn6oO6yKOGKb36rGkmwPjIDxnMxfkrOTWZNI14YeRDKmiqh4IQbIvLq3KymI8SHb+3w1nBRJNhERVqvBSOfH5lRdtAUnG8Up7Li9UNsMGyE8tTrL73wW5uNaBz/GmcxOdMaNsvaG2ZrQpMSJVneGyUVJBGoQ7P9i5PzEd8Rs0/SqKDH/yj5thbi2N7n9wuvyk2XQqJoxPVEJsXaLlBumAvmfhPL1Y35vIH4Jd2sU3J81xWuL2t+v+HwsrNQs2D+j8QBlC9/wfaxagojY+V9gAAAABJRU5ErkJggg=="
          ]
         }
        ],
        "meta": {},
        "name": "icon"
       }
      }
     ]
    },
    {
     "title": "🔴Cognito🤎: Sign In and Sign Up",
     "type": "stat",
     "gridPos": { "h": 5, "w": 15, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "SignInSuccesses",
       "namespace": "AWS/Cognito",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "accountId": "$account_ids",
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "SignUpSuccesses",
       "namespace": "AWS/Cognito",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🔴Cognito🧸: Challenge Requests",
     "type": "stat",
     "description": "InitiateAuth and RespondToAuthChallenge",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "req" } },
     "targets": [
      {
       "expression": "filter eventSource like /cognito-idp.amazonaws.com/\n| filter eventName like\t/InitiateAuth|RespondToAuthChallenge/\n| filter recipientAccountId in [\"${account_ids}\"]\n| fields @timestamp, @logStream, @message, eventVersion, userIdentity.type, coalesce(userIdentity.invokedBy, userIdentity.principalId, userIdentity.accountId) as InvokedBy, eventTime, eventSource, eventName, eventType, awsRegion, sourceIPAddress, userAgent, errorCode, errorMessage, eventID, @requestParameters, additionalEventData, requestID, readOnly, eventType, apiVersion, managementEvent, recipientAccountId, recipientAccountId.serviceEventDetails.serviceAccountId, eventCategory, tlsDetails.tlsVersion, tlsDetails.cipherSuite, tlsDetails.clientProvidedHostHeader\n| stats count(*) as totalAttempts\n| sort @timestamp desc\n#| limit ${limit}",
       "queryMode": "Logs",
       "region": "us-west-2",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "❤️‍🩹Performance: 🔴CloudWatch Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "type": "volkovlabs-image-panel",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "CloudWatch",
          "type": "string",
          "values": [
           "iVBORw0KGgoAAAANSUhEUgAAAFIAAABSCAYAAADHLIObAAABYWlDQ1BrQ0dDb2xvclNwYWNlRGlzcGxheVAzAAAokWNgYFJJLCjIYWFgYMjNKykKcndSiIiMUmB/yMAOhLwMYgwKicnFBY4BAT5AJQwwGhV8u8bACKIv64LMOiU1tUm1XsDXYqbw1YuvRJsw1aMArpTU4mQg/QeIU5MLikoYGBhTgGzl8pICELsDyBYpAjoKyJ4DYqdD2BtA7CQI+whYTUiQM5B9A8hWSM5IBJrB+API1klCEk9HYkPtBQFul8zigpzESoUAYwKuJQOUpFaUgGjn/ILKosz0jBIFR2AopSp45iXr6SgYGRiaMzCAwhyi+nMgOCwZxc4gxJrvMzDY7v////9uhJjXfgaGjUCdXDsRYhoWDAyC3AwMJ3YWJBYlgoWYgZgpLY2B4dNyBgbeSAYG4QtAPdHFacZGYHlGHicGBtZ7//9/VmNgYJ/MwPB3wv//vxf9//93MVDzHQaGA3kAFSFl7jXH0fsAAAB4ZVhJZk1NACoAAAAIAAUBEgADAAAAAQABAAABGgAFAAAAAQAAAEoBGwAFAAAAAQAAAFIBKAADAAAAAQACAACHaQAEAAAAAQAAAFoAAAAAAAAASAAAAAEAAABIAAAAAQACoAIABAAAAAEAAABSoAMABAAAAAEAAABSAAAAACPualkAAAAJcEhZcwAACxMAAAsTAQCanBgAAAIEaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj4zMjk8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+MzI5PC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+CmXs/aAAAC75SURBVHgBzX0JgF1Fme53zr19b+9rOnvIRvawGDbZA0IAJeioYVB54orzZHTGgVHGp48w6nMbfA6MG477huKOoiBIQBYVwh6ykJCVJN2d7vS+3O287/ur6vbtkAjO9ub0vbfqVP1bffXXcqrq3o42vPIfTkGp9HlE2JUkUR+Q9CRR0s34gQhJVwGlnmwJB+Ik7inma/uXrVs7iD/jStaujdfftjfV1jA91d2AWKzT+d7Ld666Lxnrakpm1nQnR89aXlq3ZV+ysn1DgmXLEqy9LgGNimiQeP6dV5RQzPW4Plq6ZkPU3rUsmtyOODPYHXX1puPMpKYo2NRU6C4efUpbPlq7tnQ4nXtXr63tj3JHoxQdUywUViQRzqKNB6NnXvXB5dVR6qk44q2/ikmCYlKyN0sxhiQZZaGGWaZ+Su8nGgdLCbqjKDoAlA5QaGeSQhdZulOlmKAXeg4MY+CMBz41EGT+OSELHWHNrfH65+6Ka+ZNj2q7EO9r74syo03jRr4EgVNYUVtZUQSttLQLJaykpUcA6FBxG9aszdQM5aeNxcW5rIOFhGQxw0Us9zziMD1JksaGqmrUpKtwYHToxmjDBe9rRZzdmoqilsHRUaSiGKk4QmxhzNDFFRI4u69UOhH0hKDDQCcYA3z3k6cXpaSHzD3ko6ejO45ZAcVSTymOewulUm8UJ31RHA/VlIaGF/zqprFK+f8Z8Wcvek+2UF1fn8olTUmUmlQqYgri4rQE8cyklMxkbc2k7dMI1mQ6UnM6ijNVHg9hQFtRojdFxQRD+TG1msui2yl0dlK7MR2n5vYMDhSSYokYsiVY3TvwyGsgUoiDk0ElwCkKdvcOaH6SHhNAV/ukYd7TLUxIM0pF8niBN8T3MOPDFD9MUt5HQ1GUjJBPlUOLkxyl5hjmJYpdT5GKElYUMSCXPhGl6M9VrNAMu6hqhtUsSy3DOr4byFtPWfXkaCBDHT2sNkqSGpY/MiciYKG8PkLgBJ57p1KpUipOkT0pjgwOZ4Zyowdq0pnTDK4Nr7z28eq46riu/r5SqVSUSSyTQGSgWIgoLjx4TyLXd7E0RqMcphunQl1sokbJRHm4UgLgoqRt/DRaifBxi9oHrfUXzS7HGFExyvch5hIkT1ewI8Qt0XS5mHEZqRnhbHdMFqdzyKMSASibHasiVjQUCsUkNzwSDRVy65f96hMnpk1RgmEWkySse+NRqlSJz+wWRu7OALJck+rIHJ0KKEJ5nkX5GUWscyaXKFuyyG6hqeOHE2Khk2zVJGXlHNM7ficp5WzF/MvbYJnOeq9QKWKwQA5gNvCW7Ug1baqsAiyLCUot46fyU5JeNF0ZzC0VioWYXifeLRJsQDIck938MwRMunKt7GJUsjTyZQhJGdNkBS+lOd2mT2S8VAyHmrt3yYHd4HRiZJhTxUwV0gBQnRqjWW/SvGAnnXkuW6F834VKdOn2KXmWb8aUM52TmSB+GFAil2IzMMR5WymP+d7WhH0p2L+zyeNpUpeBzDm1Xo4vpUFB6QLxSGBKstHRAAMzhGYLgSGvjJGBKpKrK2+d0sRvIUmU75QpZlEngDfGTR0W6t5Zp9j4FSyWGsa9bBNGIvMoM2acw+WZXpfokTK7mKLSmU4vT3oVZb+MsVIBqVTVRjFy7DGTCsavG15GaIZanlLKacqTHKvFcWJHzUzlidhCRRVzr3LcUj1BkBN0WnKZ3+lVmuSIxsLKeEjzPGV5ZoZJM1st5mmZZbLGQ0l1V5nfGeTpfL7XobGNLsl6ivvjONkmTgOS9VGefI4LUrY3RFFv/HioJK8+KDWyiUo9p4kSteUam4xRrsS4iAsO5a+gkz3u5RmN+zByvOAK2SKyVON3+YfVW8FzuHzZyL6RvSQjUXIgVyztlhUGpCLhkgonIBTAKzWC8TQJtBxXejF5ChNQznOponUMug9xi3mCwxldLrw4Al1ZjkmRCCcx5Ac7AoNllzMDuSQqx5dVod351Mr0QGfE0peUSuwkmMwBuuPYX37ioDhd0+b8y8Qo1xtgUXF5BZavj4o0R6MkpyyEjiUUNJhsnPrQS1JcRDFj4K2PuGCcX1qNI9B5XlFYkv94oRzH4LJdXMo8eeA+vF5pLNszLsd0JpyDOCn7zbKVa9PBI2OvxrKN2NluykLBfJJUyJ5yqGhQ6jOcmrLRXq3jELvlB51OXkh0qb4Mni5QBr3G4eU42ZX2mGVeQLDLJJSFentMZdAXQuN29leUK8hxSbJDMqLnRb2Dg3YAMi3OMrFkGqFCvvnhbPDKlFSRFuzzRMbrKEQWjPahJVEOH6/4FMV2wrhGOpmScjOAhHnqg9iGJMbEVnCPqzGjzRKjm2ir+Ly9IQzCfGi5/Aiyx+mNwIljNKSXDaE8PRpzvm4eqcUYm0dyRhDmk8YU5oRitMkclYXpT5gZyggrtqYTcnQLFTViaReTGVNOIzCii6tTiGoziAQewUSuCOSZRyBjpVelVDpgtIBkNE89lGOPQWHy4/S5mQbTKFNTG1nkgop8FVh2hFBUFTa6KRvVkdH0BDozn3Is1YNpCpnBlxZ1qLeT4uxyTzYRUmKpRP6lgimpKohK8KfAFGBxHUHiu9QzjOKP95BzmGZWsYOuRbw4w6ftEgq7R5ieY1oG6TNbkZreaEAng3kDWnpsPmr2MkbVVtwKMJlQUfEOhP8IMIUYRRtOBQIZx+mJQDK3SpVEnzAXcrjQPFpJO8VpcZOiKidBpWdK/KFgikfGu2kC6dtqUdzbj8Lt21C1YgYarz8D9cfNR+2sqahqakCqJsumXkShfwijHd0Y3rgDQ7/dgLHvb0Pq+BakF7dxPYnrG/Rc0GHN+6jXz98VMxvGPes/HkyVyWmWdj4NcjlR91qu8006ycgQA6xsEIk9gJVgCkd5hSuA3YiT10QwzVPYz6mZRnVVGPvxNlRfPA/TfvY6tJ60HLXT2o3rcB9Ny44Gzj0FucsH0ffeTei+9V4Mf+4JZFbP4LpNhotzXAjK+OZPvf9VYBp8ps+sziVJ0dZbC1zzTBOE6Bma5WbrARKBIscjhKqFw3jm4frMCWDScaywLG/u5zsw5UtrMPN15yHb1mxWjHX3YWDrTgxtfx75/T0o5bg6xuW4qtYm1MyZhoaFc1A7cwrazz4RLQT+wAV/QMf/+jGBZIc+q4ndwwigvpSXmtGRwDSCynzfUv4tfaY1T4PIPnIlpPslv8AV/vT6E65M10TIOo+UExJEAifSF3TK4vJe6gmE9uGbOQcO0ebvPIA5d/wNpq86TdwY2LYb+3/5Owzc/RQKj3UDPQWgllPbtOipUyuTxCe9tBF15y1B++oz0Xz8IkxdfTZqj56FPR/9LvJP7kPV0kkGpjzebOUnLfdllSOwDL4bUuIEsEMZQ0iVLygrhY53E8JE1vtLdrJp10VpraEiV9+WpHOZunQNkJ3gkYcocCMbDT3EM52dpvEQMKmIQObv7sb8e96LqStPMgt2fv8OdHzsZyh1jSGemkU0i2uu89n0BXqQrRlPoYTSWB79X3kYA19bj+b3nolZb70EjUvmYe6nrsTO67+BsUd3IT2nxTVzVYKKpimTRAk2GhfAdP23TGC+VbzqWOCQLoSSwLghxtCVuRJM8RuflOkaGy5yVPRX3NpexX4yykqg/mSPLt1b6G6Uo0QXVsaZYZyOQDmslpggdmLWj64wEDVf3HzDt/D8Zd8AGlJILeFCdXuN9Z1uKkulQTZBjWrSiFqqES9qRDSjGgc/8Fts+dsbMbxzH2pmTMasD74JqbZ6lAZGEFVzClygBbI3Q8/OsjhVbnps89CyfWYgjROtWel4lOITLHk805fZlc9zGL/Foyifyg7nFR95bm8SF8fyVYybR9IrrVICXIcqkCKlBZNkkVPulFmcQBQ29qH5urNw1GvPkx5s+8qP0XXNz1B1/lTOH1VvBI5zxyTPt03K6YZilkfpXnNKzS01WNVXIXVOC8bu3oltf/t5DO/uQN2c6Zj+kTeheGcvoDlpE727kaP+WAHFXk6f6M0alKIm7jQIGC9+3HbqMWNdeWTjoWVV2gvKR57Ax9xCXTbPfgk4oWF6ElNtlq0gXdm0lRng+pMKjHAcTLslOHFbFnPe9mrdYt9v/4B97/oOMhfOdiAJQIIVPN94+BH02L1ahTkpZQtQFiBe3ozcwx3Y+bFvojA0itaTl6P1Sxchd8c+FHf3YewHOyiXE+JJDRbmfrAH+Xv2EWDOT9X09SRlwn2oEv4bwJQIfxX70UTjgHV8p+uiag404OjtBfsOWk6jNOtvqLFyADpcn6kNGD19FH/Xg2lffh3qj5qGka4e7Fz7PaRPnsrmR/AECkdm4STgbJ6p0qivYppKFtJCf6w+D2y6XLdCankThr+0EftOvxuz/serMPmSs9D7mXtR9+qXYdLNp6GGo3yqOoviWA4ju/fj4G/Yx15zH9KXtLPJcwQbYyWq66Ay15eqzLxXWUMZQ0i1h/aZtJzTcD7RmK0oqUkrqot1Vcpyh6dKHqmCmCtQU1nBSwTTJBKseG4Npp73chO+744HMPa7HahevQBJN/sze7Qfl236XCleBExKZyOKqvgIeXojer66Dm0rT+Rkfgrm/eIa1M6ehlhdPa/iyBgyLY32bjp2IbpPXIT9f/NtxLPryM++U/0pl2jcQKTSjttzODBlY6hctSNbG5AiojzAJq2ornQhidTLpELTNs9j9vg8kfj+CTADGMKjuGMQjW94GRrmzECufxCd37oXVS+fhtIgBzeNzDJK9ekrykVNmavEP+mZpON6qgaiwoY+dN35e8x++6tRzymRrs7fPITeex5DsWsA6dY6NK48HlMuOB1tnIfiphh7V92MqkvYMga0m0v4aMNLGc0lOwAsJMJFR4tWhhuGapBZboAbtSFusLlyidGclIQCU5eEWuhuLK5ctY/SnmE0n7TE0no3bcfondvYX9aySVufbBJMjolwsl3UyQzKdCe6CXlK06IHLY6OqkbfbQ8jx0m9rm2f/hb2rPoSRu7eghznmMO3b8K+V34V22/4tpnWduYKNN3wCuR/zj6TA9PE0dxIJD2oHy9jKLxy5QRuYumMpRnrF+61Vi4b0kV5ZKxJLUnVntV56M4CUr9oMye1NU9WAy+NqLoGNu8wIGSANKsJhU/Jd94grfJQZslQk0M6eaYF4mVmyBOZRnIufBS7BrHt419Hqr4Ggzc+jNT57AdT7MUkazJnxu0E+/3rsG/BTEx7zTlou/BU9H/mPltNMvfxNgTPdGY4e5wZzh7Zb3ZJt5qEK46sipt2L7d51krmxWzU1TyuwpkGOWi8imuXRSRYdyG0mMt2GSbXpiwUnT5xErKt7hFweFcHUzj9YL8pEUGOk+blHCLbEwVid+vMYtykWJ4KD06jRu7agsHvP4b4JOokiG76xDwtbHD6E59Yj95b70dhcAR182ai5tKl1s3Ek+pkgFWKhe7D7FSGL5rXKZXSrTBYb7epunSPPaOuH9jLp9tSzCfEQCzpEsR3mXFcgJcnVSbJOl4mxm30AKaNPrLFvEKZxQE+PdVQT1lQMNDzGgfjduvyXNTle6t9dqU9Ll82Ru21fDoiKJKlCpOBetFrbZ2zoYqPk50Y2rbLaDLzpxP8e7lUx/mnJv2cGlU2cyu7kxbUO5mS7wvvtIsoSQ8Vut0IxzseNQCBVPMxE0ThLjKKaSKorsAiMMEchfUEMsqlseKTQ5j+mbcg08ijNbzSrY1IRnLWRTg5ToWzx5lj6WW1TrbleKOpxGTZR9meyiR6Hl82tXIF8J+yj3QsVknPcV0Ejlf7xWfgqDs+i5qVi1H43QEUHj9g9ovOvFlEXo9Z69UHEE2oT2OjSOdKbQakTsyl2b/Vqg9wo7ZJ4ock85JQ5rn5lG59n0njw8rO6K+fJYCXYfbrV6GBa4vGxkl5oXcQ0aSs8wxLlTy+1Cy9HOlxdtG7rJMSmNStl5BwnZVVhqvsUJGk18qPZgIktjxtS4RJt/jllapoLogMbdqBtrNOQPWUNlSvOhWT+R649Fx0/fAeDH34QVS9jv16nvSa5/rZhZVb1WK2quzeHsakk/mZmkxOT4V2pamw3LTJZgVzxZORvDyYyigPPBrraWjhgR4svft/Y+a5bt443NmDjoceQ8/9T2Bw3WakFjdw1loQLmaIG0yEI4X9WWB6fq5Bxuz7DOARrphTtg0+quwarrQ38LGQcUvnNoWW5aLptej/0cPY/CTns8uPQuOKRWhasRQNi+ei/h9mo+uEhei86hakjmumc8Ru4VgzA2eiIKPtvLdCsCAMmaUrM1qIqi3CA6vpJHZNOzRhUYlQoBmXKCvAlCBNbPP3d2H5vddixllc2SHpth/dgT03/BSF33ez78oiNZen6LSJpUsFZSAdLwqmozTjLcrHySiTRsz+rNQ7irGf7KS6AtLTm5HWokYtnaJQRGnnEPIbe40lfeokpGZwi0Jgj/LkHx87co/vxdi6nejrXYfOC2Zh0ttWof2ckzH5ojOQ+kYt9l7yZa4FTDabHYiulbgG4sB06KpA5nJVpSjPuR2wZ6SNKnh+UGizkKI2bzFBFR4jYuUZIKy13P37MPurVxiIJT63P/mpr6LjQz9D5ripSHEEtScIko8DJ7kvEcwAtozVE6WeldlVjP5kKzKnzcSkG1ej6YTFqJs1DVWNdYhTnLqRJz84jNF9XRh45jn0/+pRjH53M/d8JiM9hatErICojatJrXQg0W7uwvPnfpmr7jsx+91roHlm7ubXouvSW5B942y3zklvdlMjspjtcgpzByWoK0onSdpGujnMSdNDzD1ljF0CgJFxlw4CjJ9GjSG7ag7mvfZ8I9/8zZ9h34duQc05S7jqwpLzsuZmMdWQ41Of9+eAKQsEYmHjQUSFFGbe8k5MOfckVLe3muTwoRWkKJ1CVUOdbV+0stkW/uIV6HnHU+j44u3I/WAXMpfOJDij7P8oVXPNKbVInVuFg1fdwV3LLGa95RK0X3Q6Bq58HPkn9iI1kwMlV8hU9eaRvgyqBA+l0jPpUtFG1jSPZRPVpEYYCkhBJmKDURweBWvmqhU16Q0HMOv9r0GWG1a9XO3e9Y7vInvmQgeipiDkMwMkxXCsaCLS8RI9M+Y8MX/7ftRduRzzr70cDXNnyiCMcGPs4BOb0Ld+E8ae3YtixxBSzdXILpiChmMXoPllS1A/dwYms9k2HbsIe17+Cxz8uzuQff1sJH3cPOM554irRFpm03P7wRvuQvMpy9HARePmvzgN+26+Gan5LdzRdDMODYLBM1UgoWMIJUkVxTTIpg6ebefwnVQLQo7apPJg8t6NoiJjGrPcQCMRKUxirevad/96FDGATM30cnNwNaaakziGpnwcTKuoFwFTi7P5O7vQ8uEzsPD9b0ZVfS20x7PnJ3eh850/Rx7bkZ2/FNXnzUb1MdNRHBrD0B2b0XP9T7EbNWj96GrMeMMFqOckfN7fvAF7prWh4w2s8DVstgfpmTKSI3TEeWZp5zB61q03IOuXzUdqWTMn7dxc0wILB1T9OTDJw+LTdIvofDjdhh2x+5YGu2GujvNGzx8K9S6DYbWhe4FJwdyszxwzCfVT20kF9D68EanGVo6SXCg2DaIT6AY/+V4IphNOugowxWD9MlXoCaW4pQ8Nf7sCi659K9Jsej1PbMHWq/UsvR6TPrgGU15zDRoXzkWmyc1ZZUtheASDO/ai+55H0PXXP0Tfh+7HUXdeiannn4pZl11oi72db/kBspfO5fcw+AUNTY0EVnsGI48/Z1sb1ZNbbZEl/9R+pGaxeQ+xeWuGwj/nWETHXux2aDOHOHuM20v96dIL+kixCZdxAcTGwCn15pE9oR0Z9kcFLleNPtfJJ4ssSnokMw0C8cXBNHkVzTx4KYWgxK3WKu5hL7jmcgPxwMMbsOnkjyA1pwGL77sBU848QWR2jfX00Q5+EyObQbalCc1L59t70itO5gLwt7F91cdRuu1qTL/4bMz4y1UY2bIHg995HFUsg5o5zybwzRX9/f3I9w0gSyBTk5sw1rmT+giytVC5g3OM0G8JIR3cL5YckDKGo3bi9mvI5Mm90xzaLMk+wqkIj5Ro7U8FSLTSTsDtMvQDiCF0Eg/nmZVgGr+8kU2p9OggZt5xBWqnt2OAW7WbL/wMZwJtWPqtv0fTojkcyUvYd88fceD2B5HbuA8lAqKFwMzCKWg5bwWmrTodTZwjLvrn9+LZpi9j1+qbkP1jG9q4pTv9ra/Cs997iqvutFur5rJZHjfMr2Vxe8Iuli3hRqvAckVSKAdRriuXzqJpxYzp5pE6IKCpJ+cXJBH64hSxAl5Ks1Apcro61kLfKFeg5fKcHGf4LQztsXieMn+Q4wUFiRPkMU/ZIc1UdA6j9h1LMe1sNzfd/qUfI9+zHwu/cJWBqH7y6Q9+DtvP50bYnZtR7B6iXdTPEXb0ge14fs038PSVn0L/5h1cPGnCvA9egarjpmH3J29Bnic4Go4+Ci3vPxe5X+xl/+iW02yuy4EtyrqHFHOOALIvl2Hi7fWABGczIEcHCyWuFdMjKwpUBsM4xguqAqtzzm3uRo4LEmkeManmSJls5RxNKy/Md3JM7XilKJHXkcC0TDmHvPHZEUy++DR+f4rfpnp0A7oIwPQvXIG2EzilGRrBputuRu+nHkD6Am6i8fFTIy/qCAKBiCfXIn3eZK7I78GWd92EIe44yqtn3PAmDP3oPnTd94ipaj17BUHg3JOTeLmZpmypyQ02fSrl8ih0cY2zLTjIBMutTLRSgwwzaHSUGJB9nWP6/hK/2CMQ/NtYrfCh6MLIILImlN/UiYG9dpoNzScuQTHPpwnth3gaz0oxkmnSfGgpSvDy3L1oTDp3AFPLGtFy3CKj6fjNHxGjDdMvPMPud//0tzj4uXXIvvoo9wgoPrUGbR2wEvScrT4stbQJ+T90Y+eXfmJ8k047HrWvOgMHfvQ7W9zQSJ69YgGKu3hIgo+cyUgR1ctm2dmjUe4x5f64D/E0PpXRHl2hDHbjyyRk1NQ5ABmQJ6yebl9OqlJGiadQA3GlABUy3CtOSnQ9bN+IwNTTVbuc3NuQ6+hEYXSeMRjiwpArA8uSlchBhjOC46agduok877eH65H03t40IoLxbneAXTcfBdH1KNQ4kg6vvRllhm/aeXkXFdqRQMGvv0Yep/eypZTjabXnIihr6/H8N5OG5hqj5+D4qNDVhGlZ0fRctYK4xvYuB0FLrvZ1i6nR2ULGXGlMrLxGz+PjPj9RvaYPEAlDiNmoNAX0gVeBG+0NZpe2o69X70Lowf70cxJ8qzP/yWG7t7gngbYSVtfKlqJtJBxL1Oh06OECj28SQ7w+XlaC3cBMxjlaDy2fhvqj5lvlg9s34Ox+3Zxq7UWJU7BXM9vApweJ9QGVQ1YmtaUducw8OxO469bdBSnKr0Y7eQRGV6ZmTzuwm/o6Tm89V8uRMsKtizuPPb8/EEeL+TpDe02GmWFjWaylUsOFyBq2L3mfVqMZeuJYrcVG4w5jACV2gTLSK6wjP5+F7b++E6jXHT5arS96wIM3fYU0rO1iMA5vuZn6rAVqv8M8RAyLeG0o5ynkbOffRXnjLo0IyiiH/z6r91rmlPS6RC1J18boaC6V1yfocKs+8pwoYJ8uqpsjZRPZdyQ05WqraE89u1c3G3nkpqujjsfwtBN65E+po0nODg1cnBZXkDNVDskvFbUdw1W22SWpUxsK9YMsSYqg5yZ46HkiYKfnDpUnTAVO97xTez745M2p1zxsasw+drVGLjtIRTU96iJqWkwtJVrzTPZuesEBb97Zmk636PHNcvXyCuM1Nfx0vKXLhsQFLF7NR7m62Vkzh5lK8Fx+k/dayzhM7jLVjqnbhVytQ1SKhSw+19/hv0EsfOff4HU6fw+MrsOx2SqgrIKTEyi6aPJXHsq2NONLNbRPhbC6sAbJP5xo4zVbmmgS0a8sAGPv/HT6Hp6C2p4VO+kf/xrHHPbJ1F75jznaUKGAwE0J+OiaZLTm4CO8p5NpzTGUHE2L9GgJbZDptKVrqthU5mE0f0HdIuaqW00jvs/NtWyJG8HZbpbK7Vs071NaTigZ9v5zMxrrOsg0/l1We536yoMslnzL+YUaPg3m7Dn7V8jDx8ZeY5Tg4xVKvP9i6HTEjAJW9dM5SmwyJRoqVxDrgNO9HoyodnOszU6sdlRkAuZrXzVdhPXBztH8ch5a7H0u+/B7HNPxbyLz8Hci87CGA1VX6XLRFqsbE+4s1CT+/6tu/H4ig8h39Fny2GqmJqLF6PvoY0ovauARvbFtX+5CKOb9yI9qZ6PbtybVvdA4WaP2csbU0n7qDteUoemJa6PHXyKp34xDdUcyHSNPLefHDXWQqIWTqO4xKYy28jPwBqmAFAqURWwh67YCyVefBSAAUmP5PebvQ0+0wQYmWKH1Ia7JSWbacwtz6Q5wpOv+Cge/sfPm3fm+ehY3dSIaj6y6V3jQ4vrEGn5TbC445htqEc10zS3G3t8PwZ37beJftvFJ6Lve+vQu3m7HUOZ8Xae83l8J/dY2I8KRHqnkDR7FKritE3ABY/CQz1oeQtHfK4CjR44yBWe+9H4gVNRw62GPOfAQw88i9RpPKzKVXSHB/kkQzf20ofdVaQZGMp2eczn8za3s2Nb1+N6JDfALNtInGGkHa9p8QWPDKHPZz+n02Lpl7Wj4zqefbzu16i5iIsJcyexP5JX00CTZZ8WL8c0cPASXWlglFunTSg8cpBTq6fQsnQepp57MnahHrt4prJ1+QLMOI/7LDe9HXve80XUXsxplzyFzZCzYwMw1vE+ziXHbt+OhitPxty3+ENcdzyI0b1PY+7qvzJ9PY9tQu7XzyPzmhn2vG0tjX20Ql3CotILtbii1EPT2Cn55+18m/i4HqmR20BmlhekkIa+JDDVzAlG6oRWrvPx+wgbuzB2514JCjDS5ylQBkkB46JXpoV0ingKn0y4txIvqkPHLfdi9iXnoGnBbMz8l7dgx19/FC08eTb7kpVY+K7X82h0A3a/6ds26qamNnIrmL3TAPvcXTrOXUL7x1djvugaatHz5BbsufzLaPm716P95GOZz2VGdiMF/jRJto6rQGGxl7YFZxHNRDB5T1uVGsAUOGoAaZaD4DmPJIGatygZVekplFF9vmQw6RUGOptWxCN9OtZnwJkcCValuFCfBqLXaZ4gvbQsas5i9Nc7sfPn92DhFa/GvDe+Er33Po3Nr/4EUndmMZNLYvPf+Cq0v/xYdNy3HgMbtqO4vw+pllrULZkNPcW0+ScjHZnZ/ObPIr1gMuZetcbtOlL1UVxSKw6PovM9P0D16xfzN2W4+CLdBOXwYApAgakCODBlur4dy3V5/rZFGUgHompBAAZhfzaY8mB6pEmRUmpniuuoTa7wo1TlyTD+WbNSt6Ec8uoIdHx8M3Zf/UO0EpBJxy/G8k+/G0/03YCnV12DoX+9GnO4xdE4b5a9KdamSGGao/sSp2d77/k9tl/4BUqNsfTJD6OBj4XDnAEMPrcHkwn20e++lF9Jqcfzb/4aql/Dk3J6WtJCL+e9ofwmWzayXPLIsFUiy2WvPJKBHMAGm9RVC858HzvNpu6BPvbfRZZNuSqvD91d2aNcakV+oLMMqXBXiMkQXeEzhI6qIscDrOd2rcD0rN/Ak2THo4FH9iadfwJGOZ3Z9f6PovOOZ5HnAn/E0V7zQnlTgR42xMe/jgcexdb/8w3s+cAnUH/paVjyw6vRsuxojPX2YysPVD3/tq+j6vTZaOQqUPNxCxFzPtxz3V3cNuZgp0P92nHUgGX17Sx1FjLuXg4XVT6v6jRX8pPijs9vfeD7mv6IjzXhIoa+3Rux5cmTXnIzp0aZEGrWPM/XqmliXN2AWWaBUZgBqjxN0ONpNRzBu/DYVf+EY//ve9HEgh//EU76L3g59nzzV3ju8o9jGx/xMphHn+N0iE8pBQ5NHGrQcO45WPCjGzHj/NNsRYeK0Hnfo+j6xNfR8Lrzudj7OeS+14s5l12EmfymRNW6Ojy38l+QPreZm21cWtN3eLg3FewX/4Qy0GYrn0OMhYnt8SviL6zsZFd/1KY9O7mKlI/5mzzi9XAwDB4XUi07+FtFfqA7Ur7Uu5eT7um82LLGsj5u+2qvOtVYjaM/+zbMIjC6NO3p5fdz+rbs4KncDpvE61tjNbMmo2E+PW3BHK6s28YoFym6bClNk+0dt/wauy//KqpfNRf5X+7H5M9fggV/danZ1L3+GWx9w42cWvGLAty+1ep52FIO9ki3ldqVgV1mhKbqWv7Kytgjy3/1yZOiZy66djuXzeds2r2zNFbIEUeOQ1ZIzygBASRJkzgPgicbzw90R8p/ETBD9ZT1yTP4HcTikwfRcvUZmH3ZBWg7ZhFXcNwirJlzmI9egvz8z9fh4D/dhzlfeytmXnSmUe2+bR12XPIFZC6ageKvDqDlI2dh4d+/2VaE+jg4bf27L6LQwYOqUwmmtmODUwVAXOlNFoEqNWVr4uFifiN/ceWkaMNF127jryzNe0YemSOQxhzA+m8Apvos2lR6ph8J99Tr3rAUzWcfg8ZFc5BtbkSqiiMnn99zAwMYeu559D+8CYNf3sCnYM605nNx4pE+zPzOm20GIAT23/swtq28CalzW1DaNMC+dDkWX/dOZJob0M/t5c1v/icuD7H8+pqJBqCycwS3cZgwuUiPTI2U8rvGkuhEAflsVZQ6euOeHaXRsbFYvyolxxn3vP88ML2Wsofr3jmtM7pcCFUu3ypT6cAoSlu0isNvT7CX1BMRU9mP6YwRf46MR2VSnJPaoX/xceGk8OABTP3ca7Hof15m8g88+gyefdONfLgj70ABNacchSWffg830Bqx4zu/xPOXf8WmRqUufnuXT1HOGrJWemYUFemRqbFSsStfzJ+iCXmBrdlf6lZ5qUPlgOAGGN/ZUlzogG2MUBfsBw43ISCdG80qQi+HvDKmnE9eG83NwnE5VkoKtw35Sn2a51G2dphiPhenTucSoKHqNVOOa4bUQ1qzTytKeljgCpCOruy/Svs/A1hyzRW2L5/+6Qew5eovIv/QXgw+/Sj2r3oQsy+9EPoepComrBXQaJv+ONuoz4OpsmjxgtZm+GNgjWrJeVdMptmlTBXaPn3IezNP6T7fUY3T2X1FfqALcg7Nlzz3Yg6lezovVikuygzFLF/zVHsTJI7uKq89Yws83fNdvnfsNs9ULabPnoLuD9+NJ//hJk6HBtC8aC6WfuF9qH3XMlS/bjFaTlxm+nQuXbsAagEqa9ksZ6CliVA5PjfL56pGLaHxN3+s2ZDPazd2CVLFk9w8zzELdNGJR9T6/Pd6JsVPkONqn/qo2yqZ+kSjdNOnbzfILkshndlpOcwXH/ONx7gNZDXRqnO4xfvZR/FU9w1Y8ol3o57nOY//3N9bH6u98TGu+nd9bx3Sx093K0xS6XV7zc4CU+j0MiGTjuN6Neqc9QLeZcXrLpnpiQ2skBrSfeiorDCktsI5vkPo7PYw+eJwL+OWjZbggzKH0fDO55dD0fEKTuCyPReJ7F75Wsvkumj6nDaM3LkdT7/z0+j8w5M83ODOUWqVadNHv8JvYuxkH8sTbPpKS8DE6w52Bn1q2gSYv5GGBk3I/e+iyZhxg1xfIDNY0wz+KzyTqngJLJpHj5NuZ7zvm2SfuVylPQLLe54KFloK4y/wTJYYXGBOLWlEYV8/Nr/8k3a4Kq6hN/5yJ+eRHKxWcDTXpFxLdZJsZng71EJkg8y0JLcCxP6xXqfR8jrHQgMYNRKRWQ3//wDzsM280h4PkEozXrl/Bpgqo7Y+uEefWtmK/HPcEONKfnwsv7ErPXbSV87jqsfsEY+8k4GzT/jo7ZbOuANbrwnCqAQ4OuZKmAuM0BJcHfh0Gh3yy+mez3GP0znmspxQUY5fhffSvUBLYWKQFug8WVmOFIgm5JfDF8hzRCbP84jE7NCgxcFJ2wtaddIobVsUwssZQB2MuFdFotOtDGvaAs7OoEQYkecF73MySByEhYgk8nK3FfmWqvTAaVTjdIfmBzojD0ZV8jPDvaStLMeLKetRhv0FOSE8VJ/ujbYiVNTLLo/yBNKlMijr9SnBHtOhbHGrldsqObGLa9QROI+kY7syGtFEYS7D0vgxTmeCA73SnabwOVFeRX6gOyI/M9yrwg4n1en3cU9T1mPJR7CHRC47hCZJH+N2T+AnXbCTnIoap08zD2ZcvTMRrdb3RHlYkDdakhLxC4SZrrJQK6EpNxMOoa8wyticAd4El+INKRs5QV8lv1nuCl+hz4TYvTGKwWjKdh9RnhPish2PGH2sXL6yHK/Imyvm8DKdAjDkscflbybYjwNr/ulGKfFPFBbAULqZ4YRW0jnrrECO39GFz4nyxuUEeUfMLxvvJXk90qEr8MtgZZXleDrHNU7nkgOIIWS+tzzIK8txWrxcR6c8yXG08khhl1RxsImGNI/k9xEpTyKd+iMKcxkS5dRYYKyW5lKDojLVeCGNqyLfy5uoryJfeuzlJAc6L8YXSKqd7SG/HB6qT/dGWxlKhSv5i4HpjTGpToelcG09SgZlIudNmv94uolG+zsPBkmCBJWQl7v97wCmmX8Ye4KdoSQy2tGK2FLHP8rlK5fLlXI8XaBbppNHF+QPmybQD69b05afmlhT4oheKMykloV6c3ivdCnwoSMr03lpR853jEfOp2z38pK8Hq9GWUFjiFjoxZbzx09J8EmHmeV7xkWrNMkKzqI0K5dJU7qPKDXEOeXRk82AhGn5LKRLlNv0caOSGKzlE2l2sRTA0OZbzLd5lDhd5/uik+Qyv2lR3ZnRkiPjXVipjwTly+uRfV6fhkzeGq/IJC98yDTRSabam4xWN8Z7W+G2XM9Q5pMK9/zEw8AiqyiX8brsMr3ISa9fV+m3IolDFz+l3EXtxt9Tg5KdIkeoW194l0EC5Vt3K4MrwPKFZ66/nGx3I8H+crXmJrvkEWQ63uwNMxPMPvbu/AkJA4Tf/kpSKf5bDv6go74JxkWERI7BmYheXGGzGPe1yr/gbwBJji81yyHT+ceIfhuSTyuygVhypslP/eY44xHDmGGs+WfwWhWYZ8rt/yUgneLTIjPzfIgPBCoebTBlTqkU+7c0e0MqwbSCM2uiZ5JU51jtWIQk8XLsLi45+hMJAeBya8KlenY8cZImQCnaJmDSAkz/CoDPwbznInQq5r8G4O8lpbjFojSea6cQvWWewBAoOf7MNf93glYn9e8MdEZOIVcluBqcREzXxX/bYd9xQJZlrGYVVFfH6XSWylQBuvIEM1fkefUi9w6LJa2ayRHVPZbShFb/HwEN2er0MUcvoBZSFIs8UVdEsVhgWOJ2NVfcVCP8tWP3Q720krUTADcUTJWBJBg94IwZ8PoFehU0EkAGknmHgWP3HOu48UT38QARGHlWilvNBFB5HiAabuDkeSRwrCRMwF2dQk++qH+kke+iGfvpDx20r4O6O+lKB+QspVJ+gDUyOJpLjSSZwXw63Vbg7kRJ/1lEpnfyP5S0ZgZT+VIqXZMp1kR5NOSqotZcrjiF6ztzWfwFrOelLMfCbLpqRm02ww0JVhbfUZTLp1NJposbODvpCu312dpa/luRlAoZakGG688VgDVMifo1T92HPDmXeSVD51gGqIGoPom1q+ZlMvWfSezPA6O4yaJJCseK8p6SDgEOsd4PsmK7HUD8GdZStI/p+1gre0ncwa8SdOdHi92dNbmBV/7H/teRPpbEHZRXmSquJ1ZdU0c7FvWWiqfQ9lfSV/mlTNsNBx489X01rfVVLYU4aufP5k+hN/P7tskUIs5f3Ih5kiBpZbm5fxtxa57/dYMP6QRPZwN5HC3h1r1tnKhpqHr0NRSuBiQ8vqBFK/shNv5GIX++lEdvmMZDOvoXLejjmMXl6OQgYea/Zyl28xj7AeYfTDJxT6ow1ovGpsFlt65VE3zRi/KiW9esiddgDdZ1PSNnsUv/aOhWxtbwnw1dvxa4DteJ1GUe8ZMka6+Pbt2wIaqUt3IlITzk/+E89YoPTonTpYb/B6Vcxx3SXGL/AAAAAElFTkSuQmCC"
          ]
         }
        ],
        "meta": {},
        "name": "icon"
       }
      }
     ]
    },
    {
     "title": "🔴CloudWatch Logs💔: Incoming Bytes [Filtered by ${account_ids}]",
     "type": "bargauge",
     "description": "Incoming Bytes [Filtered by ${account_ids}]",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "dimensions": { "LogGroupName": "*" },
       "label": "${PROP('AccountLabel')}: ${LABEL}",
       "metricName": "IncomingBytes",
       "namespace": "AWS/Logs",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": {
         "name": "SCHEMA",
         "parameters": [
          { "name": "AWS/ApiGateway", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "select": {
         "name": "SUM",
         "parameters": [
          { "name": "Count", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT SUM(Count) FROM SCHEMA(\"AWS/ApiGateway\")",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🔴CloudWatch Logs💃: Incoming Log Events [Filtered by ${account_ids}]",
     "type": "bargauge",
     "description": "Incoming Log Events [Filtered by ${account_ids}]",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "dimensions": { "LogGroupName": "*" },
       "label": "${PROP('AccountLabel')}: ${LABEL}",
       "metricName": "IncomingLogEvents",
       "namespace": "AWS/Logs",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": {
         "name": "SCHEMA",
         "parameters": [
          { "name": "AWS/ApiGateway", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "select": {
         "name": "SUM",
         "parameters": [
          { "name": "Count", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT SUM(Count) FROM SCHEMA(\"AWS/ApiGateway\")",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🔴CloudWatch Logs🧣: Forwarded Bytes [Filtered by ${account_ids}]",
     "type": "bargauge",
     "description": "Forwarded Bytes [Filtered by ${account_ids}]",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "dimensions": { "LogGroupName": "*" },
       "label": "${PROP('AccountLabel')}: ${LABEL}",
       "metricName": "ForwardedBytes",
       "namespace": "AWS/Logs",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": {
         "name": "SCHEMA",
         "parameters": [
          { "name": "AWS/ApiGateway", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "select": {
         "name": "SUM",
         "parameters": [
          { "name": "Count", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT SUM(Count) FROM SCHEMA(\"AWS/ApiGateway\")",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🔴CloudWatch Logs🍷: Delivery Errors🚨 [Filtered by ${account_ids}]",
     "type": "stat",
     "description": "Delivery Errors [Filtered by ${account_ids}]",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "dimensions": { "LogGroupName": "*" },
       "label": "${PROP('AccountLabel')}: ${LABEL}",
       "metricName": "DeliveryErrors",
       "namespace": "AWS/Logs",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": {
         "name": "SCHEMA",
         "parameters": [
          { "name": "AWS/ApiGateway", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "select": {
         "name": "SUM",
         "parameters": [
          { "name": "Count", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT SUM(Count) FROM SCHEMA(\"AWS/ApiGateway\")",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "🔴CloudWatch Logs🍷: Throttle Count🚨 [Filtered by ${account_ids}]",
     "type": "stat",
     "description": "Throttle Count [Filtered by ${account_ids}]",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "accountId": "$account_ids",
       "label": "${PROP('AccountLabel')}: ${LABEL}",
       "metricName": "ThrottleCount",
       "namespace": "AWS/Logs",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": {
         "name": "SCHEMA",
         "parameters": [
          { "name": "AWS/ApiGateway", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "select": {
         "name": "SUM",
         "parameters": [
          { "name": "Count", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT SUM(Count) FROM SCHEMA(\"AWS/ApiGateway\")",
       "statistic": "Sum"
      }
     ]
    }
   ]
  }
 ]
}